; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ARWeb"
#define MyAppVersion "4.0"
#define MyAppPublisher "Allinweb AG"
#define MyAppURL "https://www.allinweb.ch/"
#define MyAppExeName "ARWeb-Scanner\exec_launcher.bat"
#define MyAppDefaultDir "C:\ARWeb\ARWeb-Scanner"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{6B19A0CE-E1EA-467B-BA64-FDDBA8B22CC0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
SetupIconFile=C:\ARWeb\ARWeb-Scanner\arweb.ico
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={#MyAppDefaultDir}
; DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName} v{#MyAppVersion}
AllowNoIcons=yes
LicenseFile=C:\ARWeb\ARWeb-Scanner\license.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=INSTALL-HOTFIX-v4.0
OutputDir=C:\ARWeb
SolidCompression=yes
WizardStyle=modern
UninstallDisplayName=uninstall-ARWeb-v4.0

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
; You might have other tasks here, keep them if needed.

[Files]
Source: "C:\ARWeb\ARWeb-Scanner\AR_Web_Engine.jar"; DestDir: "{app}\ARWeb-Scanner\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\AR_Web_Scanner.jar"; DestDir: "{app}\ARWeb-Scanner\"; Flags: ignoreversion
; Source: "C:\ARWeb\ARWeb-Scanner\ARWeb.lic"; DestDir: "{app}\ARWeb-Scanner\"; Flags: ignoreversion
; Source: "C:\ARWeb\ARWeb-Scanner\exec_launcher.bat"; DestDir: "{app}\ARWeb-Scanner\"; Flags: ignoreversion
; Source: "C:\ARWeb\ARWeb-Scanner\edgedriver-versions\*"; DestDir: "{app}\ARWeb-Scanner\edgedriver-versions\"; Flags: ignoreversion
; Source: "C:\ARWeb\ARWeb-Scanner\java\*"; DestDir: "{app}\ARWeb-Scanner\java\"; Flags: ignoreversion
; Source: "C:\ARWeb\ARWeb-Scanner\java\lib\*"; DestDir: "{app}\ARWeb-Scanner\java\lib\"; Flags: ignoreversion
; Source: "C:\ARWeb\ARWeb-Scanner\java\bin\*"; DestDir: "{app}\ARWeb-Scanner\java\bin\"; Flags: ignoreversion
; Source: "C:\ARWeb\ARWeb-Scanner\java\conf\*"; DestDir: "{app}\ARWeb-Scanner\java\conf\"; Flags: ignoreversion
; Source: "C:\ARWeb\ARWeb-Scanner\java\include\*"; DestDir: "{app}\ARWeb-Scanner\java\include\"; Flags: ignoreversion
; Source: "C:\ARWeb\ARWeb-Scanner\java\jmods\*"; DestDir: "{app}\ARWeb-Scanner\java\jmods\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\javaFX\*"; DestDir: "{app}\ARWeb-Scanner\javaFX\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\javaFX\bin\*"; DestDir: "{app}\ARWeb-Scanner\javaFX\bin\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\javaFX\lib\*"; DestDir: "{app}\ARWeb-Scanner\javaFX\lib\"; Flags: ignoreversion
; Source: "C:\ARWeb\ARWeb-Scanner\lang\*"; DestDir: "{app}\ARWeb-Scanner\lang\"; Flags: ignoreversion
; Source: "C:\ARWeb\ARWeb-Scanner\config\*"; DestDir: "{app}\ARWeb-Scanner\config\"; Flags: ignoreversion
; Source: "C:\ARWeb\ARWeb\database.mdb"; DestDir: "{app}\ARWeb\"; Flags: ignoreversion
; Source: "C:\ARWeb\ARWeb\ARWeb.config"; DestDir: "{app}\ARWeb\"; Flags: ignoreversion
; Source: "C:\ARWeb\ARWeb\priorities.properties"; DestDir: "{app}\ARWeb\"; Flags: ignoreversion
; Source: "C:\ARWeb\ARWeb\Logs\*"; DestDir: "{app}\ARWeb\Logs\"; Flags: ignoreversion
; Source: "C:\ARWeb\ARWeb\Reports\*"; DestDir: "{app}\ARWeb\Reports\"; Flags: ignoreversion
; Source: "C:\ARWeb\ARWeb\Excel\*"; DestDir: "{app}\ARWeb\Excel\"; Flags: ignoreversion
; Source: "C:\ARWeb\ARWeb\Export\*"; DestDir: "{app}\ARWeb\Export\"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
; Name: "{autodesktop}\{#MyAppName} v{#MyAppVersion}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
