; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ARWeb"
#define MyAppVersion "4.0-Full"
#define MyAppPublisher "Allinweb AG"
#define MyAppURL "https://www.allinweb.ch/"
#define MyAppExeName "ARWeb-Scanner\exec_launcher.bat"
#define MyAppDefaultDir "C:\ARWeb"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{6B19A0CE-E1EA-467B-BA64-FDDBA8B22CC0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
SetupIconFile=C:\ARWeb\ARWeb-Scanner\arweb.ico
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={#MyAppDefaultDir}
; DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName} v{#MyAppVersion}
AllowNoIcons=yes
LicenseFile=C:\ARWeb\ARWeb-Scanner\license.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=INSTALL-v4.0-Full
OutputDir=C:\ARWeb
SolidCompression=yes
WizardStyle=modern
UninstallDisplayName=uninstall-ARWeb-v4.0

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\ARWeb\ARWeb-Scanner\AR_Web_Engine.jar"; DestDir: "{app}\ARWeb-Scanner\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\AR_Web_Scanner.jar"; DestDir: "{app}\ARWeb-Scanner\"; Flags: ignoreversion
; Source: "C:\ARWeb\ARWeb-Scanner\ARWeb.lic"; DestDir: "{app}\ARWeb-Scanner\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\exec_launcher.bat"; DestDir: "{app}\ARWeb-Scanner\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\edgedriver-versions\*"; DestDir: "{app}\ARWeb-Scanner\edgedriver-versions\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\java\*"; DestDir: "{app}\ARWeb-Scanner\java\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\java\lib\*"; DestDir: "{app}\ARWeb-Scanner\java\lib\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\java\lib\jfr\*"; DestDir: "{app}\ARWeb-Scanner\java\lib\jfr\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\java\lib\security\*"; DestDir: "{app}\ARWeb-Scanner\java\lib\security\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\java\bin\*"; DestDir: "{app}\ARWeb-Scanner\java\bin\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\java\bin\server\*"; DestDir: "{app}\ARWeb-Scanner\java\bin\server\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\java\conf\*"; DestDir: "{app}\ARWeb-Scanner\java\conf\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\java\conf\management\*"; DestDir: "{app}\ARWeb-Scanner\java\conf\management\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\java\conf\security\*"; DestDir: "{app}\ARWeb-Scanner\java\conf\security\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\java\conf\security\policy\*"; DestDir: "{app}\ARWeb-Scanner\java\conf\security\policy\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\java\conf\security\policy\limited\*"; DestDir: "{app}\ARWeb-Scanner\java\conf\security\policy\limited\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\java\conf\security\policy\unlimited\*"; DestDir: "{app}\ARWeb-Scanner\java\conf\security\policy\unlimited\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\java\include\*"; DestDir: "{app}\ARWeb-Scanner\java\include\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\java\include\win32\*"; DestDir: "{app}\ARWeb-Scanner\java\include\win32\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\java\include\win32\bridge\*"; DestDir: "{app}\ARWeb-Scanner\java\include\win32\bridge\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\java\jmods\*"; DestDir: "{app}\ARWeb-Scanner\java\jmods\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\javaFX\*"; DestDir: "{app}\ARWeb-Scanner\javaFX\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\javaFX\bin\*"; DestDir: "{app}\ARWeb-Scanner\javaFX\bin\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\javaFX\lib\*"; DestDir: "{app}\ARWeb-Scanner\javaFX\lib\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\lang\*"; DestDir: "{app}\ARWeb-Scanner\lang\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\config\*"; DestDir: "{app}\ARWeb-Scanner\config\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb\database.mdb"; DestDir: "{app}\ARWeb\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb\ARWeb.config"; DestDir: "{app}\ARWeb\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb\priorities.properties"; DestDir: "{app}\ARWeb\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb\Logs\*"; DestDir: "{app}\ARWeb\Logs\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb\Reports\*"; DestDir: "{app}\ARWeb\Reports\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb\Excel\*"; DestDir: "{app}\ARWeb\Excel\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb\Export\*"; DestDir: "{app}\ARWeb\Export\"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName} v{#MyAppVersion}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
// Replaces all occurrences of "C\:\\ARWeb\\" in the config with the selected {app} path
function MyStringReplace(const S, OldPattern, NewPattern: string): string;
var
  P: Integer;
  ResultStr: string;
begin
  ResultStr := S;
  P := Pos(OldPattern, ResultStr);
  while P > 0 do
  begin
    Delete(ResultStr, P, Length(OldPattern));
    Insert(NewPattern, ResultStr, P);
    P := Pos(OldPattern, ResultStr);
  end;
  Result := ResultStr;
end;


procedure UpdateConfigFile(NewBasePath: String; AppNewPath: String);
var
  ConfigFile: String;
  Lines: TArrayOfString;
  i: Integer;
begin
  ConfigFile := ExpandConstant('{app}\ARWeb\ARWeb.config');
  AppNewPath := MyStringReplace(AppNewPath, '\', '|');
  AppNewPath := MyStringReplace(AppNewPath, '|', '\\');
  AppNewPath := MyStringReplace(AppNewPath, ':', '|');
  AppNewPath := MyStringReplace(AppNewPath, '|', '\:') + '\\';
  if LoadStringsFromFile(ConfigFile, Lines) then
  begin
    for i := 0 to GetArrayLength(Lines) - 1 do
    begin
      Log('Before: ' + Lines[i]);
      Lines[i] := MyStringReplace(Lines[i], 'C\:\\ARWeb\\', AppNewPath);
      Log('After: ' + Lines[i]);
    end;
    SaveStringsToFile(ConfigFile, Lines, False);
    MsgBox('The File : "' + ConfigFile + '" has been updated', mbInformation, MB_OK); 
  end
  else
  begin
    MsgBox('Failed to load ARWeb.config from ' + ConfigFile, mbError, MB_OK);
  end;
end;

// Automatically called after files are installed
procedure CurStepChanged(CurStep: TSetupStep);
  var
    AppNewPath,
    ExpectedPath: String;
begin
  if CurStep = ssPostInstall then
  begin
    // Escape backslashes: C:\MyPath → C:\\MyPath\\
    // EscapedAppPath := StringChangeEx(ExpandConstant('{app}'), '\', '\\', True) + '\\';
    // EscapedAppPath := MyStringReplace(ExpandConstant('{app}'), '\', '\\') + '\\';
    AppNewPath := ExpandConstant('{app}');
    ExpectedPath := ExpandConstant('{#MyAppDefaultDir}');
    if SameText(AppNewPath, ExpectedPath) then
      // MsgBox('Paths match!', mbInformation, MB_OK)
    else
      UpdateConfigFile(ExpandConstant('{app}\ARWeb\ARWeb.config'), AppNewPath);
  end;
end;
