; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ARWeb"
#define MyAppVersion "4.0"
#define MyAppPublisher "Alinweb AG"
#define MyAppURL "https://www.allinweb.ch/"
#define MyAppExeName "MyProg-x64.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{FCAB3B94-1D80-4E7A-B6C1-AE04B18224F1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
SetupIconFile=C:\ARWeb-Scanner\arweb.ico
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=C:\ARWeb-Scanner\ARWeb.lic
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=INSTALL
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Program Files (x86)\Inno Setup 6\Examples\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\ARWeb-Scanner\AR_Web_Engine.jar"; DestDir: "{app}\ARWeb-Scanner\"; Flags: ignoreversion
Source: "C:\ARWeb-Scanner\AR_Web_Scanner.jar"; DestDir: "{app}\ARWeb-Scanner\"; Flags: ignoreversion
Source: "C:\ARWeb-Scanner\ARWeb.lic"; DestDir: "{app}\ARWeb-Scanner\"; Flags: ignoreversion
Source: "C:\ARWeb-Scanner\exec_launcher.bat"; DestDir: "{app}\ARWeb-Scanner\"; Flags: ignoreversion
Source: "C:\ARWeb-Scanner\edgedriver-versions\*"; DestDir: "{app}\ARWeb-Scanner\edgedriver-versions\"; Flags: ignoreversion
Source: "C:\ARWeb-Scanner\java\*"; DestDir: "{app}\ARWeb-Scanner\java\"; Flags: ignoreversion
Source: "C:\ARWeb-Scanner\java\lib\*"; DestDir: "{app}\ARWeb-Scanner\java\lib\"; Flags: ignoreversion
Source: "C:\ARWeb-Scanner\java\bin\*"; DestDir: "{app}\ARWeb-Scanner\java\bin\"; Flags: ignoreversion
; Source: "C:\ARWeb-Scanner\javaFX\*"; DestDir: "{app}\ARWeb-Scanner\javaFX\"; Flags: ignoreversion
Source: "C:\ARWeb-Scanner\javaFX\bin\*"; DestDir: "{app}\ARWeb-Scanner\javaFX\bin\"; Flags: ignoreversion
Source: "C:\ARWeb-Scanner\javaFX\lib\*"; DestDir: "{app}\ARWeb-Scanner\javaFX\lib\"; Flags: ignoreversion
Source: "C:\ARWeb-Scanner\lang\*"; DestDir: "{app}\ARWeb-Scanner\lang\"; Flags: ignoreversion
Source: "C:\ARWeb-Scanner\config\*"; DestDir: "{app}\ARWeb-Scanner\config\"; Flags: ignoreversion
Source: "C:\ARWeb\database.mdb"; DestDir: "{app}\ARWeb\"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb.config"; DestDir: "{app}\ARWeb\"; Flags: ignoreversion
Source: "C:\ARWeb\priorities.properties"; DestDir: "{app}\ARWeb\"; Flags: ignoreversion
Source: "C:\ARWeb\Logs\*"; DestDir: "{app}\ARWeb\Logs\"; Flags: ignoreversion
Source: "C:\ARWeb\Reports\*"; DestDir: "{app}\ARWeb\Reports\"; Flags: ignoreversion
Source: "C:\ARWeb\Excel\*"; DestDir: "{app}\ARWeb\Excel\"; Flags: ignoreversion
Source: "C:\ARWeb\Export\*"; DestDir: "{app}\ARWeb\Export\"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

