; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ARWeb"
#define MyAppVersion "4.0"
#define MyAppPublisher "Allinweb AG"
#define MyAppURL "https://www.allinweb.ch/"
#define MyAppExeName "exec_launcher.bat"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{6B19A0CE-E1EA-467B-BA64-FDDBA8B22CC0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName=ARWeb v4.0
AllowNoIcons=yes
LicenseFile=C:\ARWeb\ARWeb-Scanner\ARWeb.lic
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=INSTALL
SetupIconFile=C:\ARWeb\ARWeb-Scanner\arweb.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\ARWeb\ARWeb-Scanner\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\config\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\ARWeb\ARWeb-Scanner\AR_Web_Engine.jar"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\AR_Web_Scanner.jar"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\ARWeb.lic"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\ARWeb\ARWeb-Scanner\exec_launcher.bat"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: shellexec postinstall skipifsilent

[Code]
// Replaces all occurrences of "C\:\\ARWeb\\" in the config with the selected {app} path
function MyStringReplace(const S, OldPattern, NewPattern: string): string;
var
  P: Integer;
  ResultStr: string;
begin
  ResultStr := S;
  P := Pos(OldPattern, ResultStr);
  while P > 0 do
  begin
    Delete(ResultStr, P, Length(OldPattern));
    Insert(NewPattern, ResultStr, P);
    P := Pos(OldPattern, ResultStr);
  end;
  Result := ResultStr;
end;


procedure UpdateConfigFile(NewBasePath: String);
var
  ConfigFile: String;
  Lines: TArrayOfString;
  i: Integer;
begin
  ConfigFile := ExpandConstant('{app}\ARWeb\ARWeb.config');
  if LoadStringsFromFile(ConfigFile, Lines) then
  begin
    for i := 0 to GetArrayLength(Lines) - 1 do
    begin
      Lines[i] := MyStringReplace(Lines[i], 'C:\ARWeb\', NewBasePath);
      //Lines[i] := StringChangeEx(Lines[i], 'C\:\\ARWeb\\', NewBasePath, True);
      // Lines[i] := StringReplace(Lines[i], 'C:\ARWeb\', NewBasePath, [rfReplaceAll]);
    end;
    SaveStringsToFile(ConfigFile, Lines, False);
  end
  else
  begin
    MsgBox('Failed to load ARWeb.config from ' + ConfigFile, mbError, MB_OK);
  end;
end;

// Automatically called after files are installed
procedure CurStepChanged(CurStep: TSetupStep);
var
  EscapedAppPath: String;
begin
  if CurStep = ssPostInstall then
  begin
    // Escape backslashes: C:\MyPath → C:\\MyPath\\
    // EscapedAppPath := StringChangeEx(ExpandConstant('{app}'), '\', '\\', True) + '\\';
    EscapedAppPath := MyStringReplace(ExpandConstant('{app}'), '\', '\\') + '\\';
    UpdateConfigFile(EscapedAppPath);
  end;
end;
