// Source code is unavailable, and was generated by the Fernflower decompiler.
package com.allinweb.ch.component.pane;

import com.allinweb.ch.component.listCell.ABRCellFactory;
import com.allinweb.ch.component.listCell.ComponentListCell;
import com.allinweb.ch.component.model.BlockDetailsDTO;
import com.allinweb.ch.component.model.BlockLoadDTO;
import com.allinweb.ch.component.model.BlockLoopInstructionLoadDTO;
import com.allinweb.ch.component.model.BotJobLoadDTO;
import com.allinweb.ch.component.model.InstructionDTO;
import com.allinweb.ch.component.model.InstructionReferenceLoadDTO;
import com.allinweb.ch.component.pane.base.ABRPane;
import com.allinweb.ch.component.scene.*;
import com.allinweb.ch.component.scene.base.ABRScene;
import com.allinweb.ch.control.ABRComponentBuilder;
import com.allinweb.ch.core.ABRSharedResources;
import com.allinweb.ch.driver.ABRWebDriver;
import com.allinweb.ch.persistence.BlockDTO;
import com.allinweb.ch.persistence.BlockLoopInstructionDTO;
import com.allinweb.ch.persistence.BotJobDTO;
import com.allinweb.ch.persistence.SavedBlockLoopInstructionDTO;
import com.allinweb.ch.persistence.SavedBlocksDTO;
import com.allinweb.ch.persistence.VariableUserDTO;
import com.allinweb.ch.socket.WebSocketStompServer;
import com.allinweb.ch.util.ABRConstants;
import com.allinweb.ch.util.ABRLogger;
import com.allinweb.ch.util.ABRPropertyEnum;
import com.allinweb.ch.util.ABRPropertyManager;
import com.allinweb.ch.util.ComboBoxVars;
import com.allinweb.ch.util.ExcelWriter;
import com.google.gson.Gson;
import java.io.File;
import java.io.IOException;
import java.net.ServerSocket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.stream.Collectors;
import javafx.animation.KeyFrame;
import javafx.animation.Timeline;
import javafx.application.Platform;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.concurrent.Task;
import javafx.concurrent.Worker;
import javafx.geometry.HPos;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.*;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.control.TextField;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.FontPosture;
import javafx.scene.text.FontWeight;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javafx.stage.Modality;
import javafx.stage.Stage;
import javafx.util.Duration;
import javax.swing.*;
import javax.websocket.server.ServerContainer;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.servlet.ServletContextHandler;
import org.eclipse.jetty.websocket.jsr356.server.deploy.WebSocketServerContainerInitializer;

public class ABRViewBotJobPane extends ABRPane {

    private static final String CONNECTION_TYPE = "jdbc:ucanaccess://";
    private static final String CONNECTION_PARAMETERS = ";memory=false;newDatabaseVersion=V2010";

    // Postgres
    private static boolean POSTGRES_DB = false;

    private Connection conn = null;
    private ObservableList<VariableUserDTO> variablesList;

    private ObservableList<ComboBoxVars> webPageItems = FXCollections.observableArrayList();

    private static final ABRComponentBuilder builder = new ABRComponentBuilder();
    private BotJobDTO botJob;
    private List<BotJobLoadDTO> botLoadJobs = new ArrayList<>();
    private ObservableList<BlockDTO> blockDTOObservableList;
    private ListView<BlockDTO> uiBlockList;

    private SimpleBooleanProperty isEditingBotJob = new SimpleBooleanProperty(false);
    Button refreshButton;
    Button openScannerButton;
    Button editBotJobButton;
    Button launchBotJobButton;
    Button saveBotJobButton;
    Button saveAsBotJobButton;
    Button printBotJobButton;
    Button copyBotJobButton;
    Button openExcelFileButton;
    Button generateExcelButton;
    Button openExcelFilterPanelButton;
    Button closeBotJobButton;

    Label botJobNameLabel;
    Label botJobDescriptionLabel;
    TextField botJobName;
    TextField botJobDescription;
    VBox botJobContainer;
    Button componentButton;
    VBox componentContainer;
    ListView<SavedBlocksDTO> componentList;

    private static final int SECONDS = 3; // Total seconds for the countdown
    private int remainingSeconds = SECONDS;
    private Timeline timeline;
    private ExecutorService executorService;
    private Alert alertToShow;
    private Server jettyServer;
    private ServerContainer wsContainer;
    private WebView webView = new WebView();
    private WebEngine webEngine;
    private ABRScene abrScene;

    public ABRViewBotJobPane(BotJobDTO botJob, ABRScene abrScene) {
        this.abrScene = abrScene;
        this.botJob = botJob;
        // Initialize database IF IS ACCESS TO BE USED
        variablesList = FXCollections.observableArrayList();

        String dataBaseType = ABRPropertyManager.getInstance().getProperty(ABRPropertyEnum.DATABASE_TYPE);

        if (dataBaseType != null && dataBaseType.equalsIgnoreCase("POSTGRES")) {
            POSTGRES_DB = true;
        } else {
            POSTGRES_DB = false;
        }

        if (!POSTGRES_DB) {
            initializeDatabase();
        }
        Platform.runLater(() -> loadJobVariables());
        Platform.runLater(() -> loadWebPageFields());
    }

    public void initUIComponents() {
        int port = 8080;

        String portSocket = ABRPropertyManager.getInstance().getProperty(ABRPropertyEnum.PORT_SOCKET);
        if (portSocket != null) {
            port = Integer.parseInt(portSocket);
        }

        // Start WebSocket server in a background thread
        int finalPort = port;
        new Thread(() -> {
                    try {
                        startWebSocketServer(finalPort);
                    } catch (Exception e) {
                        ABRLogger.getInstance(ABRWebDriver.class).fine("port Alrey in Use: " + finalPort);

                        Alert alert = new Alert(AlertType.ERROR);
                        alert.setTitle("Port Error");
                        alert.setHeaderText("Change the Port configuration\"");
                        alert.setContentText(String.format("Port %d already in Use!", finalPort));
                        alert.showAndWait();

                        //                        Stage stage = (Stage) ((Button) .getSource()).getScene().getWindow();
                        //                        stage.close();
                        return;
                    }
                })
                .start();

        // Create a label to display the countdown
        Label countdownLabel = new Label(String.valueOf(remainingSeconds));
        countdownLabel.setStyle("-fx-font-size: 24px;");
        countdownLabel.setVisible(false);
        // Create a stack pane to hold the label
        StackPane stackPane = new StackPane(countdownLabel);
        stackPane.setPadding(new Insets(20));
        // Create a dialog for the alert
        alertToShow = new Alert(AlertType.INFORMATION);
        alertToShow.setTitle("Countdown Alert");
        alertToShow.setHeaderText("Count Down");
        alertToShow.initModality(Modality.APPLICATION_MODAL);
        // Set the content of the alert
        alertToShow.getDialogPane().setContent(stackPane);
        // Create a timeline to update the countdown
        timeline = new Timeline(new KeyFrame(Duration.seconds(1), event -> {
            remainingSeconds--;
            countdownLabel.setText(String.valueOf(remainingSeconds));
            if (remainingSeconds <= 0) {
                timeline.stop(); // Stop the timeline when countdown finishes
                alertToShow.close(); // Close the alert dialog
            }
        }));

        this.refreshButton = builder.buildButton(
                "Refresh", ABRConstants.SPACE_ZERO, "/refresh.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.openScannerButton = builder.buildButton(
                "Scan", ABRConstants.SPACE_ZERO, "/open_browser.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.editBotJobButton = builder.buildButton(
                "Edit", ABRConstants.SPACE_ZERO, "/edit.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.launchBotJobButton = builder.buildButton(
                "Launch", ABRConstants.SPACE_ZERO, "/play.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.saveBotJobButton = builder.buildButton(
                "Save", ABRConstants.SPACE_ZERO, ABRConstants.ICON_SAVE, ABRConstants.SPACE_M, new Insets(5.0D));

        this.saveAsBotJobButton = builder.buildButton(
                "Save As", ABRConstants.SPACE_ZERO, ABRConstants.ICON_SAVE, ABRConstants.SPACE_M, new Insets(5.0D));
        this.printBotJobButton = builder.buildButton(
                "Print", ABRConstants.SPACE_ZERO, ABRConstants.ICON_PRINT, ABRConstants.SPACE_M, new Insets(5.0D));
        this.copyBotJobButton = builder.buildButton(
                "Copy", ABRConstants.SPACE_ZERO, ABRConstants.ICON_COPY, ABRConstants.SPACE_M, new Insets(5.0D));
        this.openExcelFileButton = builder.buildButton(
                "Excel File", ABRConstants.SPACE_ZERO, ABRConstants.ICON_EXCEL, ABRConstants.SPACE_M, new Insets(5.0D));
        this.generateExcelButton = builder.buildButton(
                "Generate", ABRConstants.SPACE_ZERO, ABRConstants.ICON_EXCEL, ABRConstants.SPACE_M, new Insets(5.0D));
        this.openExcelFilterPanelButton = builder.buildButton(
                "Filter", ABRConstants.SPACE_ZERO, ABRConstants.ICON_LIST, ABRConstants.SPACE_M, new Insets(5.0D));
        this.closeBotJobButton = builder.buildButton(
                "Close", ABRConstants.SPACE_ZERO, ABRConstants.ICON_CROSS, ABRConstants.SPACE_M, new Insets(5.0D));

        // Create a GridPane for the left side buttons
        GridPane leftGridPane = new GridPane();
        leftGridPane.setVgap(10); // Vertical spacing between elements
        leftGridPane.setHgap(10); // Horizontal spacing between elements

        // Define a uniform width for the buttons
        double buttonWidth = 100;

        // Add the top row of buttons
        refreshButton.setPrefWidth(buttonWidth);
        leftGridPane.add(refreshButton, 0, 0);

        openScannerButton.setPrefWidth(buttonWidth);
        leftGridPane.add(openScannerButton, 1, 0);

        saveBotJobButton.setPrefWidth(buttonWidth);
        leftGridPane.add(saveBotJobButton, 2, 0);

        saveAsBotJobButton.setPrefWidth(buttonWidth);
        leftGridPane.add(saveAsBotJobButton, 3, 0);

        editBotJobButton.setPrefWidth(buttonWidth);
        leftGridPane.add(editBotJobButton, 4, 0);

        launchBotJobButton.setPrefWidth(buttonWidth);
        leftGridPane.add(launchBotJobButton, 5, 0);

        // Add the bottom row of buttons
        //        saveBotJobButton.setPrefWidth(buttonWidth);
        //        leftGridPane.add(saveBotJobButton, 0, 1);

        //        saveAsBotJobButton.setPrefWidth(buttonWidth);
        //        leftGridPane.add(saveAsBotJobButton, 1, 1);

        openExcelFileButton.setPrefWidth(buttonWidth);
        leftGridPane.add(openExcelFileButton, 2, 1);

        generateExcelButton.setPrefWidth(buttonWidth);
        leftGridPane.add(generateExcelButton, 3, 1);

        openExcelFilterPanelButton.setPrefWidth(buttonWidth);
        leftGridPane.add(openExcelFilterPanelButton, 4, 1);

        closeBotJobButton.setPrefWidth(buttonWidth);
        leftGridPane.add(closeBotJobButton, 5, 1);

        // Center the buttons
        for (Node node : leftGridPane.getChildren()) {
            GridPane.setHalignment(node, HPos.CENTER);
        }

        // Other UI components

        double botJobNameWidth = 100;

        this.botJobNameLabel = new Label(this.botJob.getName());
        this.botJobNameLabel.setPrefWidth(botJobNameWidth);
        this.botJobName = new TextField(this.botJob.getName());
        this.botJobName.setPrefWidth(botJobNameWidth);

        this.initComponentUI();

        StackPane botJobNameGroup =
                new StackPane(new Node[] {this.botJobNameLabel, this.botJobName, this.componentButton});
        StackPane.setAlignment(this.componentButton, Pos.CENTER_RIGHT);
        StackPane.setMargin(this.componentButton, new Insets(5.0D, 0.0D, 0.0D, 0.0D));

        this.botJobDescriptionLabel = new Label(this.botJob.getDescription());
        this.botJobDescriptionLabel.setPrefWidth(botJobNameWidth);
        this.botJobDescription = new TextField(this.botJob.getDescription());
        this.botJobDescription.setPrefWidth(botJobNameWidth);

        StackPane botJobDescriptionGroup =
                new StackPane(new Node[] {this.botJobDescriptionLabel, this.botJobDescription});

        //        this.blockDTOObservableList = FXCollections.observableArrayList(ABRSharedResources.getInstance()
        //                .getEntityList(BlockDTO.class, blockDTO -> blockDTO.getBotJob().getId() == botJob.getId()));

        // Send a message to all connected clients after 5 seconds
        //        WebSocketStompServer.sendMessageToAll(jsonData);
        List<InstructionDTO> listForDeletion =
                WebSocketStompServer.getBlockLoopInstructionIdsWithNullBlock(this.botJob.getId());
        for (InstructionDTO instruction : listForDeletion) {
            WebSocketStompServer.deleteInstruction(this.botJob.getId(), instruction);
        }
        WebSocketStompServer.deleteNullBlocks(this.botJob.getId());
        WebSocketStompServer.updateBlockOrderNumber(WebSocketStompServer.selectAllBlocks(this.botJob.getId()));

        loadBlockAll(botJob.getId());

        Gson gson = new Gson();
        String jsonData = "";

        // Load blocks based on the BotJobLoadDTO instead of blockDTOObservableList
        if (botLoadJobs.size() > 0) {

            List<InstructionDTO> rowList = null;
            for (BlockLoadDTO block : botLoadJobs.get(0).getBlockLoadDTOList()) {
                rowList = getInstructionsByBlockId(botLoadJobs.get(0).getId(), block.getId());
                reorderInstructions(rowList);
            }

            List<BlockLoopInstructionLoadDTO> blockLoopInstructions = botLoadJobs.get(0).getBlockLoadDTOList().stream()
                    .flatMap(blockLoadDTO -> blockLoadDTO.getBlockLoopInstructionLoadDTOS().stream()
                            .map(blockLoopInstructionDTO -> new BlockLoopInstructionLoadDTO(
                                    botLoadJobs.get(0).getId(), // Use botJobLoadDTO instead of botJob
                                    blockLoopInstructionDTO.getId(),
                                    blockLoopInstructionDTO.getInstructionOrderNumber(),
                                    blockLoopInstructionDTO.getName(),
                                    blockLoopInstructionDTO.getDescription(),
                                    blockLoadDTO.getId(), // block ID from BlockLoadDTO
                                    blockLoadDTO.getBlockOrderNumber(),
                                    blockLoadDTO.getName(),
                                    blockLoopInstructionDTO.getActions(),
                                    blockLoopInstructionDTO.getParentId(),
                                    blockLoopInstructionDTO.getOperation())))
                    .collect(Collectors.toList());

            jsonData = gson.toJson(blockLoopInstructions);
        } else {
            jsonData = "[]";
        }

        webEngine = webView.getEngine();
        webEngine.javaScriptEnabledProperty().set(true);

        buildWebView(jsonData, finalPort);

        //        this.uiBlockList = new ListView<>(blockDTOObservableList);
        //
        //        this.uiBlockList.setCellFactory(new ABRCellFactory<>(BlockListCell.class)::call);
        //        this.uiBlockList.setMaxHeight(Double.MAX_VALUE);
        //        this.uiBlockList.setMaxWidth(Double.MAX_VALUE);
        //        this.uiBlockList.setPrefHeight(900.0D);
        //        this.uiBlockList.setBorder(null);

        HBox compBox = new HBox(new Node[] {this.webView, this.componentContainer});
        HBox.setHgrow(this.webView, Priority.ALWAYS);
        HBox.setHgrow(this.componentContainer, Priority.ALWAYS);
        this.botJobContainer = new VBox(new Node[] {leftGridPane, botJobNameGroup, botJobDescriptionGroup, compBox});
        AnchorPane.setTopAnchor(this.botJobContainer, ABRConstants.SPACE_M);
        AnchorPane.setBottomAnchor(this.botJobContainer, ABRConstants.SPACE_M);
        AnchorPane.setLeftAnchor(this.botJobContainer, ABRConstants.SPACE_M);
        AnchorPane.setRightAnchor(this.botJobContainer, ABRConstants.SPACE_M);

        // Add the stylesheet to the scene
        //        mainGridPane.getStylesheets().add(css);

    }

    private void buildWebView(String jsonData, int finalPort) {
        webEngine.load(getClass().getResource("/build/index.html").toExternalForm());

        webEngine.getLoadWorker().stateProperty().addListener((obs, oldState, newState) -> {
            if (newState == Worker.State.SUCCEEDED) {
                // After the page has successfully loaded
                try {
                    webEngine.executeScript("setTimeout(function() { window.receiveDataFromJava(JSON.stringify("
                            + jsonData + "), " + finalPort + ") }, 1000)");
                } catch (Exception e) {
                    ABRLogger.getInstance(ABRViewBotJobPane.class).severe("buildWebView  \nError: " + e.getMessage());
                }
            }
        });
    }

    public void initUIBehaviour() {
        refreshButton.setOnMouseClicked(e -> {
            stopWebSocketServer();
            Stage stage = (Stage) ((Button) e.getSource()).getScene().getWindow();
            stage.close();

            new ABRViewBotJobScene(botJob.getId()).show();
        });
        saveAsBotJobButton.setOnMouseClicked(e -> new ABRSaveBotJobAsScene(botJob.getId()).show());
        this.botJobNameLabel.visibleProperty().bind(this.isEditingBotJob.not());
        this.botJobDescriptionLabel.visibleProperty().bind(this.isEditingBotJob.not());
        this.botJobName.visibleProperty().bind(this.isEditingBotJob);
        this.botJobDescription.visibleProperty().bind(this.isEditingBotJob);
        this.editBotJobButton.setOnMouseClicked((e) -> {
            this.isEditingBotJob.set(this.isEditingBotJob.not().getValue());
        });
        this.saveBotJobButton.setOnMouseClicked((e) -> {
            this.isEditingBotJob.set(false);
            this.botJobNameLabel.setText(this.botJobName.getText());
            this.botJobDescriptionLabel.setText(this.botJobDescription.getText());
            this.botJob.setName(this.botJobNameLabel.getText());
            this.botJob.setDescription(this.botJobDescriptionLabel.getText());
            ABRSharedResources.getInstance().updateEntity(this.botJob, BotJobDTO.class);
        });
        this.openScannerButton.setOnMouseClicked((e) -> {
            ABRLogger.getInstance(ABRWebDriver.class).fine("Calling openScannerButton");

            abrScene.startNewThread(() -> executeScannerTask());
        });

        this.generateExcelButton.setOnMouseClicked((e) -> {
            BotJobDTO botJobUpdated =
                    (BotJobDTO) ABRSharedResources.getInstance().getEntityById(BotJobDTO.class, this.botJob.getId());
            Task<Void> excel = new Task<>() {
                @Override
                protected Void call() throws Exception {
                    new ExcelWriter().generateExcelFiles(botJobUpdated);
                    return null;
                }
            };
            if (ExcelWriter.isFileExits(this.botJob)) {
                System.out.println("warning");
                new ABRAlertScene(
                        AlertType.INFORMATION,
                        "Warning: Excel File already exist",
                        "Excel File already exists: overwrite it?",
                        () -> {
                            new Thread(excel).start();
                        },
                        new ButtonType[] {ButtonType.OK});
            } else {

                new ABRAlertScene(
                        AlertType.INFORMATION,
                        "Excel file generated",
                        "The excel file has been generated successfully",
                        new ButtonType[] {ButtonType.OK});
                new Thread(excel).start();
            }
        });
        this.openExcelFilterPanelButton.setOnMouseClicked((e) -> {
            (new ABRExportFilterScene(this.botJob)).show();
        });
        this.launchBotJobButton.setOnMouseClicked((e) -> {
            ABRPropertyManager managerProps = ABRPropertyManager.getInstance();
            String enginePath = managerProps.getProperty(ABRPropertyEnum.PATH_ENGINE) + "\\ABR_Web_Engine.jar";
            String excelPath = ABRPropertyManager.getInstance().getProperty(ABRPropertyEnum.FOLDER_PATH_EXCEL);
            excelPath = excelPath + "\\" + this.botJob.getName() + ".xlsx";
            if (!(new File(excelPath)).exists()) {
                new ABRAlertScene(
                        AlertType.WARNING,
                        "Missing file excel",
                        "Please generate and compile the data of the file excel first before launching the bot job",
                        new ButtonType[] {ButtonType.OK});
            }

            String[] command = new String[] {
                "cmd.exe",
                "/c",
                ".\\java\\bin\\java.exe",
                "-jar",
                "\"" + enginePath + "\"",
                "execute/j",
                String.valueOf(this.botJob.getHomeBanking().getId()),
                String.valueOf(this.botJob.getId()),
                "\"" + excelPath + "\"",
                "-c",
                ABRPropertyManager.getConfigurationFileName()
            };
            ProcessBuilder processBuilder = new ProcessBuilder(command);
            processBuilder.directory(new File(ABRConstants.CURRENT_PATH));
            String logPath = ABRPropertyManager.getInstance().getProperty(ABRPropertyEnum.FOLDER_PATH_LOG);
            File output = new File(logPath + "\\engine_debug_log_output.log");
            File error = new File(logPath + "\\engine_debug_log_error.log");
            File input = new File(logPath + "\\engine_debug_log_input.log");
            List<File> files = new ArrayList<File>();
            files.add(output);
            files.add(error);
            files.add(input);

            Iterator<File> var11 = files.iterator();

            while (var11.hasNext()) {
                File file = (File) var11.next();
                if (!file.exists()) {
                    try {
                        file.createNewFile();
                    } catch (IOException var15) {
                        var15.printStackTrace();
                    }
                }
            }

            processBuilder.redirectOutput(output);
            processBuilder.redirectError(error);
            processBuilder.redirectInput(input);

            try {
                processBuilder.start();
            } catch (IOException var14) {
                var14.printStackTrace();
            }
        });
        this.closeBotJobButton.setOnMouseClicked((e) -> {
            stopWebSocketServer();
            Stage stage = (Stage) ((Button) e.getSource()).getScene().getWindow();
            stage.close();
        });
        this.openExcelFileButton.setOnMouseClicked((e) -> {
            try {
                String excelFilePath = ABRPropertyManager.getInstance().getProperty(ABRPropertyEnum.FOLDER_PATH_EXCEL);
                excelFilePath = excelFilePath + "\\" + this.botJob.getName() + ".xlsx";
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + excelFilePath);
            } catch (IOException var3) {
                var3.printStackTrace();
            }
        });
        this.componentButton.setOnMouseClicked((e) -> {
            if (this.componentContainer.isVisible()) {
                this.componentContainer.setVisible(false);
                this.componentContainer.setManaged(false);
            } else {
                this.componentContainer.setVisible(true);
                this.componentContainer.setManaged(true);
            }
        });
    }

    private void executeScannerTask() {
        try {
            Platform.runLater(() -> {
                try {
                    // Call the ABRScannedElementScene here
                    ABRScannedElementScene scene = new ABRScannedElementScene(
                            this.botJob.getHomeBanking().getPriority(),
                            this.botJob.getId(),
                            this.botJob.getBlocks() != null
                                            && this.botJob.getBlocks().size() > 0
                                    ? this.botJob.getBlocks().get(0).getId()
                                    : null);
                    scene.show(); // Make sure the scene is shown
                } catch (Exception ex) {
                    handleExceptionScan(ex);
                }
            });
        } catch (Exception ex) {
            handleExceptionScan(ex);
        }
    }

    private void handleExceptionScan(Exception ex) {
        // Log the exception
        ABRLogger.getInstance(ABRWebDriver.class)
                .severe("ERROR Calling openScannerButton\n" + ex.getMessage() + "\nRoot cause: " + ex.getMessage());

        // Display the error message to the user
        Platform.runLater(() -> {
            JOptionPane.showMessageDialog(
                    null,
                    "An error has occurred Calling SCAN: \nError: " + ex.getMessage() + "\nCause: " + ex.getMessage(),
                    "Error calling in SCAN",
                    JOptionPane.ERROR_MESSAGE);
        });
    }

    private void showAlert(String title, String content) {
        executorService = Executors.newSingleThreadExecutor();
        alertToShow.setAlertType(AlertType.ERROR);
        alertToShow.setTitle("Error");
        alertToShow.setHeaderText(title);
        alertToShow.setContentText(content);

        executorService.execute(() -> {
            timeline.setCycleCount(SECONDS); // Run for SECONDS seconds
            timeline.play(); // Start the timeline

            // Show the alert on the JavaFX Application Thread
            javafx.application.Platform.runLater(() -> alertToShow.showAndWait());
        });

        if (executorService != null) {
            remainingSeconds = SECONDS;
            executorService.shutdown();
        }
    }

    public Pane getPaneReference() {
        AnchorPane acAnchorPane = new AnchorPane(new Node[] {this.botJobContainer});
        acAnchorPane.setUserData(this);
        return acAnchorPane;
    }

    private void initComponentUI() {
        this.componentButton = builder.buildButton(
                "",
                ABRConstants.SPACE_L,
                "/Cubes.png",
                ABRConstants.SPACE_L + 10.0D,
                Insets.EMPTY,
                Background.fill(Color.TRANSPARENT));
        ObservableList<SavedBlocksDTO> savedBlocksDTO =
                ABRSharedResources.getInstance().getEntityList(SavedBlocksDTO.class);
        this.componentList = new ListView<SavedBlocksDTO>(savedBlocksDTO);

        componentList.setCellFactory(new ABRCellFactory<>(ComponentListCell.class)::call);
        this.componentList.setMaxHeight(Double.MAX_VALUE);
        this.componentList.setPrefHeight(900.0D);
        this.componentList.setUserData(this);
        this.componentList.getUserData();
        VBox.setVgrow(componentList, Priority.ALWAYS);

        Label componentTitleLabel = new Label("Components");
        componentTitleLabel.setPadding(new Insets(5.0D));
        componentTitleLabel.setFont(
                Font.font((String) null, FontWeight.BOLD, FontPosture.REGULAR, ABRConstants.SPACE_SM + 4.0D));
        Label searchLabel = new Label("Find");
        searchLabel.setPadding(new Insets(5.0D));
        searchLabel.setFont(
                Font.font((String) null, FontWeight.BOLD, FontPosture.REGULAR, ABRConstants.SPACE_SM + 2.0D));
        TextField searchTextField = new TextField();

        searchTextField.textProperty().addListener((observable, oldValue, newValue) -> {
            ObservableList<SavedBlocksDTO> savedBlocksDTOs;
            if (!newValue.equals("")) {
                System.out.println(newValue + " Text");
                savedBlocksDTOs = ABRSharedResources.getInstance().getEntityList(SavedBlocksDTO.class, (savedBlock) -> {
                    return savedBlock.getName().toLowerCase().contains(newValue.toLowerCase());
                });
            } else {
                savedBlocksDTOs = ABRSharedResources.getInstance().getEntityList(SavedBlocksDTO.class);
            }

            this.componentList.setItems(savedBlocksDTOs);
            this.componentList.refresh();
        });

        createMockSavedBlocksDTOs();

        HBox searchPaneBox = new HBox(new Node[] {searchLabel, searchTextField});
        searchPaneBox.setMaxHeight(ABRConstants.SPACE_XL);
        searchPaneBox.setSpacing(ABRConstants.SPACE_XXS);
        HBox.setHgrow(searchTextField, Priority.ALWAYS);

        this.componentContainer = new VBox(new Node[] {componentTitleLabel, searchPaneBox, componentList});
        this.componentContainer.setSpacing(ABRConstants.SPACE_XS);
        this.componentContainer.setMaxWidth(200.0D);
        this.componentContainer.setVisible(false);
        this.componentContainer.setManaged(false);
    }

    public BotJobDTO getBotJobDTO() {
        return this.botJob;
    }

    private void addWaitTask(Integer secondsToWait) {
        Alert alert = new Alert(
                Alert.AlertType.CONFIRMATION,
                "Are you sure you want to add a wait of " + secondsToWait + " seconds to the botjob?",
                ButtonType.YES,
                ButtonType.NO);
        Optional<ButtonType> result = alert.showAndWait();
        if (result.isPresent() && result.get() == ButtonType.YES) {
            Task<Void> waitTask = new Task<>() {
                @Override
                protected Void call() throws Exception {
                    List<BlockLoopInstructionDTO> instructionList =
                            botJob.getBlocks().get(0).getBlockLoopInstructions();
                    BlockLoopInstructionDTO waitInstruction = new BlockLoopInstructionDTO();
                    waitInstruction.setName("Wait " + secondsToWait + "second(s)");
                    waitInstruction.setDescription("Waiting action");
                    waitInstruction.setEncrypted(false);
                    waitInstruction.setInstructionOrderNumber(instructionList.size());
                    waitInstruction.setOptional(false);
                    waitInstruction.setActions(ABRConstants.HOLD);
                    waitInstruction.setOnHoldSeconds(secondsToWait);
                    waitInstruction.setBlock(botJob.getBlocks().get(0));
                    waitInstruction.setExportToABR(false);
                    ABRSharedResources.getInstance()
                            .addEntity(
                                    waitInstruction,
                                    BlockLoopInstructionDTO.class,
                                    () -> new ABRAlertScene(
                                            Alert.AlertType.INFORMATION,
                                            "Instruction Added",
                                            "Instruction Wait " + secondsToWait
                                                    + " second(s) has been added successfully",
                                            ButtonType.OK));
                    return null;
                }
            };
            new Thread(waitTask).start();
        }
    }

    private void addInstruction(String name, String operation, Integer varId) {
        Alert alert = new Alert(
                Alert.AlertType.CONFIRMATION,
                "Are you sure you want to add a " + name + " to the botjob?",
                ButtonType.YES,
                ButtonType.NO);
        Optional<ButtonType> result = alert.showAndWait();
        if (result.isPresent() && result.get() == ButtonType.YES) {
            Task<Void> waitTask = new Task<>() {
                @Override
                protected Void call() throws Exception {
                    List<BlockLoopInstructionDTO> instructionList =
                            botJob.getBlocks().get(0).getBlockLoopInstructions();
                    BlockLoopInstructionDTO instruction = new BlockLoopInstructionDTO();
                    instruction.setName(name);
                    instruction.setOperation(operation);
                    instruction.setVariableId(varId);
                    instruction.setEncrypted(false);
                    instruction.setInstructionOrderNumber(instructionList.size());
                    instruction.setOptional(false);
                    if (name.equalsIgnoreCase("setValue")) {
                        instruction.setActions(ABRConstants.SET_VALUE);
                    } else if (name.equalsIgnoreCase("getValue")) {
                        instruction.setActions(ABRConstants.GET_VALUE);
                    } else if (name.equalsIgnoreCase("check")) {
                        instruction.setActions(ABRConstants.CHECK_VALUE);
                    }
                    instruction.setOnHoldSeconds(1);
                    instruction.setBlock(botJob.getBlocks().get(0));
                    instruction.setExportToABR(false);
                    ABRSharedResources.getInstance()
                            .addEntity(
                                    instruction,
                                    BlockLoopInstructionDTO.class,
                                    () -> new ABRAlertScene(
                                            Alert.AlertType.INFORMATION,
                                            "Instruction Added",
                                            "Instruction " + instruction.getName() + " has been added successfully",
                                            ButtonType.OK));
                    return null;
                }
            };
            new Thread(waitTask).start();
        }
    }

    private void initializeDatabase() {

        String dbPath = ABRPropertyManager.getInstance().getProperty(ABRPropertyEnum.FOLDER_PATH_DB);
        String dbUrl = CONNECTION_TYPE + dbPath + ABRConstants.FILE_NAME_DB + CONNECTION_PARAMETERS;

        File dbFile = new File(dbPath + ABRConstants.FILE_NAME_DB);
        if (!dbFile.exists()) {
            try (Connection conn = DriverManager.getConnection(dbUrl)) {
                try (Statement stmt = conn.createStatement()) {
                    String createTableSQL = "CREATE TABLE home_banking (" + "ID AUTOINCREMENT PRIMARY KEY, "
                            + "name TEXT, password TEXT, url TEXT, username TEXT, priority TEXT)";
                    stmt.executeUpdate(createTableSQL);
                }
                System.out.println(String.format("Database %s has bee created!", dbFile.getName()));
            } catch (SQLException e) {
                ABRLogger.getInstance(ABRViewBotJobPane.class).severe("initializeDatabase\nError: " + e.getMessage());
            }
        } else {
            ABRLogger.getInstance(ABRViewBotJobPane.class)
                    .info(String.format("Database '%s' Already exist!", dbFile.getName()));
        }
    }

    private void loadJobVariables() {
        variablesList.clear();
        String selectSQL = " SELECT vars.id, vars.type, vars.name, vars.value, COUNT(blk.variable_id) UsedVars "
                + " FROM variable vars "
                + " left join block_loop_instruction blk on blk.variable_id = vars.id "
                + " where bot_job_id = " + this.botJob.getId()
                //                                + " and  block_loop_instruction_id = " + instructionId
                + " group by vars.id, vars.type, vars.Name, vars.value ";
        try (Statement stmt = ABRSharedResources.getInstance().getConnection().createStatement();
                ResultSet rs = stmt.executeQuery(selectSQL)) {
            while (rs.next()) {
                int id = rs.getInt("ID");
                String type = rs.getString("type");
                String name = rs.getString("name");
                String value = rs.getString("value");
                String usedVars = rs.getString("UsedVars");
                variablesList.add(new VariableUserDTO(id, type, name, value, this.botJob.getId(), -1, usedVars));
            }
        } catch (SQLException e) {
            ABRLogger.getInstance(ABRViewBotJobPane.class).severe("loadJobVariables  \nError: " + e.getMessage());
        }
    }

    private void loadWebPageFields() {
        webPageItems.clear();
        String selectSQL = " SELECT  "
                + "  bj.id AS bot_job_id,  "
                + "  bli.id AS block_loop_instruction_id,  "
                + "  bli.instruction_order_number,  "
                + "  bli.actions,  "
                + "  bli.name AS instruction_name,  "
                + "  bli.path,  "
                + "  bli.operation      "
                + " FROM bot_job bj  "
                + " LEFT JOIN block b ON b.bot_job_id = bj.id  "
                + " JOIN block_loop_instruction bli ON bli.block_id = b.id  "
                + " where bj.id = " + this.botJob.getId()
                + "   and operation is null  "
                + "  ORDER BY bj.id, b.block_order_number, bli.instruction_order_number ASC;";

        try (Statement stmt = ABRSharedResources.getInstance().getConnection().createStatement();
                ResultSet rs = stmt.executeQuery(selectSQL)) {
            while (rs.next()) {
                int id = rs.getInt("block_loop_instruction_id");
                String name = rs.getString("instruction_name");
                String actions = rs.getString("actions");

                // Filter out "SET", "GET", "CK", and "H"
                if (actions != null
                        && !actions.equalsIgnoreCase(ABRConstants.SET_VALUE)
                        && !actions.equalsIgnoreCase(ABRConstants.GET_VALUE)
                        && !actions.equalsIgnoreCase(ABRConstants.CHECK_VALUE)
                        && !actions.equalsIgnoreCase(ABRConstants.EXTRACT_FIELD)
                        && !actions.equalsIgnoreCase(ABRConstants.SCREEN)
                        && !actions.equalsIgnoreCase(ABRConstants.QUIT)
                        && !actions.equalsIgnoreCase(ABRConstants.HOLD)
                        && !actions.equalsIgnoreCase(ABRConstants.IF_ELSE)
                        && !actions.equalsIgnoreCase(ABRConstants.GOTO)) {
                    webPageItems.add(new ComboBoxVars(name, name, id, -1));
                }
            }
        } catch (SQLException e) {
            ABRLogger.getInstance(ABRWebDriver.class)
                    .severe(String.format(
                            "loadWebPageFields - Error selecting Web Page Fields.\n Error: %s", e.getMessage()));
        }
    }

    public void startWebSocketServer(int port) throws Exception {
        // Check if the port is available
        if (isPortInUse(port)) {
            throw new Exception("Port " + port + " is already in use.");
        }

        // Set up Jetty server to run WebSocket endpoint
        jettyServer = new Server(port); // Server listens on port 8080
        ServletContextHandler context = new ServletContextHandler(ServletContextHandler.SESSIONS);
        context.setContextPath("/");
        jettyServer.setHandler(context);

        // Initialize WebSocket container
        wsContainer = WebSocketServerContainerInitializer.configureContext(context);
        //        wsContainer.setDefaultMaxSessionIdleTimeout(600000);
        wsContainer.addEndpoint(WebSocketStompServer.class);

        // Start Jetty server
        jettyServer.start();
        System.out.println("WebSocket server started at ws://localhost:8080/websocket");
    }

    // Method to check if the port is already in use
    private boolean isPortInUse(int port) {
        try (ServerSocket serverSocket = new ServerSocket(port)) {
            return false; // Port is available
        } catch (IOException e) {
            return true; // Port is already in use
        }
    }

    private int saveBlock(BlockDetailsDTO blockDTO) {
        // Generate a Unique-ID for the block
        Integer nextId = loadNextIdBlockData() + 1;
        Integer nextBlockOrder = loadNextBlockOrderNUmber(blockDTO.getBotJobId());

        // Build the SQL insert query
        String insertSQL = "INSERT INTO block(id, block_order_number, description, name, type_id, bot_job_id) VALUES ("
                + nextId + ", "
                + nextBlockOrder + ", " // block_order_number
                + "'" + blockDTO.getBlockName() + " description', " // description
                + "'" + blockDTO.getBlockName() + "', " // name
                + 1 + ", " // type_id
                + blockDTO.getBotJobId() + ")"; // bot_job_id, assuming BotJobDTO has an ID

        try (Statement stmt = ABRSharedResources.getInstance().getConnection().createStatement()) {
            stmt.executeUpdate(insertSQL);
            System.out.println("Block data saved successfully.");
            return nextId;
        } catch (SQLException e) {
            ABRLogger.getInstance(ABRViewBotJobPane.class).severe("saveBlock  \nError: " + e.getMessage());
            return -1;
        }
    }

    private Integer loadNextIdBlockData() {
        //        String selectSQL = "SELECT NEXT_VAL fROM homeBankingSeq";
        String selectSQL = "SELECT MAX(ID) AS max_id FROM block";
        try (Statement stmt = ABRSharedResources.getInstance().getConnection().createStatement();
                ResultSet rs = stmt.executeQuery(selectSQL)) {
            while (rs.next()) {
                return rs.getInt("max_id");
            }
        } catch (SQLException e) {
            ABRLogger.getInstance(ABRViewBotJobPane.class).severe("loadNextIdBlockData  \nError: " + e.getMessage());
        }
        return null;
    }

    private Integer loadNextBlockOrderNUmber(int botJobId) {
        //        String selectSQL = "SELECT NEXT_VAL fROM homeBankingSeq";
        String selectSQL = "SELECT MAX(ID) AS max_id FROM block where bot_job_id = " + botJobId;
        try (Statement stmt = ABRSharedResources.getInstance().getConnection().createStatement();
                ResultSet rs = stmt.executeQuery(selectSQL)) {
            while (rs.next()) {
                return rs.getInt("max_id");
            }
        } catch (SQLException e) {
            ABRLogger.getInstance(ABRViewBotJobPane.class).severe("loadNextIdBlockData  \nError: " + e.getMessage());
        }
        return null;
    }

    public void stopWebSocketServer() {
        if (jettyServer != null && jettyServer.isStarted()) {
            try {
                jettyServer.stop();
            } catch (Exception e) {
                ABRLogger.getInstance(ABRViewBotJobPane.class)
                        .severe("stopWebSocketServer  \nError: " + e.getMessage());
            }
            jettyServer.destroy();
            ABRLogger.getInstance(ABRViewBotJobPane.class).info("WebSocket server stopped.");
            //            System.out.println("WebSocket server stopped.");
        }
    }

    private void loadBlockAll(int botJobId) {
        String query = "SELECT bj.id AS bot_job_id, bj.name AS bot_job_name, "
                + " b.id AS block_id, b.block_order_number, b.name AS block_name, "
                + " b.description AS block_description, b.type_id, "
                + " bli.id AS block_loop_instruction_id, bli.instruction_order_number, "
                + " bli.actions, bli.name AS instruction_name, bli.path, bli.description AS instruction_description, "
                + " bli.optional, bli.block_marked, bli.default_val, bli.action_custom_max_wait_sec, "
                + " bli.on_hold_seconds, bli.encrypted, bli.export_to_abr, "
                + " irl.reference_type, irl.value, "
                + "  bli.operation, bli.parent_id "
                + " FROM bot_job bj "
                + " LEFT JOIN block b ON b.bot_job_id = bj.id "
                + " JOIN block_loop_instruction bli ON bli.block_id = b.id "
                + " LEFT JOIN instruction_reference irl ON irl.block_loop_instruction_id = bli.id "
                + " where bot_job_id = " + botJobId
                + "  ORDER BY bj.id, b.block_order_number, bli.instruction_order_number, irl.id ASC";

        try (Statement stmt = ABRSharedResources.getInstance().getConnection().createStatement();
                ResultSet rs = stmt.executeQuery(query)) {

            Map<Integer, BotJobLoadDTO> botJobMap = new HashMap<>();
            Map<Integer, BlockLoadDTO> blockMap = new HashMap<>();
            Map<Integer, BlockLoopInstructionLoadDTO> instructionMap = new HashMap<>();

            botLoadJobs.clear();

            while (rs.next()) {
                botJobId = rs.getInt("bot_job_id");
                BotJobLoadDTO botJobDTO = botJobMap.get(botJobId);

                if (botJobDTO == null) {
                    botJobDTO = new BotJobLoadDTO();
                    botJobDTO.setId(botJobId);
                    botJobDTO.setName(rs.getString("bot_job_name"));
                    botJobDTO.setBlockLoadDTOList(new ArrayList<>());
                    botJobMap.put(botJobId, botJobDTO);
                    botLoadJobs.add(botJobDTO);
                }

                int blockId = rs.getInt("block_id");
                BlockLoadDTO blockDTO = blockMap.get(blockId);

                if (blockDTO == null) {
                    blockDTO = new BlockLoadDTO();
                    blockDTO.setId(blockId);
                    blockDTO.setBlockOrderNumber(rs.getInt("block_order_number"));
                    blockDTO.setName(rs.getString("block_name"));
                    blockDTO.setDescription(rs.getString("block_description"));
                    blockDTO.setTypeId(rs.getInt("type_id"));
                    blockDTO.setBotJobId(botJobDTO.getId());
                    blockDTO.setBotJobName(botJobDTO.getName());

                    blockDTO.setBlockLoopInstructionLoadDTOS(new ArrayList<>());
                    botJobDTO.getBlockLoadDTOList().add(blockDTO);
                    blockMap.put(blockId, blockDTO);
                }

                int instructionId = rs.getInt("block_loop_instruction_id");
                BlockLoopInstructionLoadDTO instruction = instructionMap.get(instructionId);

                if (instruction == null) {
                    instruction = new BlockLoopInstructionLoadDTO();
                    instruction.setId(instructionId);
                    instruction.setInstructionOrderNumber(rs.getInt("instruction_order_number"));
                    instruction.setActions(rs.getString("actions"));
                    instruction.setName(rs.getString("instruction_name"));
                    instruction.setPath(rs.getString("path"));
                    instruction.setDescription(rs.getString("instruction_description"));
                    instruction.setOptional(rs.getInt("optional"));
                    instruction.setBlockMarked(rs.getBoolean("block_marked"));
                    instruction.setDefault_val(rs.getString("default_val"));
                    instruction.setActionCustomMaxWaitSec(rs.getInt("action_custom_max_wait_sec"));
                    instruction.setOnHoldSeconds(rs.getInt("on_hold_seconds"));
                    instruction.setEncrypted(rs.getInt("encrypted"));
                    instruction.setExportToABR(rs.getInt("export_to_abr"));
                    instruction.setOperation(rs.getString("operation"));
                    instruction.setParentId(rs.getInt("parent_id"));

                    instruction.setInstructionReferenceLoadDTOList(new ArrayList<>());
                    blockDTO.getBlockLoopInstructionLoadDTOS().add(instruction);
                    instructionMap.put(instructionId, instruction);
                }

                String referenceType = rs.getString("reference_type");
                if (referenceType != null) {
                    InstructionReferenceLoadDTO reference = new InstructionReferenceLoadDTO();
                    reference.setReferenceType(referenceType);
                    reference.setValue(rs.getString("value"));
                    instruction.getInstructionReferenceLoadDTOList().add(reference);
                }
            }
        } catch (SQLException e) {
            ABRLogger.getInstance(ABRViewBotJobPane.class).severe("loadBlockAll  \nError: " + e.getMessage());
        }
    }

    public List<InstructionDTO> getInstructionsByBlockId(int botJobId, int blockId) {
        // List to store the fetched instructions
        List<InstructionDTO> instructions = new ArrayList<>();

        // Build the SQL query statement
        String querySQL = "SELECT * FROM block_loop_instruction WHERE block_id = " + blockId
                + " order by instruction_order_number ASC";

        // Execute the query and process the result set
        try (Statement stmt = ABRSharedResources.getInstance().getConnection().createStatement();
                ResultSet rs = stmt.executeQuery(querySQL)) {

            while (rs.next()) {
                // Assuming you have an Instruction class, populate it with data from the ResultSet
                InstructionDTO instruction = new InstructionDTO();
                instruction.setInstructionId(rs.getInt("id"));
                instruction.setInstructionName(rs.getString("name"));
                instruction.setInstructionOrderNumber(rs.getInt("instruction_order_number"));
                instruction.setBlockId(rs.getInt("block_id"));
                instruction.setBlockOrderNumber(instruction.getBlockOrderNumber());
                instruction.setBotJobId(botJobId);

                instruction.setActions(rs.getString("actions"));
                instruction.setPath(rs.getString("path"));
                instruction.setDescription(rs.getString("description"));
                instruction.setOptional(rs.getInt("optional"));
                instruction.setActionCustomMaxWaitSec(rs.getInt("action_custom_max_wait_sec"));
                instruction.setOnHoldSeconds(rs.getInt("on_hold_seconds"));
                instruction.setEncrypted(rs.getInt("encrypted"));
                instruction.setExportToABR(rs.getInt("export_to_abr"));

                // Add the instruction to the list
                instructions.add(instruction);
            }

            ABRLogger.getInstance(ABRWebDriver.class)
                    .info(String.format("Fetched %d instructions for Block ID %d:", instructions.size(), blockId));

        } catch (SQLException e) {
            ABRLogger.getInstance(ABRWebDriver.class)
                    .severe(String.format(
                            "Error fetching instructions for Block ID %d. Error: %s: ", blockId, e.getMessage()));
        }

        return instructions;
    }

    public boolean reorderInstructions(List<InstructionDTO> rowList) {
        int orderNumber = 1;

        // Iterate through the list and update the instructionOrderNumber
        for (InstructionDTO instruction : rowList) {
            instruction.setInstructionOrderNumber(orderNumber);
            orderNumber++; // Increment the order number for the next instruction
        }

        // Build the SQL update statement
        try (Statement stmt = ABRSharedResources.getInstance().getConnection().createStatement()) {
            // Loop through each instruction in the rowList
            for (InstructionDTO instruction : rowList) {
                // Increment the instructionOrderNumber by 1 for each instruction
                String updateSQL = "UPDATE block_loop_instruction SET  "
                        + " instruction_order_number = " + instruction.getInstructionOrderNumber()
                        + " WHERE id = " + instruction.getInstructionId()
                        + " AND block_id = " + instruction.getBlockId();

                int rowsAffected = stmt.executeUpdate(updateSQL);
                if (rowsAffected > 0) {
                    ABRLogger.getInstance(ABRWebDriver.class)
                            .warning(String.format(
                                    "preInsertStep - InstructionId: %s in BlockId: %s now has order number: %d",
                                    instruction.getInstructionId(),
                                    instruction.getBlockId(),
                                    instruction.getInstructionOrderNumber() + 1));
                } else {
                    ABRLogger.getInstance(ABRWebDriver.class)
                            .warning(String.format(
                                    "preInsertStep - No matching record found for BlockId: %d and InstructionId: %d",
                                    instruction.getBlockId(), instruction.getInstructionId()));
                }
            }

            return true;
        } catch (SQLException e) {
            ABRLogger.getInstance(ABRWebDriver.class)
                    .severe(String.format("Error updating instruction order numbers.\nError: %s", e.getMessage()));
        }
        return false;
    }

    private void createMockSavedBlocksDTOs() {
        // Create mock data for SavedBlocksDTO
        ObservableList<SavedBlocksDTO> savedBlocksDTOs = FXCollections.observableArrayList();

        // Create mock SavedBlockLoopInstructionDTO entries
        SavedBlockLoopInstructionDTO instruction1 = new SavedBlockLoopInstructionDTO();
        instruction1.setInstructionOrderNumber(1);
        instruction1.setActions("Action 1");
        instruction1.setName("Instruction 1");
        instruction1.setPath("/path/to/instruction1");
        instruction1.setDescription("Description for Instruction 1");
        instruction1.setOptional(false);
        instruction1.setDefaultValue("default1");
        instruction1.setActionCustomMaxWaitSec(10);
        instruction1.setOnHoldSeconds(5);
        instruction1.setEncrypted(false);
        instruction1.setExportToABR(true);

        SavedBlockLoopInstructionDTO instruction2 = new SavedBlockLoopInstructionDTO();
        instruction2.setInstructionOrderNumber(2);
        instruction2.setActions("Action 2");
        instruction2.setName("Instruction 2");
        instruction2.setPath("/path/to/instruction2");
        instruction2.setDescription("Description for Instruction 2");
        instruction2.setOptional(false);
        instruction2.setDefaultValue("default2");
        instruction2.setActionCustomMaxWaitSec(20);
        instruction2.setOnHoldSeconds(10);
        instruction2.setEncrypted(false);
        instruction2.setExportToABR(true);

        // Assign mock instructions to mock blocks
        SavedBlocksDTO block1 = new SavedBlocksDTO();
        block1.setName("Block One");
        block1.setDescription("Description for Block One");
        block1.setTypeId(1);
        block1.setSavedBlockLoopInstructions(new ArrayList<>(List.of(instruction1))); // Assign instruction1 to block1

        SavedBlocksDTO block2 = new SavedBlocksDTO();
        block2.setName("Block Two");
        block2.setDescription("Description for Block Two");
        block2.setTypeId(2);
        block2.setSavedBlockLoopInstructions(new ArrayList<>(List.of(instruction2))); // Assign instruction2 to block2

        SavedBlocksDTO block3 = new SavedBlocksDTO();
        block3.setName("Another Block");
        block3.setDescription("Description for Another Block");
        block3.setTypeId(3);
        block3.setSavedBlockLoopInstructions(new ArrayList<>()); // No instructions for this block

        SavedBlocksDTO block4 = new SavedBlocksDTO();
        block4.setName("Sample Block");
        block4.setDescription("Description for Sample Block");
        block4.setTypeId(4);
        block4.setSavedBlockLoopInstructions(new ArrayList<>()); // No instructions for this block

        // Add mock blocks to the ObservableList
        savedBlocksDTOs.addAll(block1, block2, block3, block4);

        this.componentList.setItems(savedBlocksDTOs);
    }
}
