// Source code is unavailable, and was generated by the Fernflower decompiler.
package com.allinweb.ch.component.pane;

import com.allinweb.ch.component.listCell.ABRCellFactory;
import com.allinweb.ch.component.listCell.BlockListCell;
import com.allinweb.ch.component.listCell.ComponentListCell;
import com.allinweb.ch.component.pane.base.ABRPane;
import com.allinweb.ch.component.scene.*;
import com.allinweb.ch.control.ABRComponentBuilder;
import com.allinweb.ch.core.ABRSharedResources;
import com.allinweb.ch.persistence.BlockDTO;
import com.allinweb.ch.persistence.BotJobDTO;
import com.allinweb.ch.persistence.SavedBlocksDTO;
import com.allinweb.ch.util.ABRConstants;
import com.allinweb.ch.util.ABRPropertyEnum;
import com.allinweb.ch.util.ABRPropertyManager;
import com.allinweb.ch.util.ExcelWriter;
import com.google.common.base.Strings;
import java.io.File;
import java.io.IOException;
import java.util.*;
import java.util.Iterator;
import java.util.List;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.collections.ObservableList;
import javafx.concurrent.Task;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.*;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.FontPosture;
import javafx.scene.text.FontWeight;
import javafx.stage.Stage;

public class ABRViewBotJobPane extends ABRPane {
    private static final ABRComponentBuilder builder = new ABRComponentBuilder();
    private BotJobDTO botJob;
    private SimpleBooleanProperty isEditingBotJob = new SimpleBooleanProperty(false);
    Button refreshButton;
    Button openScannerButton;
    Button editBotJobButton;
    Button launchBotJobButton;
    Button saveBotJobButton;
    CheckBox checkBoxUpdatePriority;
    Button saveAsBotJobButton;
    Button printBotJobButton;
    Button copyBotJobButton;
    Button openExcelFileButton;
    Button generateExcelButton;
    Button openExcelFilterPanelButton;
    Button closeBotJobButton;
    ButtonBar buttonPane;
    Label botJobNameLabel;
    Label botJobDescriptionLabel;
    TextField botJobName;
    TextField botJobDescription;
    ListView<BlockDTO> uiBlockList;
    VBox botJobContainer;
    Button componentButton;
    VBox componentContainer;
    ListView<SavedBlocksDTO> componentList;

    public ABRViewBotJobPane(BotJobDTO botJob) {
        this.botJob = botJob;
    }

    public void initUIComponents() {
        this.refreshButton = builder.buildButton(
                "Refresh", ABRConstants.SPACE_ZERO, "/refresh.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.openScannerButton = builder.buildButton(
                "Scan", ABRConstants.SPACE_ZERO, "/open_browser.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.editBotJobButton = builder.buildButton(
                "Edit", ABRConstants.SPACE_ZERO, "/edit.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.launchBotJobButton = builder.buildButton(
                "Launch", ABRConstants.SPACE_ZERO, "/play.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.saveBotJobButton = builder.buildButton(
                "Save", ABRConstants.SPACE_ZERO, "/save.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.checkBoxUpdatePriority = new CheckBox("Upd\nPriority");
        checkBoxUpdatePriority.setWrapText(true);
        checkBoxUpdatePriority.setPrefWidth(80); // Adjust width as needed

        this.saveAsBotJobButton = builder.buildButton(
                "Save As", ABRConstants.SPACE_ZERO, "/save.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.printBotJobButton = builder.buildButton(
                "Print", ABRConstants.SPACE_ZERO, "/print.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.copyBotJobButton = builder.buildButton(
                "Copy", ABRConstants.SPACE_ZERO, "/copy.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.openExcelFileButton = builder.buildButton(
                "Excel File", ABRConstants.SPACE_ZERO, "/excel.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.generateExcelButton = builder.buildButton(
                "Generate", ABRConstants.SPACE_ZERO, "/excel.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.openExcelFilterPanelButton = builder.buildButton(
                "Filter", ABRConstants.SPACE_ZERO, "/list.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.closeBotJobButton = builder.buildButton(
                "Close", ABRConstants.SPACE_ZERO, "/cross.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.buttonPane = new ButtonBar();
        this.buttonPane
                .getButtons()
                .addAll(
                        refreshButton,
                        this.openScannerButton,
                        this.editBotJobButton,
                        this.launchBotJobButton,
                        this.saveBotJobButton,
                        this.saveAsBotJobButton,
                        this.openExcelFileButton,
                        this.generateExcelButton,
                        this.openExcelFilterPanelButton,
                        this.closeBotJobButton);

        // Create a GridPane
        GridPane gridPane = new GridPane();

        // Add the ButtonBar to the GridPane and align it at the center
        gridPane.add(buttonPane, 0, 0);
        GridPane.setHalignment(buttonPane, javafx.geometry.HPos.CENTER); // Align center

        // Add checkBoxUpdatePriority below saveBotJobButton
        gridPane.add(checkBoxUpdatePriority, 0, 1);
        GridPane.setHalignment(checkBoxUpdatePriority, javafx.geometry.HPos.CENTER); // Align center

        this.botJobNameLabel = new Label(this.botJob.getName());
        this.botJobName = new TextField(this.botJob.getName());
        this.initComponentUI();
        StackPane botJobNameGroup =
                new StackPane(new Node[] {this.botJobNameLabel, this.botJobName, this.componentButton});
        StackPane.setAlignment(this.componentButton, Pos.CENTER_RIGHT);
        StackPane.setMargin(this.componentButton, new Insets(5.0D, 0.0D, 0.0D, 0.0D));
        this.botJobDescriptionLabel = new Label(this.botJob.getDescription());
        this.botJobDescription = new TextField(this.botJob.getDescription());
        StackPane botJobDescriptionGroup =
                new StackPane(new Node[] {this.botJobDescriptionLabel, this.botJobDescription});
        ObservableList<BlockDTO> blockDTOObservableList = ABRSharedResources.getInstance()
                .getEntityList(BlockDTO.class, blockDTO -> blockDTO.getBotJob().getId() == botJob.getId());
        this.uiBlockList = new ListView<>(blockDTOObservableList);

        uiBlockList.setCellFactory(new ABRCellFactory<>(BlockListCell.class)::call);
        this.uiBlockList.setMaxHeight(Double.MAX_VALUE);
        this.uiBlockList.setMaxWidth(Double.MAX_VALUE);
        this.uiBlockList.setPrefHeight(900.0D);
        this.uiBlockList.setBorder((Border) null);
        HBox compBox = new HBox(new Node[] {this.uiBlockList, this.componentContainer});
        HBox.setHgrow(this.uiBlockList, Priority.ALWAYS);
        HBox.setHgrow(this.componentContainer, Priority.ALWAYS);
        this.botJobContainer = new VBox(new Node[] {gridPane, botJobNameGroup, botJobDescriptionGroup, compBox});
        AnchorPane.setTopAnchor(this.botJobContainer, ABRConstants.SPACE_M);
        AnchorPane.setBottomAnchor(this.botJobContainer, ABRConstants.SPACE_M);
        AnchorPane.setLeftAnchor(this.botJobContainer, ABRConstants.SPACE_M);
        AnchorPane.setRightAnchor(this.botJobContainer, ABRConstants.SPACE_M);
    }

    public void initUIBehaviour() {
        refreshButton.setOnMouseClicked(e -> {
            Stage stage = (Stage) ((Button) e.getSource()).getScene().getWindow();
            stage.close();
            new ABRViewBotJobScene(botJob.getId()).show();
        });
        saveAsBotJobButton.setOnMouseClicked(e -> new ABRSaveBotJobAsScene(botJob.getId()).show());
        this.botJobNameLabel.visibleProperty().bind(this.isEditingBotJob.not());
        this.botJobDescriptionLabel.visibleProperty().bind(this.isEditingBotJob.not());
        this.botJobName.visibleProperty().bind(this.isEditingBotJob);
        this.botJobDescription.visibleProperty().bind(this.isEditingBotJob);
        this.editBotJobButton.setOnMouseClicked((e) -> {
            this.isEditingBotJob.set(this.isEditingBotJob.not().getValue());
        });
        this.saveBotJobButton.setOnMouseClicked((e) -> {
            this.isEditingBotJob.set(false);
            this.botJobNameLabel.setText(this.botJobName.getText());
            this.botJobDescriptionLabel.setText(this.botJobDescription.getText());
            this.botJob.setName(this.botJobNameLabel.getText());
            this.botJob.setDescription(this.botJobDescriptionLabel.getText());
            if (checkBoxUpdatePriority.isSelected()
                    && !Strings.isNullOrEmpty(this.botJob.getHomeBanking().getPriority())) {
                this.botJob.setPriority(this.botJob.getHomeBanking().getPriority());
            }
            ABRSharedResources.getInstance().updateEntity(this.botJob, BotJobDTO.class);
        });
        this.openScannerButton.setOnMouseClicked((e) -> {
            (new ABRScannedElementScene(
                            this.botJob.getHomeBanking().getPriority(),
                            this.botJob.getId(),
                            this.botJob.getBlocks() != null
                                    ? this.botJob.getBlocks().get(0).getId()
                                    : 0))
                    .show();
        });
        this.generateExcelButton.setOnMouseClicked((e) -> {
            BotJobDTO botJobUpdated =
                    (BotJobDTO) ABRSharedResources.getInstance().getEntityById(BotJobDTO.class, this.botJob.getId());
            Task<Void> excel = new Task<>() {
                @Override
                protected Void call() throws Exception {
                    new ExcelWriter().generateExcelFiles(botJobUpdated);
                    return null;
                }
            };
            if (ExcelWriter.isFileExits(this.botJob)) {
                System.out.println("warning");
                new ABRAlertScene(
                        AlertType.INFORMATION,
                        "Warning: Excel File already exist",
                        "Excel File already exists: overwrite it?",
                        () -> {
                            new Thread(excel).start();
                        },
                        new ButtonType[] {ButtonType.OK});
            } else {

                new ABRAlertScene(
                        AlertType.INFORMATION,
                        "Excel file generated",
                        "The excel file has been generated successfully",
                        new ButtonType[] {ButtonType.OK});
                new Thread(excel).start();
            }
        });
        this.openExcelFilterPanelButton.setOnMouseClicked((e) -> {
            (new ABRExportFilterScene(this.botJob)).show();
        });
        this.launchBotJobButton.setOnMouseClicked((e) -> {
            ABRPropertyManager var10000 = ABRPropertyManager.getInstance();
            String enginePath = var10000.getProperty(ABRPropertyEnum.PATH_ENGINE) + "\\ABR_Web_Engine.jar";
            String var16 = ABRPropertyManager.getInstance().getProperty(ABRPropertyEnum.FOLDER_PATH_EXCEL);
            //            String excelPath = var16 + "\\" + this.botJob.getName() + ".xlsx";
            String excelPath = var16 + "\\"; // + this.botJob.getName() + ".xlsx";
            if (!(new File(excelPath)).exists()) {
                new ABRAlertScene(
                        AlertType.WARNING,
                        "Missing file excel",
                        "Please generate and compile the data of the file excel first before launching the bot job",
                        new ButtonType[] {ButtonType.OK});
            }

            String[] command = new String[] {
                "cmd.exe",
                "/c",
                ".\\java\\bin\\java.exe",
                "-jar",
                "\"" + enginePath + "\"",
                "execute/j",
                String.valueOf(this.botJob.getHomeBanking().getId()),
                String.valueOf(this.botJob.getId()),
                "\"" + excelPath + "\"",
                "-c",
                ABRPropertyManager.getConfigurationFileName()
            };
            ProcessBuilder processBuilder = new ProcessBuilder(command);
            processBuilder.directory(new File(ABRConstants.CURRENT_PATH));
            String logPath = ABRPropertyManager.getInstance().getProperty(ABRPropertyEnum.FOLDER_PATH_LOG);
            File output = new File(logPath + "\\engine_debug_log_output.log");
            File error = new File(logPath + "\\engine_debug_log_error.log");
            File input = new File(logPath + "\\engine_debug_log_input.log");
            List<File> files = new ArrayList<File>();
            files.add(output);
            files.add(error);
            files.add(input);

            Iterator<File> var11 = files.iterator();

            while (var11.hasNext()) {
                File file = (File) var11.next();
                if (!file.exists()) {
                    try {
                        file.createNewFile();
                    } catch (IOException var15) {
                        var15.printStackTrace();
                    }
                }
            }

            processBuilder.redirectOutput(output);
            processBuilder.redirectError(error);
            processBuilder.redirectInput(input);

            try {
                processBuilder.start();
            } catch (IOException var14) {
                var14.printStackTrace();
            }
        });
        this.closeBotJobButton.setOnMouseClicked((e) -> {
            Stage stage = (Stage) ((Button) e.getSource()).getScene().getWindow();
            stage.close();
        });
        this.openExcelFileButton.setOnMouseClicked((e) -> {
            try {
                String excelFilePath = ABRPropertyManager.getInstance().getProperty(ABRPropertyEnum.FOLDER_PATH_EXCEL);
                excelFilePath = excelFilePath + "\\" + this.botJob.getName() + ".xlsx";
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + excelFilePath);
            } catch (IOException var3) {
                var3.printStackTrace();
            }
        });
        this.componentButton.setOnMouseClicked((e) -> {
            if (this.componentContainer.isVisible()) {
                this.componentContainer.setVisible(false);
                this.componentContainer.setManaged(false);
            } else {
                this.componentContainer.setVisible(true);
                this.componentContainer.setManaged(true);
            }
        });
    }

    public Pane getPaneReference() {
        AnchorPane acAnchorPane = new AnchorPane(new Node[] {this.botJobContainer});
        acAnchorPane.setUserData(this);
        return acAnchorPane;
    }

    private void initComponentUI() {
        this.componentButton = builder.buildButton(
                "",
                ABRConstants.SPACE_L,
                "/Cubes.png",
                ABRConstants.SPACE_L + 10.0D,
                Insets.EMPTY,
                Background.fill(Color.TRANSPARENT));
        ObservableList<SavedBlocksDTO> savedBlocksDTO =
                ABRSharedResources.getInstance().getEntityList(SavedBlocksDTO.class);
        this.componentList = new ListView<SavedBlocksDTO>(savedBlocksDTO);

        componentList.setCellFactory(new ABRCellFactory<>(ComponentListCell.class)::call);
        this.componentList.setMaxHeight(Double.MAX_VALUE);
        this.componentList.setPrefHeight(900.0D);
        this.componentList.setUserData(this);
        this.componentList.getUserData();
        VBox.setVgrow(componentList, Priority.ALWAYS);

        Label componentTitleLabel = new Label("Components");
        componentTitleLabel.setPadding(new Insets(5.0D));
        componentTitleLabel.setFont(
                Font.font((String) null, FontWeight.BOLD, FontPosture.REGULAR, ABRConstants.SPACE_SM + 4.0D));
        Label searchLabel = new Label("Find");
        searchLabel.setPadding(new Insets(5.0D));
        searchLabel.setFont(
                Font.font((String) null, FontWeight.BOLD, FontPosture.REGULAR, ABRConstants.SPACE_SM + 2.0D));
        TextField searchTextField = new TextField();
        searchTextField.textProperty().addListener((observable, oldValue, newValue) -> {
            ObservableList<SavedBlocksDTO> savedBlocksDTOs;
            if (!newValue.equals("")) {
                System.out.println(newValue + " Text");
                savedBlocksDTOs = ABRSharedResources.getInstance().getEntityList(SavedBlocksDTO.class, (savedBlock) -> {
                    return savedBlock.getName().toLowerCase().contains(newValue.toLowerCase());
                });
            } else {
                savedBlocksDTOs = ABRSharedResources.getInstance().getEntityList(SavedBlocksDTO.class);
            }

            this.componentList.setItems(savedBlocksDTOs);
            this.componentList.refresh();
        });

        HBox searchPaneBox = new HBox(new Node[] {searchLabel, searchTextField});
        searchPaneBox.setMaxHeight(ABRConstants.SPACE_XL);
        searchPaneBox.setSpacing(ABRConstants.SPACE_XXS);
        HBox.setHgrow(searchTextField, Priority.ALWAYS);

        this.componentContainer = new VBox(new Node[] {componentTitleLabel, searchPaneBox, componentList});
        this.componentContainer.setSpacing(ABRConstants.SPACE_XS);
        this.componentContainer.setMaxWidth(200.0D);
        this.componentContainer.setVisible(false);
        this.componentContainer.setManaged(false);
    }

    public BotJobDTO getBotJobDTO() {
        return this.botJob;
    }
}
