// Source code is unavailable, and was generated by the Fernflower decompiler.
package com.allinweb.ch.component.pane;

import com.allinweb.ch.builder.WebElementTagNameEnum;
import com.allinweb.ch.component.listCell.ABRCellFactory;
import com.allinweb.ch.component.listCell.BlockListCell;
import com.allinweb.ch.component.listCell.ComponentListCell;
import com.allinweb.ch.component.pane.base.ABRPane;
import com.allinweb.ch.component.scene.*;
import com.allinweb.ch.control.ABRComponentBuilder;
import com.allinweb.ch.core.ABRSharedResources;
import com.allinweb.ch.driver.ABRWebDriver;
import com.allinweb.ch.persistence.BlockDTO;
import com.allinweb.ch.persistence.BlockLoopInstructionDTO;
import com.allinweb.ch.persistence.BotJobDTO;
import com.allinweb.ch.persistence.SavedBlocksDTO;
import com.allinweb.ch.persistence.VariableUserDTO;
import com.allinweb.ch.util.ABRConstants;
import com.allinweb.ch.util.ABRLogger;
import com.allinweb.ch.util.ABRPropertyEnum;
import com.allinweb.ch.util.ABRPropertyManager;
import com.allinweb.ch.util.ComboBoxVars;
import com.allinweb.ch.util.ExcelWriter;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javafx.animation.KeyFrame;
import javafx.animation.Timeline;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.concurrent.Task;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.*;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.control.TextField;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.FontPosture;
import javafx.scene.text.FontWeight;
import javafx.stage.Modality;
import javafx.stage.Stage;

public class ABRViewBotJobPane extends ABRPane {

    private static final String CONNECTION_TYPE = "jdbc:ucanaccess://";
    private static final String CONNECTION_PARAMETERS = ";memory=false;newDatabaseVersion=V2010";

    // Postgres
    private static final boolean POSTGRES_DB = true;
    private static final String CONNECTION_POSTGRES = "jdbc:postgresql://";
    private static final String DB_HOST = "localhost"; // or your PostgreSQL server address
    private static final String DB_PORT = "5432"; // default PostgreSQL port
    private static final String DB_NAME = "abr_web"; // your database name
    private static final String USERNAME = "postgres"; // your database username
    private static final String PASSWORD = "martini"; // your database password

    private Connection conn = null;
    private ObservableList<VariableUserDTO> variablesList;

    private ObservableList<ComboBoxVars> webPageItems = FXCollections.observableArrayList();

    private static final ABRComponentBuilder builder = new ABRComponentBuilder();
    private BotJobDTO botJob;
    private SimpleBooleanProperty isEditingBotJob = new SimpleBooleanProperty(false);
    Button refreshButton;
    Button addWaitButton30;
    Button addWaitButton15;
    Button openScannerButton;
    Button editBotJobButton;
    Button launchBotJobButton;
    Button saveBotJobButton;
    Button saveAsBotJobButton;
    Button printBotJobButton;
    Button copyBotJobButton;
    Button openExcelFileButton;
    Button generateExcelButton;
    Button openExcelFilterPanelButton;
    Button addNewStepButton;
    Button closeBotJobButton;

    Label botJobNameLabel;
    Label botJobDescriptionLabel;
    TextField botJobName;
    TextField botJobDescription;
    ObservableList<BlockDTO> blockDTOObservableList;
    ListView<BlockDTO> uiBlockList;
    VBox botJobContainer;
    Button componentButton;
    VBox componentContainer;
    ListView<SavedBlocksDTO> componentList;

    private static final int SECONDS = 3; // Total seconds for the countdown
    private int remainingSeconds = SECONDS;
    private Timeline timeline;
    private ExecutorService executorService;
    private Alert alertToShow;

    public ABRViewBotJobPane(BotJobDTO botJob) {
        this.botJob = botJob;
        // Initialize database IF IS ACCESS TO BE USED
        variablesList = FXCollections.observableArrayList();
        if (!POSTGRES_DB) {
            initializeDatabase();
        }
        loadJobVariables();
        loadWebPageFields();
    }

    public void initUIComponents() {
        // Create a label to display the countdown
        Label countdownLabel = new Label(String.valueOf(remainingSeconds));
        countdownLabel.setStyle("-fx-font-size: 24px;");
        countdownLabel.setVisible(false);
        // Create a stack pane to hold the label
        StackPane stackPane = new StackPane(countdownLabel);
        stackPane.setPadding(new Insets(20));
        // Create a dialog for the alert
        alertToShow = new Alert(Alert.AlertType.INFORMATION);
        alertToShow.setTitle("Countdown Alert");
        alertToShow.setHeaderText("Count Down");
        alertToShow.initModality(Modality.APPLICATION_MODAL);
        // Set the content of the alert
        alertToShow.getDialogPane().setContent(stackPane);
        // Create a timeline to update the countdown
        timeline = new Timeline(new KeyFrame(javafx.util.Duration.seconds(1), event -> {
            remainingSeconds--;
            countdownLabel.setText(String.valueOf(remainingSeconds));
            if (remainingSeconds <= 0) {
                timeline.stop(); // Stop the timeline when countdown finishes
                alertToShow.close(); // Close the alert dialog
            }
        }));

        this.addWaitButton30 = builder.buildButton(
                "30s", ABRConstants.SPACE_L, ABRConstants.ICON_WAIT, ABRConstants.SPACE_M, new Insets(5));
        this.addWaitButton15 = builder.buildButton(
                "15s", ABRConstants.SPACE_L, ABRConstants.ICON_WAIT, ABRConstants.SPACE_M, new Insets(5));
        this.refreshButton = builder.buildButton(
                "Refresh", ABRConstants.SPACE_ZERO, "/refresh.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.openScannerButton = builder.buildButton(
                "Scan", ABRConstants.SPACE_ZERO, "/open_browser.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.editBotJobButton = builder.buildButton(
                "Edit", ABRConstants.SPACE_ZERO, "/edit.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.launchBotJobButton = builder.buildButton(
                "Launch", ABRConstants.SPACE_ZERO, "/play.png", ABRConstants.SPACE_M, new Insets(5.0D));
        this.saveBotJobButton = builder.buildButton(
                "Save", ABRConstants.SPACE_ZERO, ABRConstants.ICON_SAVE, ABRConstants.SPACE_M, new Insets(5.0D));

        this.saveAsBotJobButton = builder.buildButton(
                "Save As", ABRConstants.SPACE_ZERO, ABRConstants.ICON_SAVE, ABRConstants.SPACE_M, new Insets(5.0D));
        this.printBotJobButton = builder.buildButton(
                "Print", ABRConstants.SPACE_ZERO, ABRConstants.ICON_PRINT, ABRConstants.SPACE_M, new Insets(5.0D));
        this.copyBotJobButton = builder.buildButton(
                "Copy", ABRConstants.SPACE_ZERO, ABRConstants.ICON_COPY, ABRConstants.SPACE_M, new Insets(5.0D));
        this.openExcelFileButton = builder.buildButton(
                "Excel File", ABRConstants.SPACE_ZERO, ABRConstants.ICON_EXCEL, ABRConstants.SPACE_M, new Insets(5.0D));
        this.generateExcelButton = builder.buildButton(
                "Generate", ABRConstants.SPACE_ZERO, ABRConstants.ICON_EXCEL, ABRConstants.SPACE_M, new Insets(5.0D));
        this.openExcelFilterPanelButton = builder.buildButton(
                "Filter", ABRConstants.SPACE_ZERO, ABRConstants.ICON_LIST, ABRConstants.SPACE_M, new Insets(5.0D));
        this.closeBotJobButton = builder.buildButton(
                "Close", ABRConstants.SPACE_ZERO, ABRConstants.ICON_CROSS, ABRConstants.SPACE_M, new Insets(5.0D));

        this.addNewStepButton = builder.buildButton(
                "New Step", ABRConstants.SPACE_ZERO, ABRConstants.ICON_STEP, ABRConstants.SPACE_M, new Insets(5.0D));

        // Create a GridPane for the left side buttons
        GridPane leftGridPane = new GridPane();
        leftGridPane.setVgap(10); // Vertical spacing between elements
        leftGridPane.setHgap(10); // Horizontal spacing between elements

        // Define a uniform width for the buttons
        double buttonWidth = 100;

        // Add the top row of buttons
        refreshButton.setPrefWidth(buttonWidth);
        leftGridPane.add(refreshButton, 0, 0);

        openScannerButton.setPrefWidth(buttonWidth);
        leftGridPane.add(openScannerButton, 1, 0);

        addWaitButton30.setPrefWidth(buttonWidth);
        leftGridPane.add(addWaitButton30, 2, 0);

        addWaitButton15.setPrefWidth(buttonWidth);
        leftGridPane.add(addWaitButton15, 3, 0);

        editBotJobButton.setPrefWidth(buttonWidth);
        leftGridPane.add(editBotJobButton, 4, 0);

        launchBotJobButton.setPrefWidth(buttonWidth);
        leftGridPane.add(launchBotJobButton, 5, 0);

        addNewStepButton.setPrefWidth(buttonWidth);
        leftGridPane.add(addNewStepButton, 6, 0);

        // Add the bottom row of buttons
        saveBotJobButton.setPrefWidth(buttonWidth);
        leftGridPane.add(saveBotJobButton, 0, 1);

        saveAsBotJobButton.setPrefWidth(buttonWidth);
        leftGridPane.add(saveAsBotJobButton, 1, 1);

        openExcelFileButton.setPrefWidth(buttonWidth);
        leftGridPane.add(openExcelFileButton, 2, 1);

        generateExcelButton.setPrefWidth(buttonWidth);
        leftGridPane.add(generateExcelButton, 3, 1);

        openExcelFilterPanelButton.setPrefWidth(buttonWidth);
        leftGridPane.add(openExcelFilterPanelButton, 4, 1);

        closeBotJobButton.setPrefWidth(buttonWidth);
        leftGridPane.add(closeBotJobButton, 5, 1);

        // Center the buttons
        for (Node node : leftGridPane.getChildren()) {
            GridPane.setHalignment(node, javafx.geometry.HPos.CENTER);
        }

        // Other UI components
        this.botJobNameLabel = new Label(this.botJob.getName());
        this.botJobName = new TextField(this.botJob.getName());

        this.initComponentUI();

        StackPane botJobNameGroup =
                new StackPane(new Node[] {this.botJobNameLabel, this.botJobName, this.componentButton});
        StackPane.setAlignment(this.componentButton, Pos.CENTER_RIGHT);
        StackPane.setMargin(this.componentButton, new Insets(5.0D, 0.0D, 0.0D, 0.0D));
        this.botJobDescriptionLabel = new Label(this.botJob.getDescription());
        this.botJobDescription = new TextField(this.botJob.getDescription());
        StackPane botJobDescriptionGroup =
                new StackPane(new Node[] {this.botJobDescriptionLabel, this.botJobDescription});

        this.blockDTOObservableList = FXCollections.observableArrayList(ABRSharedResources.getInstance()
                .getEntityList(BlockDTO.class, blockDTO -> blockDTO.getBotJob().getId() == botJob.getId()));

        this.uiBlockList = new ListView<>(blockDTOObservableList);

        this.uiBlockList.setCellFactory(new ABRCellFactory<>(BlockListCell.class)::call);
        this.uiBlockList.setMaxHeight(Double.MAX_VALUE);
        this.uiBlockList.setMaxWidth(Double.MAX_VALUE);
        this.uiBlockList.setPrefHeight(900.0D);
        this.uiBlockList.setBorder(null);

        HBox compBox = new HBox(new Node[] {this.uiBlockList, this.componentContainer});
        HBox.setHgrow(this.uiBlockList, Priority.ALWAYS);
        HBox.setHgrow(this.componentContainer, Priority.ALWAYS);
        this.botJobContainer = new VBox(new Node[] {leftGridPane, botJobNameGroup, botJobDescriptionGroup, compBox});
        AnchorPane.setTopAnchor(this.botJobContainer, ABRConstants.SPACE_M);
        AnchorPane.setBottomAnchor(this.botJobContainer, ABRConstants.SPACE_M);
        AnchorPane.setLeftAnchor(this.botJobContainer, ABRConstants.SPACE_M);
        AnchorPane.setRightAnchor(this.botJobContainer, ABRConstants.SPACE_M);

        // Add the stylesheet to the scene
        //        mainGridPane.getStylesheets().add(css);
    }

    public void initUIBehaviour() {
        addWaitButton30.setOnAction(e -> addWaitTask(30));
        addWaitButton15.setOnAction(e -> addWaitTask(15));
        refreshButton.setOnMouseClicked(e -> {
            Stage stage = (Stage) ((Button) e.getSource()).getScene().getWindow();
            stage.close();
            new ABRViewBotJobScene(botJob.getId()).show();
        });
        saveAsBotJobButton.setOnMouseClicked(e -> new ABRSaveBotJobAsScene(botJob.getId()).show());
        this.botJobNameLabel.visibleProperty().bind(this.isEditingBotJob.not());
        this.botJobDescriptionLabel.visibleProperty().bind(this.isEditingBotJob.not());
        this.botJobName.visibleProperty().bind(this.isEditingBotJob);
        this.botJobDescription.visibleProperty().bind(this.isEditingBotJob);
        this.editBotJobButton.setOnMouseClicked((e) -> {
            this.isEditingBotJob.set(this.isEditingBotJob.not().getValue());
        });
        this.saveBotJobButton.setOnMouseClicked((e) -> {
            this.isEditingBotJob.set(false);
            this.botJobNameLabel.setText(this.botJobName.getText());
            this.botJobDescriptionLabel.setText(this.botJobDescription.getText());
            this.botJob.setName(this.botJobNameLabel.getText());
            this.botJob.setDescription(this.botJobDescriptionLabel.getText());
            ABRSharedResources.getInstance().updateEntity(this.botJob, BotJobDTO.class);
        });
        this.openScannerButton.setOnMouseClicked((e) -> {
            ABRLogger.getInstance(ABRWebDriver.class).fine("Calling openScannerButton");

            try {
                (new ABRScannedElementScene(
                                this.botJob.getHomeBanking().getPriority(),
                                this.botJob.getId(),
                                this.botJob.getBlocks() != null
                                        ? this.botJob.getBlocks().get(0).getId()
                                        : 0))
                        .show();
            } catch (Exception ex) {
                //                ABRLogger.getInstance(ABRWebDriver.class).severe("ERROR Calling openScannerButton\n" +
                // ex.getMessage());
                //                JOptionPane.showMessageDialog(
                //                        null,
                //                        "An error has occurred Calling SCAN: \nError:" + ex.getMessage() + " Cause: "
                // + ex.getCause(),
                //                        "Error calling in SCAN",
                //                        JOptionPane.ERROR_MESSAGE);
            }
        });

        this.generateExcelButton.setOnMouseClicked((e) -> {
            BotJobDTO botJobUpdated =
                    (BotJobDTO) ABRSharedResources.getInstance().getEntityById(BotJobDTO.class, this.botJob.getId());
            Task<Void> excel = new Task<>() {
                @Override
                protected Void call() throws Exception {
                    new ExcelWriter().generateExcelFiles(botJobUpdated);
                    return null;
                }
            };
            if (ExcelWriter.isFileExits(this.botJob)) {
                System.out.println("warning");
                new ABRAlertScene(
                        AlertType.INFORMATION,
                        "Warning: Excel File already exist",
                        "Excel File already exists: overwrite it?",
                        () -> {
                            new Thread(excel).start();
                        },
                        new ButtonType[] {ButtonType.OK});
            } else {

                new ABRAlertScene(
                        AlertType.INFORMATION,
                        "Excel file generated",
                        "The excel file has been generated successfully",
                        new ButtonType[] {ButtonType.OK});
                new Thread(excel).start();
            }
        });
        this.openExcelFilterPanelButton.setOnMouseClicked((e) -> {
            (new ABRExportFilterScene(this.botJob)).show();
        });
        this.launchBotJobButton.setOnMouseClicked((e) -> {
            ABRPropertyManager managerProps = ABRPropertyManager.getInstance();
            String enginePath = managerProps.getProperty(ABRPropertyEnum.PATH_ENGINE) + "\\ABR_Web_Engine.jar";
            String excelPath = ABRPropertyManager.getInstance().getProperty(ABRPropertyEnum.FOLDER_PATH_EXCEL);
            excelPath = excelPath + "\\" + this.botJob.getName() + ".xlsx";
            if (!(new File(excelPath)).exists()) {
                new ABRAlertScene(
                        AlertType.WARNING,
                        "Missing file excel",
                        "Please generate and compile the data of the file excel first before launching the bot job",
                        new ButtonType[] {ButtonType.OK});
            }

            String[] command = new String[] {
                "cmd.exe",
                "/c",
                ".\\java\\bin\\java.exe",
                "-jar",
                "\"" + enginePath + "\"",
                "execute/j",
                String.valueOf(this.botJob.getHomeBanking().getId()),
                String.valueOf(this.botJob.getId()),
                "\"" + excelPath + "\"",
                "-c",
                ABRPropertyManager.getConfigurationFileName()
            };
            ProcessBuilder processBuilder = new ProcessBuilder(command);
            processBuilder.directory(new File(ABRConstants.CURRENT_PATH));
            String logPath = ABRPropertyManager.getInstance().getProperty(ABRPropertyEnum.FOLDER_PATH_LOG);
            File output = new File(logPath + "\\engine_debug_log_output.log");
            File error = new File(logPath + "\\engine_debug_log_error.log");
            File input = new File(logPath + "\\engine_debug_log_input.log");
            List<File> files = new ArrayList<File>();
            files.add(output);
            files.add(error);
            files.add(input);

            Iterator<File> var11 = files.iterator();

            while (var11.hasNext()) {
                File file = (File) var11.next();
                if (!file.exists()) {
                    try {
                        file.createNewFile();
                    } catch (IOException var15) {
                        var15.printStackTrace();
                    }
                }
            }

            processBuilder.redirectOutput(output);
            processBuilder.redirectError(error);
            processBuilder.redirectInput(input);

            try {
                processBuilder.start();
            } catch (IOException var14) {
                var14.printStackTrace();
            }
        });
        this.closeBotJobButton.setOnMouseClicked((e) -> {
            Stage stage = (Stage) ((Button) e.getSource()).getScene().getWindow();
            stage.close();
        });
        this.addNewStepButton.setOnMouseClicked((e) -> {
            loadWebPageFields();
            ABRNewCommandScene newCommandScene = new ABRNewCommandScene(this.botJob.getId(), webPageItems);
            newCommandScene.showModal();
        });

        this.openExcelFileButton.setOnMouseClicked((e) -> {
            try {
                String excelFilePath = ABRPropertyManager.getInstance().getProperty(ABRPropertyEnum.FOLDER_PATH_EXCEL);
                excelFilePath = excelFilePath + "\\" + this.botJob.getName() + ".xlsx";
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + excelFilePath);
            } catch (IOException var3) {
                var3.printStackTrace();
            }
        });
        this.componentButton.setOnMouseClicked((e) -> {
            if (this.componentContainer.isVisible()) {
                this.componentContainer.setVisible(false);
                this.componentContainer.setManaged(false);
            } else {
                this.componentContainer.setVisible(true);
                this.componentContainer.setManaged(true);
            }
        });
    }

    private void showAlert(String title, String content) {
        executorService = Executors.newSingleThreadExecutor();
        alertToShow.setAlertType(AlertType.ERROR);
        alertToShow.setTitle("Error");
        alertToShow.setHeaderText(title);
        alertToShow.setContentText(content);

        executorService.execute(() -> {
            timeline.setCycleCount(SECONDS); // Run for SECONDS seconds
            timeline.play(); // Start the timeline

            // Show the alert on the JavaFX Application Thread
            javafx.application.Platform.runLater(() -> alertToShow.showAndWait());
        });

        if (executorService != null) {
            remainingSeconds = SECONDS;
            executorService.shutdown();
        }
    }

    public Pane getPaneReference() {
        AnchorPane acAnchorPane = new AnchorPane(new Node[] {this.botJobContainer});
        acAnchorPane.setUserData(this);
        return acAnchorPane;
    }

    private void initComponentUI() {
        this.componentButton = builder.buildButton(
                "",
                ABRConstants.SPACE_L,
                "/Cubes.png",
                ABRConstants.SPACE_L + 10.0D,
                Insets.EMPTY,
                Background.fill(Color.TRANSPARENT));
        ObservableList<SavedBlocksDTO> savedBlocksDTO =
                ABRSharedResources.getInstance().getEntityList(SavedBlocksDTO.class);
        this.componentList = new ListView<SavedBlocksDTO>(savedBlocksDTO);

        componentList.setCellFactory(new ABRCellFactory<>(ComponentListCell.class)::call);
        this.componentList.setMaxHeight(Double.MAX_VALUE);
        this.componentList.setPrefHeight(900.0D);
        this.componentList.setUserData(this);
        this.componentList.getUserData();
        VBox.setVgrow(componentList, Priority.ALWAYS);

        Label componentTitleLabel = new Label("Components");
        componentTitleLabel.setPadding(new Insets(5.0D));
        componentTitleLabel.setFont(
                Font.font((String) null, FontWeight.BOLD, FontPosture.REGULAR, ABRConstants.SPACE_SM + 4.0D));
        Label searchLabel = new Label("Find");
        searchLabel.setPadding(new Insets(5.0D));
        searchLabel.setFont(
                Font.font((String) null, FontWeight.BOLD, FontPosture.REGULAR, ABRConstants.SPACE_SM + 2.0D));
        TextField searchTextField = new TextField();
        searchTextField.textProperty().addListener((observable, oldValue, newValue) -> {
            ObservableList<SavedBlocksDTO> savedBlocksDTOs;
            if (!newValue.equals("")) {
                System.out.println(newValue + " Text");
                savedBlocksDTOs = ABRSharedResources.getInstance().getEntityList(SavedBlocksDTO.class, (savedBlock) -> {
                    return savedBlock.getName().toLowerCase().contains(newValue.toLowerCase());
                });
            } else {
                savedBlocksDTOs = ABRSharedResources.getInstance().getEntityList(SavedBlocksDTO.class);
            }

            this.componentList.setItems(savedBlocksDTOs);
            this.componentList.refresh();
        });

        HBox searchPaneBox = new HBox(new Node[] {searchLabel, searchTextField});
        searchPaneBox.setMaxHeight(ABRConstants.SPACE_XL);
        searchPaneBox.setSpacing(ABRConstants.SPACE_XXS);
        HBox.setHgrow(searchTextField, Priority.ALWAYS);

        this.componentContainer = new VBox(new Node[] {componentTitleLabel, searchPaneBox, componentList});
        this.componentContainer.setSpacing(ABRConstants.SPACE_XS);
        this.componentContainer.setMaxWidth(200.0D);
        this.componentContainer.setVisible(false);
        this.componentContainer.setManaged(false);
    }

    public BotJobDTO getBotJobDTO() {
        return this.botJob;
    }

    private void addWaitTask(Integer secondsToWait) {
        Alert alert = new Alert(
                Alert.AlertType.CONFIRMATION,
                "Are you sure you want to add a wait of " + secondsToWait + " seconds to the botjob?",
                ButtonType.YES,
                ButtonType.NO);
        Optional<ButtonType> result = alert.showAndWait();
        if (result.isPresent() && result.get() == ButtonType.YES) {
            Task<Void> waitTask = new Task<>() {
                @Override
                protected Void call() throws Exception {
                    List<BlockLoopInstructionDTO> instructionList =
                            botJob.getBlocks().get(0).getBlockLoopInstructions();
                    BlockLoopInstructionDTO waitInstruction = new BlockLoopInstructionDTO();
                    waitInstruction.setName("Wait " + secondsToWait + "second(s)");
                    waitInstruction.setDescription("Waiting action");
                    waitInstruction.setEncrypted(false);
                    waitInstruction.setInstructionOrderNumber(instructionList.size());
                    waitInstruction.setOptional(false);
                    waitInstruction.setActions(ABRConstants.HOLD);
                    waitInstruction.setOnHoldSeconds(secondsToWait);
                    waitInstruction.setBlock(botJob.getBlocks().get(0));
                    waitInstruction.setExportToABR(false);
                    ABRSharedResources.getInstance()
                            .addEntity(
                                    waitInstruction,
                                    BlockLoopInstructionDTO.class,
                                    () -> new ABRAlertScene(
                                            Alert.AlertType.INFORMATION,
                                            "Instruction Added",
                                            "Instruction Wait " + secondsToWait
                                                    + " second(s) has been added successfully",
                                            ButtonType.OK));
                    return null;
                }
            };
            new Thread(waitTask).start();
        }
    }

    private void addInstruction(String name, String operation, Integer varId) {
        Alert alert = new Alert(
                Alert.AlertType.CONFIRMATION,
                "Are you sure you want to add a " + name + " to the botjob?",
                ButtonType.YES,
                ButtonType.NO);
        Optional<ButtonType> result = alert.showAndWait();
        if (result.isPresent() && result.get() == ButtonType.YES) {
            Task<Void> waitTask = new Task<>() {
                @Override
                protected Void call() throws Exception {
                    List<BlockLoopInstructionDTO> instructionList =
                            botJob.getBlocks().get(0).getBlockLoopInstructions();
                    BlockLoopInstructionDTO instruction = new BlockLoopInstructionDTO();
                    instruction.setName(name);
                    instruction.setOperation(operation);
                    instruction.setVariableId(varId);
                    instruction.setEncrypted(false);
                    instruction.setInstructionOrderNumber(instructionList.size());
                    instruction.setOptional(false);
                    if (name.equalsIgnoreCase("setValue")) {
                        instruction.setActions(ABRConstants.SET_VALUE);
                    } else if (name.equalsIgnoreCase("getValue")) {
                        instruction.setActions(ABRConstants.GET_VALUE);
                    } else if (name.equalsIgnoreCase("check")) {
                        instruction.setActions(ABRConstants.CHECK_VALUE);
                    }
                    instruction.setOnHoldSeconds(1);
                    instruction.setBlock(botJob.getBlocks().get(0));
                    instruction.setExportToABR(false);
                    ABRSharedResources.getInstance()
                            .addEntity(
                                    instruction,
                                    BlockLoopInstructionDTO.class,
                                    () -> new ABRAlertScene(
                                            Alert.AlertType.INFORMATION,
                                            "Instruction Added",
                                            "Instruction " + instruction.getName() + " has been added successfully",
                                            ButtonType.OK));
                    return null;
                }
            };
            new Thread(waitTask).start();
        }
    }

    private void initializeDatabase() {

        String dbPath = ABRPropertyManager.getInstance().getProperty(ABRPropertyEnum.FOLDER_PATH_DB);
        String dbUrl = CONNECTION_TYPE + dbPath + ABRConstants.FILE_NAME_DB + CONNECTION_PARAMETERS;

        File dbFile = new File(dbPath + ABRConstants.FILE_NAME_DB);
        if (!dbFile.exists()) {
            try (Connection conn = DriverManager.getConnection(dbUrl)) {
                try (Statement stmt = conn.createStatement()) {
                    String createTableSQL = "CREATE TABLE home_banking (" + "ID AUTOINCREMENT PRIMARY KEY, "
                            + "name TEXT, password TEXT, url TEXT, username TEXT, priority TEXT)";
                    stmt.executeUpdate(createTableSQL);
                }
                System.out.println(String.format("Database %s has bee created!", dbFile.getName()));
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } else {
            System.out.println(String.format("Database %s Already exist!", dbFile.getName()));
        }
    }

    private Connection getConnection() {
        if (!POSTGRES_DB) {
            if (conn == null) {
                String dbPath = ABRPropertyManager.getInstance().getProperty(ABRPropertyEnum.FOLDER_PATH_DB);
                String dbUrl = CONNECTION_TYPE + dbPath + ABRConstants.FILE_NAME_DB + CONNECTION_PARAMETERS;
                try {
                    conn = DriverManager.getConnection(dbUrl);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            return conn;
        } else {

            if (conn == null) {
                String dbUrl = CONNECTION_POSTGRES + DB_HOST + ":" + DB_PORT + "/" + DB_NAME;
                try {
                    conn = DriverManager.getConnection(dbUrl, USERNAME, PASSWORD);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            return conn;
        }
    }

    private void loadJobVariables() {
        variablesList.clear();
        String selectSQL = " SELECT vars.id, vars.type, vars.name, vars.value, COUNT(blk.variable_id) UsedVars "
                + " FROM variable vars "
                + " left join block_loop_instruction blk on blk.variable_id = vars.id "
                + " where bot_job_id = " + this.botJob.getId()
                //                                + " and  block_loop_instruction_id = " + instructionId
                + " group by vars.id, vars.type, vars.Name, vars.value ";
        try (Statement stmt = getConnection().createStatement();
                ResultSet rs = stmt.executeQuery(selectSQL)) {
            while (rs.next()) {
                String id = rs.getString("ID");
                String type = rs.getString("type");
                String name = rs.getString("name");
                String value = rs.getString("value");
                String usedVars = rs.getString("UsedVars");
                variablesList.add(new VariableUserDTO(id, type, name, value, this.botJob.getId(), -1, usedVars));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void loadWebPageFields() {
        webPageItems.clear();
        String selectSQL = " SELECT  "
                + "  bj.id AS bot_job_id,  "
                + "  bli.id AS block_loop_instruction_id,  "
                + "  bli.instruction_order_number,  "
                + "  bli.actions,  "
                + "  bli.name AS instruction_name,  "
                + "  bli.path,  "
                + "  bli.operation      "
                + " FROM bot_job bj  "
                + " LEFT JOIN block b ON b.bot_job_id = bj.id  "
                + " LEFT JOIN block_loop_instruction bli ON bli.block_id = b.id  "
                + " where bj.id = " + this.botJob.getId()
                + "  ORDER BY bj.id, b.block_order_number, bli.instruction_order_number ASC;";

        try (Statement stmt = getConnection().createStatement();
                ResultSet rs = stmt.executeQuery(selectSQL)) {
            while (rs.next()) {
                int id = rs.getInt("block_loop_instruction_id");
                String name = rs.getString("instruction_name");
                String actions = rs.getString("actions");

                // Filter out "SET", "GET", and "CK"
                if (actions != null
                        && !actions.equalsIgnoreCase(WebElementTagNameEnum.SET.getValue())
                        && !actions.equalsIgnoreCase(WebElementTagNameEnum.GET.getValue())
                        && !actions.equalsIgnoreCase(WebElementTagNameEnum.CK.getValue())) {
                    webPageItems.add(new ComboBoxVars(name, id, name));
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
