// Source code is unavailable, and was generated by the Fernflower decompiler.
package com.allinweb.ch.component.pane;

import com.allinweb.ch.component.pane.base.ARPane;
import com.allinweb.ch.component.scene.AROrganizationManagerScene;
import com.allinweb.ch.component.scene.ARScannedElementScene;
import com.allinweb.ch.component.scene.base.ARScene;
import com.allinweb.ch.facade.PerformDBEngine;
import com.allinweb.ch.facade.PerformDataBase;
import com.allinweb.ch.facade.PerformLists;
import com.allinweb.ch.facade.PerformMessage;
import com.allinweb.ch.facade.PreScanApplyService;
import com.allinweb.ch.facade.BotJobDetailsService;
import com.allinweb.ch.facade.BotJobTestRunCoordinator;
import com.allinweb.ch.facade.BotJobWorkspaceService;
import com.allinweb.ch.facade.BotJobScannerCoordinator;
import com.allinweb.ch.facade.BotJobNativeOperationService;
import com.allinweb.ch.facade.BotJobWorkspaceCloseCoordinator;
import com.allinweb.ch.facade.PreScanWorkflowService;
import com.allinweb.ch.facade.PreScanBrowserSession;
import com.allinweb.ch.facade.BotJobDetailsWorkspaceRegistry;
import com.allinweb.ch.facade.BotJobTransferPathRegistry;
import com.allinweb.ch.facade.BotJobTransferService;
import com.allinweb.ch.facade.BotJobToolbarConcurrencyGuard;
import com.allinweb.ch.license.LicenceVal;
import com.allinweb.ch.license.LicenseManager;
import com.allinweb.ch.model.*;
import com.allinweb.ch.socket.WebSocketSessionManager;
import com.allinweb.ch.util.*;
import com.google.common.base.Strings;
import com.google.gson.Gson;
import com.google.gson.JsonObject;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.*;
import java.util.function.BooleanSupplier;
import javafx.animation.PauseTransition;
import javafx.application.Platform;
import javafx.beans.value.ChangeListener;
import javafx.concurrent.Worker;
import javafx.scene.Node;
import javafx.scene.layout.*;
import javafx.scene.layout.Priority;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javafx.stage.DirectoryChooser;
import javafx.stage.FileChooser;
import javafx.stage.Stage;
import javafx.util.Duration;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class ARViewBotJobPane extends ARPane {

    private static final WebSocketSessionManager webSocketSessionManager = WebSocketSessionManager.getInstance();
    private static final ARPropertyManager arPropertyManager = ARPropertyManager.getInstance();
    private static final ARScannedElementScene arScannedElementScene = ARScannedElementScene.getInstance();
    private static final PerformLists performLists = PerformLists.getInstance();
    private static final PerformDBEngine performDBEngine = PerformDBEngine.getInstance();
    private static final PerformDataBase performDataBase = PerformDataBase.getInstance();
    private static final PerformMessage performMessage = PerformMessage.getInstance();
    private static final AROrganizationManagerScene organizationManagerScene =
            AROrganizationManagerScene.getInstance();
    private static final BotJobDetailsWorkspaceRegistry botJobDetailsWorkspaceRegistry =
            BotJobDetailsWorkspaceRegistry.getInstance();
    private static final BotJobDetailsService botJobDetailsService = BotJobDetailsService.getInstance();
    private static final BotJobWorkspaceService botJobWorkspaceService = BotJobWorkspaceService.getInstance();
    private static final BotJobTransferPathRegistry botJobTransferPathRegistry =
            BotJobTransferPathRegistry.getInstance();
    private static final BotJobTransferService botJobTransferService = BotJobTransferService.getInstance();
    private static final BotJobToolbarConcurrencyGuard botJobToolbarGuard = new BotJobToolbarConcurrencyGuard();
    private static final BotJobNativeOperationService botJobNativeOperations =
            BotJobNativeOperationService.createDefault(arPropertyManager, botJobToolbarGuard);
    private static final BotJobDetailsWebViewBootstrap webViewBootstrap = new BotJobDetailsWebViewBootstrap();
    private static final BotJobTestRunCoordinator botJobTestRunCoordinator = new BotJobTestRunCoordinator(
            botJobDetailsWorkspaceRegistry,
            new BotJobTestRunCoordinator.ScannerPort() {
                @Override
                public long start(
                        BotJobLoadDTO botJob,
                        int blockOrderNumber,
                        String endpointUrl,
                        boolean runSingleBlock,
                        BooleanSupplier cancellationRequested) {
                    return ARScannedElementPane.getInstance()
                            .submitTestRunBlockPlaywright(
                                    botJob,
                                    blockOrderNumber,
                                    endpointUrl,
                                    runSingleBlock,
                                    cancellationRequested);
                }

                @Override
                public void cancelStartup() {
                    ARScannedElementPane.getInstance().cancelTestRunStartup();
                }

                @Override
                public boolean stop(long executionId) {
                    return ARScannedElementPane.getInstance().stopTestRun(executionId);
                }

                @Override
                public boolean isComplete(long executionId) {
                    return ARScannedElementPane.getInstance().isTestRunExecutionComplete(executionId);
                }

                @Override
                public String terminalOutcome(long executionId) {
                    return ARScannedElementPane.getInstance().testRunExecutionTerminalState(executionId);
                }
            },
            (botJobId, requestId) -> com.allinweb.ch.socket.SimpleWebSocketServer.getInstance()
                    .publishBotJobDetailsRuntimeStateStrict(botJobId, requestId));
    private static final ExecutorService botJobToolbarExecutor = new ThreadPoolExecutor(
            1,
            1,
            0L,
            TimeUnit.MILLISECONDS,
            new SynchronousQueue<>(),
            runnable -> daemonThread(runnable, "bot-job-toolbar"),
            new ThreadPoolExecutor.AbortPolicy());
    protected static volatile ARViewBotJobPane instance;

    boolean isComponentBoxVisible;
    private Stage stage;
    // Set to hold all active WebSocket sessions
    private int portInitial;
    private String sessionId;
    private Gson gson = new Gson();
    private PayloadJson payloadEmpty;
    private boolean firstLoad = true;
    private String previousBotTasks;
    private boolean isEnabledLicence;
    private final BotJobScannerCoordinator scannerCoordinator;
    private final BotJobWorkspaceCloseCoordinator workspaceCloseCoordinator;
    private static final String EXECUTE_ALL_OPTION_LABEL = "Execute All";
    private VBox botJobContainer;
    private Pane mainPane;
    private HBox componentBox;
    private VBox componentContainer;
    private WebView webViewTasks = new WebView();
    private WebEngine webEngineTasks;
    private WebView webViewComp = new WebView();
    private WebEngine webEngineComp;
    private WebView webViewPreScanner = new WebView();
    private WebEngine webEnginePreScanner;
    private final Map<WebEngine, ChangeListener<Worker.State>> webViewLoadListeners = new IdentityHashMap<>();
    private final Map<WebEngine, PauseTransition> pendingWebViewBootstraps = new IdentityHashMap<>();
    private boolean isPreScannerVisible = false;
    private final PreScanWorkflowService preScanWorkflowService = new PreScanWorkflowService();
    // Temporary compatibility owner for zero-caller legacy helpers; removed after workflow verification.
    private final PreScanBrowserSession preScanBrowserSession = new PreScanBrowserSession();
    private ARScene arScene;
    private BotJobLoadDTO selectedBotJob;
    private volatile String reactEnvironmentUrl = "";
    // Private constructor to prevent instantiation
    private ARViewBotJobPane() {
        super();
        scannerCoordinator = BotJobScannerCoordinator.createDefault(
                new BotJobScannerCoordinator.ScenePort() {
                    @Override
                    public void open(HomeBankingLoadDTO homeBanking, BotJobLoadDTO botJob, BlockLoadDTO block) {
                        arScannedElementScene.initialize(homeBanking, botJob, block);
                        arScannedElementScene.showModal();
                    }

                    @Override
                    public void closeWebDrivers() {
                        arScannedElementScene.closeWebDrivers();
                    }

                    @Override
                    public void closeModal() {
                        arScannedElementScene.closeModal();
                    }
                },
                new BotJobScannerCoordinator.ErrorPort() {
                    @Override
                    public void databaseFailure(ErrorMessage error) {
                        performMessage.errorMessageOperationFailed(error);
                    }

                    @Override
                    public void launchFailure(Exception error) {
                        handleExceptionScan(error);
                    }
                },
                arPropertyManager::missingMandatoryPats);
        workspaceCloseCoordinator = new BotJobWorkspaceCloseCoordinator(
                () -> botJobToolbarGuard.activeOperation() != null
                        || preScanWorkflowService.isRunning()
                        || scannerCoordinator.isBusy(),
                new BotJobWorkspaceCloseCoordinator.ExecutionPort() {
                    @Override
                    public boolean isActive(int botJobId) {
                        return BotJobDetailsWorkspaceRegistry.isExecutionActive(
                                botJobDetailsWorkspaceRegistry.require(botJobId).executionState());
                    }

                    @Override
                    public void close(int botJobId) {
                        botJobDetailsWorkspaceRegistry.close(botJobId);
                    }
                },
                this::suspendReactWorkspaceSurfaces,
                botJobTransferPathRegistry::clear,
                preScanWorkflowService::shutdown,
                error -> log.debug("Unable to close the Pre Scan browser: {}", error.getMessage()));
    }

    private static Thread daemonThread(Runnable runnable, String name) {
        Thread worker = new Thread(runnable, name);
        worker.setDaemon(true);
        return worker;
    }

    private void setNavigationTimeValue(int value) {
        // Clamp to 0..10
        int v = value % 11;
        if (v < 0) {
            v += 11;
        }
        try {
            // ARPropertyManager behaves like java.util.Properties in many places
            // (user requirement: setProperty(ARPropertyEnum.NAVIGATION_TIME.getValue(), ...))
            arPropertyManager.setProperty(ARPropertyEnum.NAVIGATION_TIME.getValue(), String.valueOf(v));
        } catch (Exception ex) {
            throw new IllegalStateException("Unable to persist Navigation Time", ex);
        }
    }

    public static ARViewBotJobPane getInstance() {
        if (instance == null) {
            synchronized (ARViewBotJobPane.class) {
                if (instance == null) {
                    instance = new ARViewBotJobPane();
                }
            }
        }
        return instance;
    }

    public void initialize(ARScene arScene, BotJobLoadDTO selectedBotJob, boolean isEnabledLicence) {
        if (selectedBotJob == null || selectedBotJob.getId() == null || selectedBotJob.getId() <= 0) {
            throw new IllegalArgumentException("An active Bot Job is required");
        }
        boolean existingWorkspace = componentBox != null;
        Integer previousBotJobId = this.selectedBotJob == null ? null : this.selectedBotJob.getId();
        Integer requestedBotJobId = selectedBotJob == null ? null : selectedBotJob.getId();
        boolean switchingBotJob = existingWorkspace
                && previousBotJobId != null
                && requestedBotJobId != null
                && !previousBotJobId.equals(requestedBotJobId);
        if (switchingBotJob && !canCloseWorkspace()) {
            throw new IllegalStateException(
                    "Stop the active Bot Job operation before opening another Bot Job");
        }
        if (switchingBotJob) {
            suspendReactWorkspaceSurfaces(previousBotJobId);
        }
        this.isEnabledLicence = isEnabledLicence;
        this.arScene = arScene;
        this.selectedBotJob = selectedBotJob;
        BotJobWorkspaceService.GridSnapshot initialGridSnapshot;
        webViewBootstrap.activate(selectedBotJob);
        botJobDetailsWorkspaceRegistry.activate(selectedBotJob, isEnabledLicence);
        try {
            reactEnvironmentUrl = botJobDetailsService
                    .captureToolbarContext(selectedBotJob.getId())
                    .endpointUrl();
        } catch (RuntimeException error) {
            abortWorkspaceActivation(selectedBotJob.getId());
            throw new IllegalStateException(
                    "Unable to resolve persisted Bot Job endpoint during workspace activation", error);
        }
        try {
            initialGridSnapshot = botJobWorkspaceService.activate(selectedBotJob);
            applyGridSnapshot(initialGridSnapshot, false);
        } catch (BotJobWorkspaceService.WorkspaceLoadException error) {
            performMessage.errorMessageOperationFailed(error.error());
            abortWorkspaceActivation(selectedBotJob.getId());
            throw error;
        } catch (RuntimeException error) {
            abortWorkspaceActivation(selectedBotJob.getId());
            throw error;
        }

        if (existingWorkspace) {
            showBotJobWorkspace();
        }

        Integer currentScannerBotJobId = arScannedElementScene.getCurrentBotJob() == null
                ? null
                : arScannedElementScene.getCurrentBotJob().getId();
        switch (botJobWorkspaceService.scannerDisposition(selectedBotJob, currentScannerBotJobId)) {
            case OPEN -> callScannerTool(selectedBotJob, arScene);
            case CLOSE -> scannerCoordinator.close();
            case KEEP -> {
                // No scanner transition is required for this activation.
            }
        }

        if (Strings.isNullOrEmpty(previousBotTasks)) {
            String portSocket = arPropertyManager.getProperty(ARPropertyEnum.PORT_SOCKET);
            if (portSocket != null) {
                portInitial = Integer.parseInt(portSocket);
            }
        }

        if (existingWorkspace) reloadReactWorkspaceSurfaces();
    }

    private void clearBotJobWorkspaceCaches() {
        botJobWorkspaceService.clearAllCaches();
    }

    private void abortWorkspaceActivation(int botJobId) {
        try {
            suspendReactWorkspaceSurfaces(botJobId);
        } finally {
            botJobDetailsWorkspaceRegistry.close(botJobId);
            clearBotJobWorkspaceCaches();
        }
    }

    private boolean refreshGrids() {
        try {
            applyGridSnapshot(botJobWorkspaceService.refresh(selectedBotJob), !firstLoad);
            return true;
        } catch (BotJobWorkspaceService.WorkspaceLoadException error) {
            performMessage.errorMessageOperationFailed(error.error());
            return false;
        }
    }

    private void applyGridSnapshot(BotJobWorkspaceService.GridSnapshot snapshot, boolean publish) {
        webViewBootstrap.updatePayload(selectedBotJob.getId(), "botJobTasks", snapshot.botJobJson());
        webViewBootstrap.updatePayload(selectedBotJob.getId(), "componentTasks", snapshot.componentJson());
        if (!publish) return;
        com.allinweb.ch.socket.InstructionRealtimePublisher publisher =
                com.allinweb.ch.socket.InstructionRealtimePublisher.getInstance();
        publisher.publishSerializedSnapshot(
                selectedBotJob.getHomeBankingId(), "botJobTasks", snapshot.botJobJson());
        publisher.publishSerializedSnapshot(
                selectedBotJob.getHomeBankingId(), "componentTasks", snapshot.componentJson());
    }

    private void buildViewComponent() {
        // ── botJobTasks (unchanged) ─────────────────────────────────────────
        if (performLists.getListBotJob().isEmpty()) {
            ErrorMessage errorMessage = performDBEngine.loadCompleteJobs(selectedBotJob.getId());
            if (errorMessage != null) {
                performMessage.errorMessageOperationFailed(errorMessage);
            }
        }

        setPayloadEmpty("botJobTasks");
        String jsonData = gson.toJson(payloadEmpty);

        if (!performLists.getListBotJob().isEmpty()) {
            List<InstructionLoad> instructions = performLists.buildJsonViewData(performLists.getListBotJob());
            if (!instructions.isEmpty()) {
                String jsonPath = arPropertyManager.getProperty(ARPropertyEnum.PATH_DB);
                performMessage.outputJson(instructions, "botJobTasks-" + selectedBotJob.getId(), jsonPath, false);
                jsonData = gson.toJson(instructions);
            }
        }

        webEngineTasks = webViewTasks.getEngine();
        webEngineTasks.javaScriptEnabledProperty().set(true);

        sessionId = "botJobTasks";
        buildWebView(
                webEngineTasks,
                jsonData,
                portInitial,
                sessionId,
                selectedBotJob.getId());

        // ── componentTasks (unchanged) ──────────────────────────────────────
        if (performLists.getListBotJobComp().isEmpty()) {
            ErrorMessage errorMessage = performDataBase.loadComponentsComplete(
                    selectedBotJob.getHomeBankingId(), selectedBotJob.getId(), selectedBotJob.getName());
            if (errorMessage != null) {
                performMessage.errorMessageOperationFailed(errorMessage);
            }
        }

        setPayloadEmpty("componentTasks");
        jsonData = gson.toJson(payloadEmpty);

        if (!performLists.getListBotJobComp().isEmpty()) {
            List<InstructionLoad> instructions = performLists.buildJsonViewData(performLists.getListBotJobComp());
            if (!instructions.isEmpty()) {
                String jsonPath = arPropertyManager.getProperty(ARPropertyEnum.PATH_DB);
                performMessage.outputJson(instructions, "componentTasks-" + selectedBotJob.getId(), jsonPath, false);
                jsonData = gson.toJson(instructions);
            }
        }

        webEngineComp = webViewComp.getEngine();
        webEngineComp.javaScriptEnabledProperty().set(true);

        sessionId = "componentTasks";
        buildWebView(
                webEngineComp,
                jsonData,
                portInitial,
                sessionId,
                selectedBotJob.getId());

        webEnginePreScanner = webViewPreScanner.getEngine();
        webEnginePreScanner.javaScriptEnabledProperty().set(true);

        sessionId = "preScannerGrid";
        buildWebView(
                webEnginePreScanner,
                "[]",
                portInitial,
                sessionId,
                selectedBotJob.getId());

        previousBotTasks = "botJobTasks";
    }

    @Override
    public void initUIComponents() {
        sessionId = "botJobTasks";
        if (Strings.isNullOrEmpty(previousBotTasks) || !previousBotTasks.equals(sessionId)) {
            buildViewComponent();
        }

        if (!performLists.getListBotJob().isEmpty() && performLists.getListBlock().isEmpty()) {
            performDataBase.loadBlocks(selectedBotJob.getId(), selectedBotJob.getName(), "block");
        }
        if (!performLists.getListBotJobComp().isEmpty() && performLists.getListBlockComp().isEmpty()) {
            performDataBase.loadBlocks(
                    selectedBotJob.getHomeBankingId(), selectedBotJob.getName(), "component_block");
        }

        initComponentWorkspace();
        componentBox = new HBox(new Node[] {webViewTasks});
        firstLoad = false;
        HBox.setHgrow(webViewTasks, Priority.ALWAYS);
        VBox.setVgrow(webViewTasks, Priority.ALWAYS);
        HBox.setHgrow(webViewPreScanner, Priority.ALWAYS);
        VBox.setVgrow(webViewPreScanner, Priority.ALWAYS);
        HBox.setHgrow(componentContainer, Priority.NEVER);

        botJobContainer = new VBox(componentBox);
        VBox.setVgrow(botJobContainer, Priority.ALWAYS);
        VBox.setVgrow(componentBox, Priority.ALWAYS);
        HBox.setHgrow(componentBox, Priority.ALWAYS);

        mainPane = new AnchorPane(botJobContainer);
        AnchorPane.setTopAnchor(botJobContainer, ARConstants.SPACE_M);
        AnchorPane.setBottomAnchor(botJobContainer, ARConstants.SPACE_M);
        AnchorPane.setLeftAnchor(botJobContainer, ARConstants.SPACE_M);
        AnchorPane.setRightAnchor(botJobContainer, ARConstants.SPACE_M);
    }

    private void buildWebView(
            WebEngine webEngine,
            String jsonData,
            int finalPort,
            String sessionIdFromJava,
            int botJobId) {
        webViewBootstrap.updatePayload(botJobId, sessionIdFromJava, jsonData);
        ChangeListener<Worker.State> previousListener = webViewLoadListeners.remove(webEngine);
        if (previousListener != null) {
            webEngine.getLoadWorker().stateProperty().removeListener(previousListener);
        }
        String indexUrl = WebBuildExtractor.getIndexUrl();
        ChangeListener<Worker.State> listener = (obs, oldState, newState) -> {
            if (newState == Worker.State.SUCCEEDED) {
                cancelPendingWebViewBootstrap(webEngine);
                if (!indexUrl.equals(webEngine.getLocation())) return;
                PauseTransition delay = new PauseTransition(Duration.seconds(1));
                pendingWebViewBootstraps.put(webEngine, delay);
                delay.setOnFinished(event -> {
                    if (pendingWebViewBootstraps.get(webEngine) != delay) return;
                    pendingWebViewBootstraps.remove(webEngine);
                    if (!indexUrl.equals(webEngine.getLocation())) return;
                    try {
                        BotJobDetailsWebViewBootstrap.Context context = webViewBootstrap.resolve(sessionIdFromJava);
                        webEngine.executeScript(
                                BotJobDetailsWebViewBootstrap.initializationScript(context, finalPort, gson));
                    } catch (Exception error) {
                        log.error("buildWebView Error: " + error.getMessage());
                    }
                });
                delay.play();
            }
        };
        webViewLoadListeners.put(webEngine, listener);
        webEngine.getLoadWorker().stateProperty().addListener(listener);
        webEngine.load(indexUrl);
    }

    private void cancelPendingWebViewBootstrap(WebEngine webEngine) {
        PauseTransition pending = pendingWebViewBootstraps.remove(webEngine);
        if (pending != null) pending.stop();
    }

    @Override
    public void initUIBehaviour() {}

    public void handlePreScanCommand(String type, JsonObject jsonEntry) {
        if ("PRE_SCAN_CLEAR_GRID".equals(type)) {
            sendPreScanReset();
            return;
        }

        if ("PRE_SCAN_REFRESH_PAGE".equals(type)) {
            Thread worker = new Thread(
                    this::refreshPreScanPage,
                    "pre-scan-refresh-" + (selectedBotJob == null ? "unknown" : selectedBotJob.getId()));
            worker.setDaemon(true);
            worker.start();
            return;
        }

        if (!"PRE_SCAN_PAGE".equals(type)) {
            return;
        }

        String searchTerms = jsonEntry != null && jsonEntry.has("searchTerms")
                ? jsonEntry.get("searchTerms").getAsString()
                : "";
        boolean searchHidden = jsonEntry != null
                && jsonEntry.has("searchHiddenFields")
                && jsonEntry.get("searchHiddenFields").getAsBoolean();

        Thread worker = new Thread(
                () -> runPreScan(searchTerms, searchHidden),
                "pre-scan-" + (selectedBotJob == null ? "unknown" : selectedBotJob.getId()));
        worker.setDaemon(true);
        worker.start();
    }

    private void refreshPreScanPage() {
        if (selectedBotJob == null) {
            log.warn("PRE SCAN refresh skipped: no selected bot job");
            return;
        }
        preScanWorkflowService.refresh(preScanContext(), preScanSink());
    }

    private void runPreScan(String searchTerms, boolean searchHidden) {
        if (selectedBotJob == null) {
            log.warn("PRE SCAN skipped: no selected bot job");
            return;
        }
        preScanWorkflowService.scan(preScanContext(), searchTerms, searchHidden, preScanSink());
    }

    @Deprecated
    private void runPreScanLegacy(String searchTerms, boolean searchHidden) {
        if (selectedBotJob == null) {
            log.warn("PRE SCAN skipped: no selected bot job");
            return;
        }

        if (!preScanBrowserSession.tryBeginScan()) {
            log.warn("PRE SCAN skipped: a scan is already in progress");
            sendPreScanStatus("running", "A pre-scan is already in progress...", 0);
            return;
        }

        try {
            String endpointUrl = selectedEndpointUrl();
            if (Strings.isNullOrEmpty(endpointUrl)) {
                log.warn("PRE SCAN skipped: no endpoint URL selected");
                sendPreScanStatus("failed", "No endpoint URL selected.", 0);
                return;
            }

            sendPreScanStatus("waiting", "Starting pre-scan for " + endpointUrl, 0);
            sendPreScanReset();

            String browserType = arPropertyManager.getProperty(ARPropertyEnum.BROWSER);
            String optionsConfig = preScanOptionsConfig();

            ensurePreScanBrowserOpen(browserType, endpointUrl, optionsConfig);
            // Legacy parity: in AR Web Factory the page has been open (and hydrated) long
            // before the user clicks Page Scanner. Here the scan can fire right after
            // DOMContentLoaded, so wait until the network is quiet and the DOM stops
            // mutating — otherwise the first scan sees the half-rendered page.
            sendPreScanStatus("waiting", "Loading the Page - waiting to settle...", 0);
            long settledMs = preScanBrowserSession.waitForPageSettled(15000);
            log.info("PRE SCAN - page settled after {} ms", settledMs);
            sendPreScanStatus("running", "web elements...", 0);
            List<ElementDTO> elements = preScanBrowserSession.scanElements(searchTermsArray(searchTerms), searchHidden);
            elements = keepActionableElements(elements);
            resolvePreScanNames(elements);
            persistPreScanDiagnostics(elements);
            sendPreScanElements(elements);
            int count = elements == null ? 0 : elements.size();
            sendPreScanStatus(
                    count == 0 ? "empty" : "done",
                    count == 0 ? "No elements found." : "Found " + count + " web element(s).",
                    count);
            log.info("PRE SCAN - sent {} elements to preScannerGrid", elements == null ? 0 : elements.size());
        } catch (Exception error) {
            log.error("PRE SCAN failed", error);
            sendPreScanStatus("failed", String.valueOf(error.getMessage()), 0);
            Platform.runLater(() -> performMessage.errorMessage(
                    "PRE SCAN - Failed",
                    "<span style='color: #D32F2F; font-weight: bold;'>" + String.valueOf(error.getMessage())
                            + "</span>",
                    "The lightweight scanner could not complete for the selected URL.",
                    null,
                    null,
                    0));
        } finally {
            preScanBrowserSession.finishScan();
        }
    }

    /**
     * Every element the pre-scan ships must map to an executable action: input = the bot
     * can type, button = it can click, output/label = it can read. Anything else (bare
     * div/span containers matched by a broad selector) is noise for the dashboard and the
     * diagnostics dumps, so it is dropped here — pre-scan path only, legacy untouched.
     */
    private List<ElementDTO> keepActionableElements(List<ElementDTO> elements) {
        if (elements == null || elements.isEmpty()) {
            return elements;
        }
        List<ElementDTO> actionable = new ArrayList<>();
        for (ElementDTO element : elements) {
            String type = element == null
                    ? ""
                    : java.util.Objects.toString(element.getTypeElement(), "").toLowerCase(java.util.Locale.ROOT);
            if (type.equals("input") || type.equals("button") || type.equals("output") || type.equals("label")) {
                actionable.add(element);
            }
        }
        int dropped = elements.size() - actionable.size();
        if (dropped > 0) {
            log.info("PRE SCAN - dropped {} non-actionable element(s) (no type/click/read action)", dropped);
        }
        return actionable;
    }

    /**
     * Naming parity with the legacy Page Scanner: screenshot the pre-scan browser,
     * correlate the scanned element rects with the OCR words, and let
     * {@code ElementTextResolver} fill {@code definedName} / correct {@code someText} —
     * the same chain {@code PerformListElements} runs after a legacy scan. Mutates the
     * elements in place BEFORE they are dumped/sent, so both the dashboard and
     * {@code elementDTO-PS-BJ.json} carry resolved names. Failures are non-fatal: the
     * scan still ships, just with unresolved names.
     */
    private void resolvePreScanNames(List<ElementDTO> elements) {
        if (elements == null || elements.isEmpty()) {
            return;
        }
        try {
            sendPreScanStatus("running", "Resolving element names (OCR)...", elements.size());
            String jsonPath = arPropertyManager.getProperty(ARPropertyEnum.PATH_DB);
            Integer scanHomeBankingId = selectedBotJob.getHomeBankingId();
            Integer scanHomeUrlId = selectedBotJob.getHomeUrlId();
            ElementDTO[] asArray = elements.toArray(new ElementDTO[0]);

            com.allinweb.ch.util.PageDiagnosticDumper.dumpRectsFromElements(
                    preScanBrowserSession.playwrightDriver(), asArray, jsonPath, "page-BJ");
            com.allinweb.ch.util.PageOcrDumper.runAndDump(
                    preScanBrowserSession.playwrightDriver(),
                    asArray,
                    jsonPath,
                    "page-BJ",
                    scanHomeBankingId,
                    scanHomeUrlId);

            // Keep the pre-OCR scanned text so the dashboard's per-block OCR review panel
            // can show scanned vs resolved and let the client agree/defer per element.
            String[] scannedTexts = new String[asArray.length];
            for (int i = 0; i < asArray.length; i++) {
                scannedTexts[i] = asArray[i] == null ? null : asArray[i].getSomeText();
            }

            com.allinweb.ch.model.OcrConfig resolverCfg =
                    com.allinweb.ch.facade.OcrConfigService.getInstance().resolveFor(scanHomeBankingId, scanHomeUrlId);
            // The correlation file name is fixed by PageOcrDumper regardless of prefix.
            com.allinweb.ch.facade.ElementTextResolver.resolveAll(
                    asArray,
                    java.nio.file.Paths.get(
                            jsonPath, com.allinweb.ch.util.PageDiagnosticDumper.SUBFOLDER, "ocr-correlation-HP.json"),
                    resolverCfg);

            for (int i = 0; i < asArray.length; i++) {
                ElementDTO element = asArray[i];
                String scanned = scannedTexts[i];
                if (element == null || Strings.isNullOrEmpty(scanned) || scanned.equals(element.getSomeText())) {
                    continue;
                }
                AttributeData[] existing =
                        element.getAttributeData() == null ? new AttributeData[0] : element.getAttributeData();
                AttributeData[] updated = new AttributeData[existing.length + 1];
                System.arraycopy(existing, 0, updated, 0, existing.length);
                updated[existing.length] = new AttributeData("scanned-text", scanned);
                element.setAttributeData(updated);
            }
        } catch (Exception ocrError) {
            log.warn("PRE SCAN - OCR name resolution failed (non-fatal): {}", ocrError.getMessage());
        }
    }

    /**
     * Comparison artifact for tracking differences against the original AR Web Factory
     * Page Scanner: writes the same dumps {@code PerformListElements} produces
     * ({@code elementDTO-PS.json} / {@code AI-ElementDTO-PS.json}) under the {@code -BJ}
     * suffix. Note: pre-scan skips the OCR {@code ElementTextResolver}, so
     * {@code definedName} is empty here by design — comparisons should ignore that field
     * until resolver parity lands.
     */
    private void persistPreScanDiagnostics(List<ElementDTO> elements) {
        if (elements == null || elements.isEmpty()) {
            return;
        }
        try {
            String jsonPath = arPropertyManager.getProperty(ARPropertyEnum.PATH_DB);
            ElementDTO[] asArray = elements.toArray(new ElementDTO[0]);

            List<String> excludeList = List.of("optional", "blockMarked", "editMode");
            performMessage.outputJsonElementDTO(asArray, excludeList, "elementDTO-PS-BJ", jsonPath);

            List<String> aiExcludeList = List.of(
                    "optional",
                    "blockMarked",
                    "editMode",
                    "id",
                    "attributeData",
                    "typeElement",
                    "customXPath",
                    "shadowRoot",
                    "nestedShadow",
                    "searchAttributeValue",
                    "attributeType",
                    "attributeValue");
            performMessage.outputJsonElementDTO(asArray, aiExcludeList, "AI-ElementDTO-PS-BJ", jsonPath);
        } catch (Exception jsonError) {
            log.warn("PRE SCAN - failed to persist element JSON: {}", jsonError.getMessage());
        }
    }

    private void ensurePreScanBrowserOpen(String browserType, String endpointUrl, String optionsConfig) {
        if (!preScanBrowserSession.isOpen()) {
            log.info("PRE SCAN - opening isolated visible Playwright at {}", endpointUrl);
            sendPreScanStatus("waiting", "Loading the Page - Opening isolated browser...", 0);
            preScanBrowserSession.ensureOpen(browserType, endpointUrl, optionsConfig);
            return;
        }

        String currentUrl = "";
        try {
            currentUrl = preScanBrowserSession.currentUrl();
        } catch (Exception ignored) {
            // If currentUrl cannot be read, still try to scan the active page.
        }
        log.info("PRE SCAN - scanning current isolated browser page {}", currentUrl);
        sendPreScanStatus("waiting", "Loading the Page - Using current browser page...", 0);
    }

    /**
     * Pane-free row test (Test Click / Test Input) against the ISOLATED pre-scan browser.
     * The legacy path runs {@code ARScannedElementPane.testingActions} on the shared
     * driver; here the scanned page lives in the isolated Pre Scan browser session, so the test must too.
     * Results stream to the dashboard status bar (done/failed) instead of a modal.
     */
    public void handlePreScanElementTest(SplitDTO splitDTO, String testType) {
        if (!preScanWorkflowService.isOpen()) {
            sendPreScanStatus("failed", "No pre-scan browser open. Run the Page Scanner first.", 0);
            return;
        }
        ElementDTO[] details = splitDTO == null ? null : splitDTO.getElementDetails();
        if (details == null || details.length == 0 || details[0] == null) {
            return;
        }
        ElementDTO elementDTO = details[0];
        Thread worker = new Thread(
                () -> runPreScanElementTest(elementDTO, testType),
                "pre-scan-test-" + (selectedBotJob == null ? "unknown" : selectedBotJob.getId()));
        worker.setDaemon(true);
        worker.start();
    }

    private void runPreScanElementTest(ElementDTO elementDTO, String testType) {
        preScanWorkflowService.testElement(elementDTO, testType, preScanSink());
    }

    private PreScanWorkflowService.Context preScanContext() {
        return new PreScanWorkflowService.Context(
                selectedBotJob.getId(),
                selectedBotJob.getName(),
                selectedBotJob.getHomeBankingId(),
                selectedBotJob.getHomeUrlId(),
                selectedEndpointUrl(),
                arPropertyManager.getProperty(ARPropertyEnum.BROWSER),
                preScanOptionsConfig(),
                arPropertyManager.getProperty(ARPropertyEnum.PATH_DB));
    }

    private PreScanWorkflowService.Sink preScanSink() {
        return new PreScanWorkflowService.Sink() {
            @Override
            public void status(String status, String message, int elementCount) {
                sendPreScanStatus(status, message, elementCount);
            }

            @Override
            public void reset() {
                sendPreScanReset();
            }

            @Override
            public void elements(List<ElementDTO> elements) {
                sendPreScanElements(elements);
            }

            @Override
            public void failure(String message) {
                Platform.runLater(() -> performMessage.errorMessage(
                        "PRE SCAN - Failed",
                        "<span style='color: #D32F2F; font-weight: bold;'>" + message + "</span>",
                        "The lightweight scanner could not complete for the selected URL.",
                        null,
                        null,
                        0));
            }
        };
    }

    private String preScanOptionsConfig() {
        HomeBankingLoadDTO homeBanking = performLists.getHomeBankingById(selectedBotJob.getHomeBankingId());
        if (homeBanking == null) {
            homeBanking = selectedBotJob.getHomeBankingLoadDTO();
        }
        return homeBanking != null && homeBanking.getOptionsConfig() != null ? homeBanking.getOptionsConfig() : "";
    }

    private void sendPreScanStatus(String status, String message, int elementCount) {
        if (selectedBotJob == null) {
            return;
        }
        java.util.Map<String, Object> payload = new java.util.LinkedHashMap<>();
        payload.put("status", status);
        payload.put("message", message == null ? "" : message);
        payload.put("elementCount", elementCount);
        payload.put("botJobId", selectedBotJob.getId());
        payload.put("botJobName", selectedBotJob.getName());
        payload.put("homeBankingId", selectedBotJob.getHomeBankingId());
        webSocketSessionManager.sendMessageJson(
                selectedBotJob.getHomeBankingId(), "preScannerGrid", gson.toJson(payload), "preScanStatus");
    }

    private String selectedEndpointUrl() {
        if (!Strings.isNullOrEmpty(reactEnvironmentUrl)) {
            return reactEnvironmentUrl;
        }
        HomeUrlDTO homeUrl = selectedBotJob == null
                ? null
                : performLists.getHomeUrlByBankId(selectedBotJob.getHomeBankingId(), selectedBotJob.getHomeUrlId());
        if (homeUrl != null && !Strings.isNullOrEmpty(homeUrl.getUrl())) {
            return homeUrl.getUrl();
        }
        return selectedBotJob != null && selectedBotJob.getHomeBankingLoadDTO() != null
                ? selectedBotJob.getHomeBankingLoadDTO().getUrl()
                : "";
    }

    private String[] searchTermsArray(String searchTerms) {
        if (Strings.isNullOrEmpty(searchTerms)) {
            // Same default profile the AR Web Factory pane scans with. Empty terms
            // would fall through to the scanner's kitchen-sink DEFAULT_SELECTOR
            // (which ends in "span, div") and flood the grid with container junk.
            return new String[] {"input", "textarea", "button", "a", "select", "label"};
        }
        return java.util.Arrays.stream(searchTerms.split(","))
                .map(String::trim)
                .filter(term -> !term.isEmpty())
                .toArray(String[]::new);
    }

    private void sendPreScanReset() {
        sendPreScanPayload(List.of());
    }

    private void sendPreScanElements(List<ElementDTO> elements) {
        if (elements == null || elements.isEmpty()) {
            sendPreScanReset();
            return;
        }
        int chunkSize = 25;
        for (int i = 0; i < elements.size(); i += chunkSize) {
            sendPreScanPayload(elements.subList(i, Math.min(i + chunkSize, elements.size())));
        }
    }

    private void sendPreScanPayload(List<ElementDTO> elements) {
        SplitDTO payload = new SplitDTO();
        payload.setHomeBankingId(selectedBotJob.getHomeBankingId());
        payload.setBotJobId(selectedBotJob.getId());
        payload.setBotJobName(selectedBotJob.getName());
        payload.setType("SEARCH_TOOL");
        payload.setSessionId("preScannerGrid");
        payload.setOperationId("searchTerms");
        payload.setElementDetails(elements.toArray(new ElementDTO[0]));
        payload.setBlocks(preScanBlockOptions());
        webSocketSessionManager.sendMessageJson(
                selectedBotJob.getHomeBankingId(), "preScannerGrid", gson.toJson(payload), "searchTerms");
    }

    private List<java.util.Map<String, Object>> preScanBlockOptions() {
        if (performLists.getListBlock().isEmpty()) {
            ErrorMessage errorMessage =
                    performDataBase.loadBlocks(selectedBotJob.getId(), selectedBotJob.getName(), "block");
            if (errorMessage != null) {
                log.warn("PRE SCAN - could not load blocks: {}", errorMessage.getErrorMessage());
            }
        }
        return performLists.getListBlock().stream()
                .filter(block -> block != null && block.getId() != null)
                .filter(block ->
                        block.getBotJobId() == null || selectedBotJob.getId().equals(block.getBotJobId()))
                .sorted(java.util.Comparator.comparingInt(
                        block -> block.getBlockOrderNumber() == null ? Integer.MAX_VALUE : block.getBlockOrderNumber()))
                .map(block -> {
                    java.util.Map<String, Object> option = new java.util.LinkedHashMap<>();
                    option.put("blockId", block.getId());
                    option.put("blockOrderNumber", block.getBlockOrderNumber());
                    option.put("blockName", block.getName());
                    return option;
                })
                .toList();
    }

    private void callScannerTool(BotJobLoadDTO scannerBotJob, ARScene scannerScene) {
        scannerCoordinator.open(scannerBotJob, scannerScene::startNewThread);
    }

    public HomeUrlDTO findMatchingHomeUrlDTO(BotJobLoadDTO botJobLoadDTO) {
        Integer targetHomeUrlId = botJobLoadDTO.getHomeUrlId();
        HomeBankingLoadDTO homeBanking = botJobLoadDTO.getHomeBankingLoadDTO();

        if (homeBanking != null && homeBanking.getHomeUrlDTOs() != null) {
            return homeBanking.getHomeUrlDTOs().stream()
                    .filter(dto -> dto.getId().equals(targetHomeUrlId))
                    .findFirst()
                    .orElse(null);
        }

        return null;
    }

    private void executeScannerTask(BotJobLoadDTO scannerBotJob) {

        ErrorMessage errorMessage = performDBEngine.loadHomeBanking(scannerBotJob.getHomeBankingId());
        if (errorMessage == null) {
            errorMessage = performDBEngine.loadHomeUrls(scannerBotJob.getHomeBankingId());
        }

        if (errorMessage != null) {
            performMessage.errorMessageOperationFailed(errorMessage);
            return;
        }
        HomeBankingLoadDTO homeBanking = performLists.getListHomeBanking().isEmpty()
                ? null
                : performLists.getListHomeBanking().get(0);

        HomeUrlDTO homeUrlDTO = findMatchingHomeUrlDTO(scannerBotJob);
        if (homeUrlDTO != null && homeBanking != null) {
            scannerBotJob.setHomeUrlId(homeUrlDTO.getId());
            homeBanking.setUrl(homeUrlDTO.getUrl());
        }

        BlockLoadDTO scannerBlock = null;
        if (scannerBotJob.getBlockLoadDTOList() != null
                && !scannerBotJob.getBlockLoadDTOList().isEmpty()) {
            scannerBlock = scannerBotJob.getBlockLoadDTOList().get(0);
        } else {

            errorMessage = performDataBase.loadBlocks(scannerBotJob.getId(), scannerBotJob.getName(), "block");
            if (errorMessage != null) {
                performMessage.errorMessageOperationFailed(errorMessage);
            }
            if (!performLists.getListBlock().isEmpty()) {
                scannerBlock = performLists.getListBlock().get(0);
            }
        }

        try {
            arScannedElementScene.initialize(homeBanking, scannerBotJob, scannerBlock);
            arScannedElementScene.showModal(); // Make sure the scene is shown
        } catch (Exception ex) {
            handleExceptionScan(ex);
        }
    }

    private void handleExceptionScan(Exception error) {
        // Log the exception

        if (error.getMessage().contains("null")) {
            log.error("Error: " + error.getMessage());
            return;
        }

        log.error("ERROR Calling openScannerButton -> Cause: " + error.getMessage());

        // Display the error message to the user
        String browser = arPropertyManager.getProperty(ARPropertyEnum.BROWSER);
        String webDriverPath = arPropertyManager.getProperty(ARPropertyEnum.PATH_WEBDRIVER);

        if (error.getMessage().contains("no such window: target window already closed")
                || error.getMessage().contains("web view not found")) {
            log.error("Error Calling SCANNER: {}", webDriverPath);
            performMessage.errorMessage(
                    "Error Calling SCANNER",
                    "<span style='font-style: italic;'>Web Browser was closed before the Scanner Tool!</span>",
                    "<span style='color: #E65100; font-weight: bold;'>WebDriver path:</span> <span style='font-weight: bold;'>"
                            + webDriverPath + "</span>",
                    "<span style='font-style: italic;'>Please close and Re-Open the Scanner Tool.</span>",
                    "<span style='font-style: italic;'>Details: " + "Web Browser was closed before the Scanner Tool"
                            + "</span>",
                    0);
        } else {

            //            "invalid session id"

            if (!error.getMessage().contains("Current browser version")) {
                log.error("Error Open URL: " + error.getMessage());

                //                performMessage.errorMessage("Error Open URL", msg1, msg2, msg3, msg4, 0);

                if (error.getMessage().contains("session deleted as the browser has closed the connection")
                        || error.getMessage().contains("Expected condition failed: waiting for com")) {
                    log.error("Interruption Calling SCANNER: {}", webDriverPath);
                    performMessage.errorMessage(
                            "Interruption Calling SCANNER",
                            "<span style='font-style: italic;'>Session deleted as the browser has closed the connection!</span>",
                            "<span style='color: #E65100; font-weight: bold;'>WebDriver path:</span> <span style='font-weight: bold;'>"
                                    + webDriverPath + "</span>",
                            "<span style='font-style: italic;'>Please close and Re-Open the Scanner Tool.</span>",
                            "<span style='font-style: italic;'>Details: "
                                    + "Web Browser was closed before the Scanner Tool" + "</span>",
                            0);
                } else {
                    log.error("WebDriver Access Issue: Browser: {} - {}", browser, webDriverPath);
                    performMessage.errorMessage(
                            "WebDriver Access Issue",
                            "<span style='color: #D32F2F; font-weight: bold; font-size: 1.1em;'>Failed to access WebDriver.</span>",
                            //                        "<span style='font-style: italic;'>It appears the WebDriver data
                            // directory might be locked by another process.</span>",
                            "<span style='font-weight: bold;'>Please ensure the following:</span>",
                            "<ul>" + "   <li>No other instances of the browser or WebDriver are currently running.</li>"
                                    + "   <li>The specified WebDriver path is correct and accessible: <span style='font-weight: bold;'>"
                                    + webDriverPath + "</span></li>"
                                    + "   <li>The configured browser is: <span style='font-weight: bold;'>"
                                    + browser + "</span></li>" + "</ul>",
                            "<span style='font-style: italic;'>If the issue persists, try closing all related browser processes and restarting the application.</span>",
                            0);
                }
            } else {
                log.error("Error Open URL: " + error.getMessage());

                int lastSlashIndex = webDriverPath.lastIndexOf('\\');
                String directoryPath = webDriverPath.substring(0, lastSlashIndex + 1); // includes the last backslash
                String fileName = webDriverPath.substring(lastSlashIndex + 1);

                log.error("Invalid URL or Navigation Error: {} - {} - {}", browser, directoryPath, fileName);
                performMessage.errorMessage(
                        "Invalid URL or Navigation Error",
                        "<span style='color: #D32F2F; font-weight: bold; font-size: 1.1em;'>The provided URL is invalid or cannot be reached.</span>",
                        "<span style='font-weight: bold;'>Please verify the following:</span>",
                        "<ul>"
                                + "   <li>The entered URL is valid and accessible.</li>"
                                + "   <li>The installed browser version: <span style='color: #008b8b; font-weight: bold;'>"
                                + browser + "</span></li>"
                                + "   <li>The WebDriver path:<br><span style='color: #008b8b; font-weight: bold;'>"
                                + directoryPath + "</span></li>"
                                + "   <li>The WebDriver file:<br><span style='color: #008b8b; font-weight: bold;'>"
                                + fileName + "</span></li>"
                                + "   <li>Ensure the WebDriver and browser are compatible and correctly configured.</li>"
                                + "</ul>",
                        "<span style='font-style: italic;'>Check the URL format (e.g., including https://) and review browser/WebDriver logs for more details.</span>",
                        0);
            }
        }

        //        Platform.runLater(() -> {
        //            JOptionPane.showMessageDialog(
        //                    null,
        //                    "An error has occurred Calling SCAN: Cause: " + ex.getMessage(),
        //                    "Error calling in SCAN",
        //                    JOptionPane.ERROR_MESSAGE);
        //        });
    }

    public Pane getPaneReference() {
        //        mainPane.setUserData(this);
        return mainPane;
    }

    private void initComponentWorkspace() {
        this.componentContainer = new VBox(new Node[] {webViewComp});
        HBox.setHgrow(this.webViewComp, Priority.ALWAYS);
        VBox.setVgrow(this.webViewComp, Priority.ALWAYS); // Ensures vertical growth

        this.componentContainer.setSpacing(ARConstants.SPACE_XS);

        this.componentContainer.setMaxWidth(800.0D);
        this.componentContainer.setVisible(false);
        this.componentContainer.setManaged(false);
        isComponentBoxVisible = false;
    }

    public BotJobLoadDTO getBotJobDTO() {
        return selectedBotJob;
    }

    /** Executes an operation from the React Bot Job Details toolbar. */
    public CompletableFuture<BotJobToolbarActionResult> handleReactToolbarAction(
            BotJobToolbarAction action, BotJobDetailsRequest request) {
        CompletableFuture<BotJobToolbarActionResult> completion = new CompletableFuture<>();
        if (action == null || request == null) {
            completion.complete(BotJobToolbarActionResult.failure(action, "Bot Job toolbar action is required"));
            return completion;
        }
        if (action == BotJobToolbarAction.STOP_TEST_RUN) {
            dispatchPromptStop(request, completion);
            return completion;
        }

        final BotJobToolbarContext context;
        try {
            context = botJobDetailsService.captureToolbarContext(request.botJobId());
            requireNonStopActionAllowed(context);
            requireExecutionStartAllowed(action);
        } catch (Exception error) {
            completeToolbarFailure(action, completion, error);
            return completion;
        }

        BotJobToolbarConcurrencyGuard.Lease lease =
                botJobToolbarGuard.tryAcquire(context.botJobId(), context.workspaceEpoch(), action);
        if (lease == null) {
            completion.complete(BotJobToolbarActionResult.failure(
                    action, "Another Bot Job toolbar operation is already in progress"));
            return completion;
        }

        if (action == BotJobToolbarAction.CHOOSE_TRANSFER_PATH) {
            runTransferChooser(context, request, completion, lease);
        } else if (action == BotJobToolbarAction.OPEN_REPORT) {
            runReportChooser(context, completion, lease);
        } else {
            try {
                botJobToolbarExecutor.execute(
                        () -> runHeadlessToolbarAction(context, action, request, completion, lease));
            } catch (RejectedExecutionException rejected) {
                lease.close();
                completion.complete(BotJobToolbarActionResult.failure(
                        action, "Another Bot Job toolbar operation is already in progress"));
            }
        }
        return completion;
    }

    private void runHeadlessToolbarAction(
            BotJobToolbarContext context,
            BotJobToolbarAction action,
            BotJobDetailsRequest request,
            CompletableFuture<BotJobToolbarActionResult> completion,
            BotJobToolbarConcurrencyGuard.Lease lease) {
        try (lease) {
            requireNonStopActionAllowed(context);
            requireExecutionStartAllowed(action);
            switch (action) {
                case OPEN_EXCEL -> openExcelFromReact(context);
                case GENERATE_EXCEL -> generateExcelFromReact(context, request.body());
                case SET_NAVIGATION_TIME -> setNavigationTimeFromReact(request.body());
                case LAUNCH -> launchExternalEngineFromReact(context);
                case REFRESH_BLOCKS -> reloadBlocksFromReact(context);
                case TEST_RUN -> runTestRunFromReact(context, request, action, completion);
                case EXPORT_JOB -> exportJobFromReact(context, request);
                case IMPORT_JOB -> importJobFromReact(context, request);
                case CREATE_BAT -> createBatFromReact(context);
                case STOP_TEST_RUN -> throw new IllegalStateException("STOP dispatch failed");
                case OPEN_REPORT, CHOOSE_TRANSFER_PATH -> throw new IllegalStateException("Native chooser dispatch failed");
            }
            if (action != BotJobToolbarAction.TEST_RUN) {
                botJobDetailsWorkspaceRegistry.require(context.botJobId(), context.workspaceEpoch());
                botJobDetailsWorkspaceRegistry.touch(context.botJobId());
                completion.complete(BotJobToolbarActionResult.success(action, toolbarActionMessage(action)));
            }
        } catch (Exception error) {
            completeToolbarFailure(action, completion, error);
        }
    }

    private void runTransferChooser(
            BotJobToolbarContext context,
            BotJobDetailsRequest request,
            CompletableFuture<BotJobToolbarActionResult> completion,
            BotJobToolbarConcurrencyGuard.Lease lease) {
        Runnable chooser = () -> {
            try (lease) {
                requireNonStopActionAllowed(context);
                DirectoryChooser directoryChooser = new DirectoryChooser();
                directoryChooser.setTitle("Select Bot Job transfer folder");
                String configured = arPropertyManager.getProperty(ARPropertyEnum.PATH_EXPORT);
                if (!Strings.isNullOrEmpty(configured)) {
                    File initial = new File(configured);
                    if (initial.isDirectory()) directoryChooser.setInitialDirectory(initial);
                }
                File selected = directoryChooser.showDialog(stage);
                if (selected == null) {
                    completion.complete(BotJobToolbarActionResult.success(
                            BotJobToolbarAction.CHOOSE_TRANSFER_PATH, "Folder selection cancelled"));
                    return;
                }
                botJobDetailsWorkspaceRegistry.require(context.botJobId(), context.workspaceEpoch());
                String path = botJobTransferPathRegistry.select(
                        request.sessionId(), context.botJobId(), selected);
                completion.complete(BotJobToolbarActionResult.success(
                        BotJobToolbarAction.CHOOSE_TRANSFER_PATH, "Transfer folder selected", path));
            } catch (Exception error) {
                completeToolbarFailure(BotJobToolbarAction.CHOOSE_TRANSFER_PATH, completion, error);
            }
        };
        if (Platform.isFxApplicationThread()) chooser.run();
        else Platform.runLater(chooser);
    }

    private void runReportChooser(
            BotJobToolbarContext context,
            CompletableFuture<BotJobToolbarActionResult> completion,
            BotJobToolbarConcurrencyGuard.Lease lease) {
        Runnable chooser = () -> {
            try {
                requireNonStopActionAllowed(context);
                File selected = chooseReportFromReact();
                if (selected == null) {
                    lease.close();
                    completion.complete(BotJobToolbarActionResult.success(
                            BotJobToolbarAction.OPEN_REPORT, "Report selection cancelled"));
                    return;
                }
                try {
                    botJobToolbarExecutor.execute(() -> {
                        try (lease) {
                            requireNonStopActionAllowed(context);
                            botJobNativeOperations.openFile(selected);
                            completion.complete(BotJobToolbarActionResult.success(
                                    BotJobToolbarAction.OPEN_REPORT, "Report opened"));
                        } catch (Exception error) {
                            completeToolbarFailure(BotJobToolbarAction.OPEN_REPORT, completion, error);
                        }
                    });
                } catch (RejectedExecutionException rejected) {
                    lease.close();
                    completion.complete(BotJobToolbarActionResult.failure(
                            BotJobToolbarAction.OPEN_REPORT,
                            "Another Bot Job toolbar operation is already in progress"));
                }
            } catch (Exception error) {
                lease.close();
                completeToolbarFailure(BotJobToolbarAction.OPEN_REPORT, completion, error);
            }
        };
        if (Platform.isFxApplicationThread()) chooser.run();
        else Platform.runLater(chooser);
    }

    private void dispatchPromptStop(
            BotJobDetailsRequest request,
            CompletableFuture<BotJobToolbarActionResult> completion) {
        botJobTestRunCoordinator.requestStop(request.botJobId()).whenComplete((result, error) -> {
            if (error != null) {
                completeToolbarFailure(BotJobToolbarAction.STOP_TEST_RUN, completion, error);
            } else if (result.accepted()) {
                completion.complete(BotJobToolbarActionResult.success(
                        BotJobToolbarAction.STOP_TEST_RUN, result.message()));
            } else {
                completion.complete(BotJobToolbarActionResult.failure(
                        BotJobToolbarAction.STOP_TEST_RUN, result.message()));
            }
        });
    }

    private void requireNonStopActionAllowed(BotJobToolbarContext context) {
        BotJobDetailsWorkspaceRegistry.Snapshot snapshot =
                botJobDetailsWorkspaceRegistry.require(context.botJobId(), context.workspaceEpoch());
        if (BotJobDetailsWorkspaceRegistry.isExecutionActive(snapshot.executionState())) {
            throw new IllegalStateException("Stop the active TEST RUN before using another toolbar action");
        }
    }

    private void requireExecutionStartAllowed(BotJobToolbarAction action) {
        boolean conflictsWithExternalEngine = switch (action) {
            case GENERATE_EXCEL, SET_NAVIGATION_TIME, REFRESH_BLOCKS, TEST_RUN, LAUNCH, IMPORT_JOB -> true;
            default -> false;
        };
        if (conflictsWithExternalEngine && botJobToolbarGuard.externalEngineRunning()) {
            throw new IllegalStateException("An external Engine execution is already active");
        }
    }

    private static void completeToolbarFailure(
            BotJobToolbarAction action,
            CompletableFuture<BotJobToolbarActionResult> completion,
            Throwable error) {
        log.error("Bot Job toolbar action {} failed", action, error);
        String message = error == null || Strings.isNullOrEmpty(error.getMessage())
                ? "Bot Job toolbar action failed"
                : error.getMessage();
        completion.complete(BotJobToolbarActionResult.failure(action, message));
    }

    private void setNavigationTimeFromReact(JsonObject body) {
        int seconds = requiredInt(body, "navigationTimeSeconds", 0, 10);
        setNavigationTimeValue(seconds);
    }

    private void reloadBlocksFromReact(BotJobToolbarContext context) {
        ErrorMessage error = performDataBase.loadBlocks(context.botJobId(), "", "block");
        if (error != null) throw new IllegalStateException(botJobErrorText(error));
    }

    private void runTestRunFromReact(
            BotJobToolbarContext context,
            BotJobDetailsRequest request,
            BotJobToolbarAction action,
            CompletableFuture<BotJobToolbarActionResult> completion) {
        JsonObject body = request.body();
        String mode = requiredString(body, "executionMode").toUpperCase(java.util.Locale.ROOT);
        if (!"ALL".equals(mode) && !"ONE".equals(mode)) {
            throw new IllegalArgumentException("Execution mode must be ALL or ONE");
        }

        int blockId = optionalInt(body, "blockId", 0);
        boolean executeAllSelected = blockId <= 0;
        if (executeAllSelected && "ONE".equals(mode)) {
            throw new IllegalArgumentException("Select a numbered block before using ONE mode");
        }

        Integer blockOrder = null;
        String blockName = EXECUTE_ALL_OPTION_LABEL;
        if (!executeAllSelected) {
            ErrorMessage loadError = performDataBase.loadBlocks(context.botJobId(), "", "block");
            if (loadError != null) throw new IllegalStateException(botJobErrorText(loadError));
            BlockLoadDTO selectedBlock = performLists.getListBlock().stream()
                    .filter(block -> block != null
                            && block.getId() != null
                            && block.getId() == blockId
                            && context.botJobId() == block.getBotJobId())
                    .findFirst()
                    .orElseThrow(() -> new IllegalArgumentException("The selected block is no longer available"));
            blockOrder = selectedBlock.getBlockOrderNumber();
            blockName = selectedBlock.getName();
        }

        TestRunExecutionSelection selection = TestRunExecutionSelection.resolve(
                blockOrder, executeAllSelected, "ONE".equals(mode));
        BotJobTestRunCoordinator.StartResult result = botJobTestRunCoordinator.start(
                context,
                selection.blockOrderNumber(),
                selection.runSingleBlock(),
                mode,
                blockName,
                request.requestId());
        completion.complete(result.accepted()
                ? BotJobToolbarActionResult.success(action, result.message())
                : BotJobToolbarActionResult.failure(action, result.message()));
    }

    private void openExcelFromReact(BotJobToolbarContext context) throws IOException {
        botJobNativeOperations.openExcel(context);
    }

    private void generateExcelFromReact(BotJobToolbarContext context, JsonObject body) throws Exception {
        ErrorMessage error = null;
        if (performLists.getQuickBotJobs().isEmpty()) error = performDataBase.loadQuickBotJobs();
        if (error == null) error = performDataBase.loadBlocks(context.botJobId(), context.name(), "block");
        if (error == null) error = performDBEngine.loadAllActionsPerBlock(performLists.getListBlock());
        if (error != null) throw new IllegalStateException(botJobErrorText(error));

        ExtractedData extracted = ExcelUtils.isFileExists(context.name(), performLists.getAllActions());
        if (extracted != null && extracted.getErrorMessage() != null) {
            throw new IllegalStateException(extracted.getErrorMessage());
        }
        if (extracted != null && !booleanValue(body, "confirmed", false)) {
            throw new IllegalArgumentException("Confirm replacement of the existing Excel file");
        }
        new ExcelUtils().generateExcelFiles(extracted, context.name(), null, true);
    }

    private File chooseReportFromReact() {
        File reportFolder = botJobNativeOperations.reportDirectory();
        FileChooser chooser = new FileChooser();
        chooser.setTitle("Open Report File");
        chooser.setInitialDirectory(reportFolder);
        chooser.getExtensionFilters().addAll(
                new FileChooser.ExtensionFilter("Excel Files", "*.xlsx", "*.xls"),
                new FileChooser.ExtensionFilter("All Files", "*.*"));
        return chooser.showOpenDialog(stage);
    }

    private void exportJobFromReact(BotJobToolbarContext context, BotJobDetailsRequest request) {
        requireConfirmed(request.body(), "Confirm the Bot Job export");
        String path = botJobTransferPathRegistry.require(
                request.sessionId(), context.botJobId(), requiredString(request.body(), "transferPath"));
        BotJobTransferResult result = botJobTransferService.exportJob(
                context.homeBankingId(), context.botJobId(), path);
        if (!result.ok()) throw new IllegalStateException(result.message());
    }

    private void importJobFromReact(BotJobToolbarContext context, BotJobDetailsRequest request) {
        requireConfirmed(request.body(), "Confirm the Bot Job import");
        String path = botJobTransferPathRegistry.require(
                request.sessionId(), context.botJobId(), requiredString(request.body(), "transferPath"));
        String dateText = requiredString(request.body(), "restoreDate");
        LocalDate restoreDate;
        try {
            restoreDate = LocalDate.parse(dateText);
        } catch (RuntimeException invalidDate) {
            throw new IllegalArgumentException("Restore date must use YYYY-MM-DD", invalidDate);
        }
        BotJobTransferResult result = botJobTransferService.importJob(
                context.homeBankingId(),
                context.organizationName(),
                context.homeUrlId(),
                context.botJobId(),
                restoreDate,
                path);
        if (!result.ok()) throw new IllegalStateException(result.message());
    }

    private void createBatFromReact(BotJobToolbarContext context) throws IOException {
        botJobNativeOperations.createBat(context);
    }

    private void launchExternalEngineFromReact(BotJobToolbarContext context) throws IOException {
        botJobNativeOperations.launchExternalEngine(context);
    }

    private static int requiredInt(JsonObject body, String field, int minimum, int maximum) {
        int value = optionalInt(body, field, Integer.MIN_VALUE);
        if (value < minimum || value > maximum) {
            throw new IllegalArgumentException(field + " must be between " + minimum + " and " + maximum);
        }
        return value;
    }

    private static int optionalInt(JsonObject body, String field, int fallback) {
        try {
            return body == null || !body.has(field) || body.get(field).isJsonNull()
                    ? fallback
                    : body.get(field).getAsInt();
        } catch (RuntimeException invalidValue) {
            throw new IllegalArgumentException(field + " must be a whole number", invalidValue);
        }
    }

    private static boolean booleanValue(JsonObject body, String field, boolean fallback) {
        try {
            return body == null || !body.has(field) || body.get(field).isJsonNull()
                    ? fallback
                    : body.get(field).getAsBoolean();
        } catch (RuntimeException invalidValue) {
            throw new IllegalArgumentException(field + " must be true or false", invalidValue);
        }
    }

    private static void requireConfirmed(JsonObject body, String message) {
        if (!booleanValue(body, "confirmed", false)) throw new IllegalArgumentException(message);
    }

    private static String requiredString(JsonObject body, String field) {
        String value = optionalString(body, field);
        if (Strings.isNullOrEmpty(value)) throw new IllegalArgumentException(field + " is required");
        return value;
    }

    private static String optionalString(JsonObject body, String field) {
        try {
            return body == null || !body.has(field) || body.get(field).isJsonNull()
                    ? ""
                    : body.get(field).getAsString().trim();
        } catch (RuntimeException invalidValue) {
            throw new IllegalArgumentException(field + " must be text", invalidValue);
        }
    }

    private static String botJobErrorText(ErrorMessage error) {
        if (error == null) return "Bot Job operation failed";
        if (!Strings.isNullOrEmpty(error.getErrorMessage())) return error.getErrorMessage();
        if (!Strings.isNullOrEmpty(error.getErrorHeader())) return error.getErrorHeader();
        return Strings.isNullOrEmpty(error.getErrorTitle()) ? "Bot Job operation failed" : error.getErrorTitle();
    }

    private static String toolbarActionMessage(BotJobToolbarAction action) {
        return switch (action) {
            case OPEN_EXCEL -> "Excel file opened";
            case GENERATE_EXCEL -> "Excel generation started";
            case OPEN_REPORT -> "Report action completed";
            case SET_NAVIGATION_TIME -> "Navigation time updated";
            case LAUNCH -> "Bot Job launch started";
            case REFRESH_BLOCKS -> "Block list refreshed";
            case TEST_RUN -> "TEST RUN started";
            case STOP_TEST_RUN -> "TEST RUN stopped";
            case EXPORT_JOB -> "Bot Job export started";
            case IMPORT_JOB -> "Bot Job import started";
            case CHOOSE_TRANSFER_PATH -> "Transfer folder selected";
            case CREATE_BAT -> "BAT file created";
        };
    }

    /** Executes a React workspace command and completes only after the JavaFX action ran. */
    public CompletableFuture<BotJobWorkspaceActionResult> handleReactWorkspaceAction(
            BotJobWorkspaceAction action, int requestedBotJobId) {
        CompletableFuture<BotJobWorkspaceActionResult> completion = new CompletableFuture<>();
        if (action == null) {
            completion.complete(BotJobWorkspaceActionResult.failure(null, "Bot Job Details action is required"));
            return completion;
        }

        Runnable command = () -> {
            try {
                if (selectedBotJob == null
                        || selectedBotJob.getId() == null
                        || selectedBotJob.getId() != requestedBotJobId) {
                    throw new IllegalArgumentException("Bot Job Details action does not match the active Bot Job");
                }
                if (componentBox == null) {
                    throw new IllegalStateException("Bot Job Details workspace is not ready");
                }
                if ((action == BotJobWorkspaceAction.SHOW_COMPONENTS
                                || action == BotJobWorkspaceAction.HIDE_COMPONENTS)
                        && componentContainer == null) {
                    throw new IllegalStateException("Components workspace is not ready");
                }
                if (action == BotJobWorkspaceAction.SHOW_PRE_SCAN
                        && !supportsDesktopBrowserTools(selectedBotJob.getPriority())) {
                    throw new IllegalStateException("Pre Scan is unavailable for this Bot Job type");
                }
                if (action == BotJobWorkspaceAction.CLOSE && stage == null) {
                    throw new IllegalStateException("Bot Job Details window is not available");
                }
                if (action == BotJobWorkspaceAction.CLOSE && !canCloseWorkspace()) {
                    throw new IllegalStateException(
                            "Wait for the active Bot Job operation to finish or stop TEST RUN first");
                }
                if (action == BotJobWorkspaceAction.OPEN_ORGANIZATIONS
                        && isEnabledLicence
                        && !com.allinweb.ch.facade.LicenseService.getInstance().isActive()) {
                    throw new IllegalStateException("An active license is required to manage environments");
                }

                switch (action) {
                    case REFRESH -> {
                        if (!refreshGrids()) {
                            throw new IllegalStateException("Unable to refresh the Bot Job grids");
                        }
                    }
                    case SHOW_BOT_JOB, HIDE_COMPONENTS -> showBotJobWorkspace();
                    case SHOW_COMPONENTS -> showComponentsWorkspace();
                    case SHOW_PRE_SCAN -> showPreScanWorkspace();
                    case OPEN_ORGANIZATIONS -> openOrganizationManager();
                    case CLOSE -> closePane();
                }
                if (action != BotJobWorkspaceAction.CLOSE) {
                    botJobDetailsWorkspaceRegistry.updateWorkspace(
                            selectedBotJob.getId(), activeWorkspaceSurface(), componentsVisible());
                }
                completion.complete(BotJobWorkspaceActionResult.success(
                        action, workspaceActionMessage(action), activeWorkspaceSurface(), componentsVisible()));
            } catch (Exception error) {
                completion.complete(BotJobWorkspaceActionResult.failure(action, error.getMessage()));
            }
        };

        try {
            if (Platform.isFxApplicationThread()) {
                command.run();
            } else {
                Platform.runLater(command);
            }
        } catch (Exception error) {
            completion.complete(BotJobWorkspaceActionResult.failure(action, error.getMessage()));
        }
        return completion;
    }

    private void showBotJobWorkspace() {
        if (componentBox == null) return;
        componentBox.getChildren().setAll(webViewTasks);
        HBox.setHgrow(webViewTasks, Priority.ALWAYS);
        VBox.setVgrow(webViewTasks, Priority.ALWAYS);
        if (componentContainer != null) {
            componentContainer.setVisible(false);
            componentContainer.setManaged(false);
        }
        isComponentBoxVisible = false;
        isPreScannerVisible = false;
        componentBox.requestLayout();
    }

    private void reloadReactWorkspaceSurfaces() {
        String indexUrl = WebBuildExtractor.getIndexUrl();
        if (webEngineTasks != null) webEngineTasks.load(indexUrl);
        if (webEngineComp != null) webEngineComp.load(indexUrl);
        if (webEnginePreScanner != null) webEnginePreScanner.load(indexUrl);
    }

    private void suspendReactWorkspaceSurfaces(int botJobId) {
        webViewBootstrap.deactivate(botJobId);
        for (String workspaceSession : List.of("botJobTasks", "componentTasks", "preScannerGrid")) {
            WebSocketSessionManager.closeSession(workspaceSession);
            botJobTransferPathRegistry.clear(workspaceSession, botJobId);
        }
        runOnFxThread(() -> {
            suspendReactWorkspaceSurface(webEngineTasks);
            suspendReactWorkspaceSurface(webEngineComp);
            suspendReactWorkspaceSurface(webEnginePreScanner);
        });
    }

    private void suspendReactWorkspaceSurface(WebEngine webEngine) {
        if (webEngine == null) return;
        cancelPendingWebViewBootstrap(webEngine);
        webEngine.getLoadWorker().cancel();
        webEngine.load("about:blank");
    }

    private void detachReactWorkspaceLoadListeners() {
        runOnFxThread(() -> {
            for (Map.Entry<WebEngine, ChangeListener<Worker.State>> entry :
                    new ArrayList<>(webViewLoadListeners.entrySet())) {
                entry.getKey().getLoadWorker().stateProperty().removeListener(entry.getValue());
                cancelPendingWebViewBootstrap(entry.getKey());
            }
            webViewLoadListeners.clear();
            pendingWebViewBootstraps.clear();
        });
    }

    private void runOnFxThread(Runnable operation) {
        if (Platform.isFxApplicationThread()) {
            operation.run();
            return;
        }
        try {
            Platform.runLater(operation);
        } catch (IllegalStateException error) {
            log.debug("JavaFX runtime is unavailable while retiring Bot Job WebViews: {}", error.getMessage());
        }
    }

    private void showComponentsWorkspace() {
        if (componentContainer == null || componentsVisible()) return;
        componentBox.getChildren().setAll(webViewTasks, componentContainer);
        HBox.setHgrow(webViewTasks, Priority.ALWAYS);
        componentContainer.setVisible(true);
        componentContainer.setManaged(true);
        isComponentBoxVisible = true;
        isPreScannerVisible = false;
        componentBox.requestLayout();
    }

    private void showPreScanWorkspace() {
        if (componentBox == null || componentBox.getChildren().contains(webViewPreScanner)) return;
        componentBox.getChildren().setAll(webViewPreScanner);
        HBox.setHgrow(webViewPreScanner, Priority.ALWAYS);
        VBox.setVgrow(webViewPreScanner, Priority.ALWAYS);
        if (componentContainer != null) {
            componentContainer.setVisible(false);
            componentContainer.setManaged(false);
        }
        isComponentBoxVisible = false;
        isPreScannerVisible = true;
        componentBox.requestLayout();
    }

    private void openOrganizationManager() {
        if (stage == null) {
            throw new IllegalStateException("Bot Job Details window is not available");
        }
        organizationManagerScene.showModal(stage);
    }

    /** Applies persisted React metadata to the active desktop execution context on the FX thread. */
    public CompletableFuture<Void> applyReactMetadataState(BotJobDetailsState state) {
        CompletableFuture<Void> completion = new CompletableFuture<>();
        Runnable apply = () -> {
            try {
                if (state == null
                        || selectedBotJob == null
                        || selectedBotJob.getId() == null
                        || selectedBotJob.getId() != state.botJobId()) {
                    throw new IllegalArgumentException("Metadata does not match the active Bot Job");
                }
                selectedBotJob.setName(state.name());
                selectedBotJob.setDescription(state.description());
                selectedBotJob.setHomeUrlId(state.homeUrlId());
                reactEnvironmentUrl = state.environmentUrl();
                if (stage != null) {
                    stage.setTitle("Bot Job Details WebSite Id: " + state.homeBankingId()
                            + " Id: " + state.botJobId());
                }
                completion.complete(null);
            } catch (RuntimeException error) {
                completion.completeExceptionally(error);
            }
        };
        if (Platform.isFxApplicationThread()) {
            apply.run();
        } else {
            Platform.runLater(apply);
        }
        return completion;
    }

    private boolean componentsVisible() {
        return componentBox != null
                && componentContainer != null
                && componentBox.getChildren().contains(componentContainer);
    }

    private String activeWorkspaceSurface() {
        if (componentBox != null && componentBox.getChildren().contains(webViewPreScanner)) return "preScan";
        if (componentsVisible()) return "components";
        return "botJob";
    }

    private static String workspaceActionMessage(BotJobWorkspaceAction action) {
        return switch (action) {
            case REFRESH -> "Bot Job grids refreshed";
            case SHOW_BOT_JOB -> "Bot Job workspace opened";
            case SHOW_COMPONENTS -> "Components workspace opened";
            case HIDE_COMPONENTS -> "Components workspace hidden";
            case SHOW_PRE_SCAN -> "Pre Scan workspace opened";
            case OPEN_ORGANIZATIONS -> "Organizations opened";
            case CLOSE -> "Bot Job Details closed";
        };
    }

    public void destroy() {
        if (selectedBotJob != null && selectedBotJob.getId() != null) {
            suspendReactWorkspaceSurfaces(selectedBotJob.getId());
        }
        detachReactWorkspaceLoadListeners();
        clearPane(getPaneReference());
        pane = null;
        scene = null;
        instance = null;
    }

    private void setPayloadEmpty(String destination) {
        int blockId = -1;
        String blockName = "1# Default Block";
        if (destination.equalsIgnoreCase("botJobTasks")) {
            if (!performLists.getListBotJob().isEmpty()
                    && performLists.getListBlock().isEmpty()) {
                ErrorMessage errorMessage = performDataBase.loadBlocks(selectedBotJob.getId(), "", "block");
                if (errorMessage != null) {
                    performMessage.errorMessageOperationFailed(errorMessage);
                }
            }
            if (selectedBotJob.getBlockId() == null
                    && !performLists.getListBlock().isEmpty()) {
                blockId = performLists.getListBlock().get(0).getId();
                blockName = performLists.getListBlock().get(0).getName();
            }
        } else if (destination.equalsIgnoreCase("componentTasks")) {
            if (!performLists.getListBotJobComp().isEmpty()
                    && performLists.getListBlockComp().isEmpty()) {
                ErrorMessage errorMessage =
                        performDataBase.loadBlocks(selectedBotJob.getHomeBankingId(), "", "component_block");

                if (errorMessage != null) {
                    performMessage.errorMessageOperationFailed(errorMessage);
                }
            }

            if (selectedBotJob.getBlockId() == null
                    && !performLists.getListBlockComp().isEmpty()) {
                blockId = performLists.getListBlockComp().get(0).getId();
                blockName = performLists.getListBlockComp().get(0).getName();
            }
        }

        this.payloadEmpty = new PayloadJson(selectedBotJob.getId(), blockId, blockName, 0);
    }

    private boolean checkLicense() {
        try {
            String licensePath = arPropertyManager.getProperty(ARPropertyEnum.PATH_LICENSE);
            if (Strings.isNullOrEmpty(licensePath)) {
                licensePath = System.getProperty("user.dir");
            }

            LicenceVal licenseStatus = LicenseManager.checkLicenseFile(licensePath);

            String msgValid = "The license file is valid and the application is authorized for use.";
            String msgNextStep = "You can now proceed with normal application usage.";

            String msgColor = "#0277BD";
            if (!licenseStatus.equals(LicenceVal.VALID)) {
                msgValid = "The license file is not valid and the application is not authorized for use.";
                msgNextStep = "Application access is restricted. Please obtain a valid license to continue.";
                msgColor = "#C62828"; // Soft, elegant red tone

                performMessage.showCustomModalDialogDragWin11(
                        "License Status Verification",
                        "<span style='color: #2E7D32; font-weight: bold; font-size: 1.1em;'>License status has been successfully verified.</span>",
                        "<span style='color: " + msgColor + "; font-weight: bold;'>" + msgValid + "</span>",
                        "<span style='font-style: italic;'>" + msgNextStep + "</span>",
                        "<span style='color: #E65100; font-weight: bold;'>Current license status:</span> <span style='font-weight: bold;'>"
                                + licenseStatus.getStaus() + "</span>",
                        false,
                        "OK",
                        null,
                        0);
                return false;
            }
            return true;
        } catch (Exception error) {

            log.error("Cannot read/validate the License path/file. Error: " + error.getMessage());
            return false;
        }
    }

    // Allow the stage to be set from outside when pane is shown
    public void setStage(Stage stage) {
        this.stage = stage;
    }

    // 🔹 Method to close the window
    private void closePane() {
        if (!Platform.isFxApplicationThread()) {
            throw new IllegalStateException("Bot Job Details close must run on the JavaFX thread");
        }
        Stage currentStage = this.stage;
        if (currentStage == null) {
            throw new IllegalStateException("Bot Job Details window is not available");
        }
        if (!canCloseWorkspace()) {
            throw new IllegalStateException(
                    "Wait for the active Bot Job operation to finish or stop TEST RUN first");
        }
        markWorkspaceClosed();
        currentStage.close();
    }

    public void markWorkspaceClosed() {
        workspaceCloseCoordinator.close(
                selectedBotJob == null ? null : selectedBotJob.getId());
    }

    public boolean canCloseWorkspace() {
        return workspaceCloseCoordinator.canClose(
                selectedBotJob == null ? null : selectedBotJob.getId());
    }

    private boolean isWebApp(String priority) {
        return priority == null
                || priority.trim().isEmpty()
                || ARPropertyEnum.WEB_APP.getValue().equalsIgnoreCase(priority);
    }

    private boolean supportsDesktopBrowserTools(String priority) {
        return isWebApp(priority) || "Rest Api".equalsIgnoreCase(priority == null ? "" : priority.trim());
    }

}
