// Source code is unavailable, and was generated by the Fernflower decompiler.
package com.allinweb.ch.component.pane;

import com.allinweb.ch.component.listCell.ARCellFactory;
import com.allinweb.ch.component.listCell.ComponentListCell;
import com.allinweb.ch.component.model.BlockLoadDTO;
import com.allinweb.ch.component.model.BotJobLoadDTO;
import com.allinweb.ch.component.model.HomeBankingLoadDTO;
import com.allinweb.ch.component.model.InstructionDTO;
import com.allinweb.ch.component.model.InstructionLoadDTO;
import com.allinweb.ch.component.model.PayloadJson;
import com.allinweb.ch.component.model.VariableUserDTO;
import com.allinweb.ch.component.pane.base.ARPane;
import com.allinweb.ch.component.scene.*;
import com.allinweb.ch.component.scene.base.ARScene;
import com.allinweb.ch.control.ARComponentBuilder;
import com.allinweb.ch.core.ARSharedResources;
import com.allinweb.ch.driver.ARWebDriver;
import com.allinweb.ch.facade.PerformDataBase;
import com.allinweb.ch.facade.PerformMessage;
import com.allinweb.ch.persistence.BlockDTO;
import com.allinweb.ch.persistence.ComponentBlockDTO;
import com.allinweb.ch.persistence.ComponentInstructionDTO;
import com.allinweb.ch.socket.SimpleWebSocketServer;
import com.allinweb.ch.util.ARConstants;
import com.allinweb.ch.util.ARLogger;
import com.allinweb.ch.util.ARPropertyEnum;
import com.allinweb.ch.util.ARPropertyManager;
import com.allinweb.ch.util.ComboBoxVars;
import com.allinweb.ch.util.ExcelUtils;
import com.allinweb.ch.util.ExtractedData;
import com.google.gson.Gson;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.net.ServerSocket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javafx.animation.KeyFrame;
import javafx.animation.Timeline;
import javafx.application.Platform;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.concurrent.Task;
import javafx.concurrent.Worker;
import javafx.geometry.HPos;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.*;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.control.TextField;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.FontPosture;
import javafx.scene.text.FontWeight;
import javafx.scene.text.Text;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javafx.stage.Modality;
import javafx.stage.Stage;
import javafx.util.Duration;
import javax.websocket.Session;
import javax.websocket.server.ServerContainer;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.servlet.ServletContextHandler;
import org.eclipse.jetty.websocket.jsr356.server.deploy.WebSocketServerContainerInitializer;

public class ARViewBotJobPane extends ARPane {

    // Set to hold all active WebSocket sessions
    private static Map<String, Session> activeSessions;
    private String sessionId;

    private static final String CONNECTION_TYPE = "jdbc:ucanaccess://";
    private static final String CONNECTION_PARAMETERS = ";memory=false;newDatabaseVersion=V2010";

    // Postgres
    private static boolean POSTGRES_DB = false;

    private Connection conn = null;
    private ObservableList<VariableUserDTO> variablesList;

    private ObservableList<ComboBoxVars> webPageItems;

    private static final ARComponentBuilder builder = new ARComponentBuilder();
    private BotJobLoadDTO botJobLoad;
    private List<BotJobLoadDTO> botJobLoadList = new ArrayList<>();
    private ObservableList<BlockDTO> blockDTOObservableList;
    private ListView<BlockDTO> uiBlockList;

    //    private static final SimpleWebSocketServer simpleWebSocketServer;
    private static final PerformMessage performMessage;
    private static final PerformDataBase performDataBase;
    private static final ARScannedElementScene arScannedElementScene;

    // Static block to initialize
    static {
        //        simpleWebSocketServer = SimpleWebSocketServer.getInstance();
        performMessage = PerformMessage.getInstance();
        performDataBase = PerformDataBase.getInstance();
        arScannedElementScene = ARScannedElementScene.getInstance();
    }

    private SimpleBooleanProperty isEditingBotJob = new SimpleBooleanProperty(false);
    // Define a flag to prevent double clicks
    private boolean isScannerButtonClicked = false;

    Button refreshButton;
    Button openScannerButton;
    Button editBotJobButton;
    Button launchBotJobButton;
    Button saveBotJobButton;
    //    Button saveAsBotJobButton;
    Button printBotJobButton;
    Button openExcelFileButton;
    Button generateExcelButton;
    Button openExcelFilterPanelButton;
    Button closeBotJobButton;

    Label botJobNameLabel;
    Label botJobDescriptionLabel;
    private TextField botJobName;
    private TextField botJobDescription;
    VBox botJobContainer;

    ListView<ComponentBlockDTO> componentList;

    private static final int SECONDS = 3; // Total seconds for the countdown
    private int remainingSeconds = SECONDS;
    private Timeline timeline;
    private ExecutorService executorService;
    private Alert alertToShow;
    private Server jettyServer;
    private ServerContainer wsContainer;

    Button componentButton;
    private VBox componentContainer;
    boolean isComponentBoxVisible;

    private WebView webView = new WebView();
    private WebEngine webEngine;
    private HBox componentBox;

    private ARScene arScene;

    public ARViewBotJobPane(BotJobLoadDTO botJobLoad, ARScene arScene) {
        this.arScene = arScene;
        this.botJobLoad = botJobLoad;
        // Initialize database IF IS ACCESS TO BE USED
        variablesList = FXCollections.observableArrayList();
        webPageItems = FXCollections.observableArrayList();

        String dataBaseType = ARPropertyManager.getInstance().getProperty(ARPropertyEnum.DATABASE_TYPE);

        if (dataBaseType != null && dataBaseType.equalsIgnoreCase("POSTGRES")) {
            POSTGRES_DB = true;
        } else {
            POSTGRES_DB = false;
        }

        if (!POSTGRES_DB) {
            initializeDatabase();
        }

        Platform.runLater(() -> this.variablesList = performDataBase.loadJobVariables(this.botJobLoad.getId()));
        Platform.runLater(() -> this.webPageItems = performDataBase.loadWebPageFields(this.botJobLoad.getId()));
    }

    public void initUIComponents() {
        int port = 8080;

        String portSocket = ARPropertyManager.getInstance().getProperty(ARPropertyEnum.PORT_SOCKET);
        if (portSocket != null) {
            port = Integer.parseInt(portSocket);
        }

        // Start WebSocket server in a background thread
        int finalPort = port;
        new Thread(() -> {
                    try {
                        startWebSocketServer(finalPort);
                    } catch (Exception e) {
                        ARLogger.getInstance(ARWebDriver.class).fine("Port already in Use: " + finalPort);

                        Alert alert = new Alert(AlertType.ERROR);
                        alert.setTitle("Port Error");
                        alert.setHeaderText("Change the Port configuration\"");
                        alert.setContentText(String.format("Port %d already in Use!", finalPort));
                        alert.showAndWait();

                        //                        Stage stage = (Stage) ((Button) .getSource()).getScene().getWindow();
                        //                        stage.close();
                        return;
                    }
                })
                .start();
        buidUIComponents(finalPort);
    }

    public void startWebSocketServer(int port) throws Exception {
        // Check if the port is available
        if (isPortInUse(port)) {
            throw new Exception("Port " + port + " is already in use.");
        }

        // Set up Jetty server to run WebSocket endpoint
        jettyServer = new Server(port); // Server listens on port 8080
        ServletContextHandler context = new ServletContextHandler(ServletContextHandler.SESSIONS);
        context.setContextPath("/");
        jettyServer.setHandler(context);

        // Initialize WebSocket container
        wsContainer = WebSocketServerContainerInitializer.configureContext(context);
        //        wsContainer.setDefaultMaxSessionIdleTimeout(600000);
        //        wsContainer.addEndpoint(WebSocketStompServer.class);
        wsContainer.addEndpoint(SimpleWebSocketServer.class); // Register SimpleWebSocketServer

        // Start Jetty server
        jettyServer.start();
        System.out.println("WebSocket server started at ws://localhost:" + port + "/websocket");

        // Example: Retrieve all active sessions
        activeSessions = SimpleWebSocketServer.getAllSessions();
        System.out.println("Active WebSocket sessions: " + activeSessions.size());
    }

    // Method to check if the port is already in use
    private boolean isPortInUse(int port) {
        try (ServerSocket serverSocket = new ServerSocket(port)) {
            return false; // Port is available
        } catch (IOException e) {
            return true; // Port is already in use
        }
    }

    public void stopWebSocketServer() {
        if (jettyServer != null && jettyServer.isStarted()) {
            try {
                jettyServer.stop();
            } catch (Exception e) {
                ARLogger.getInstance(ARViewBotJobPane.class).severe("stopWebSocketServer  \nError: " + e.getMessage());
            }
            jettyServer.destroy();
            ARLogger.getInstance(ARViewBotJobPane.class).info("WebSocket server stopped.");
            //            System.out.println("WebSocket server stopped.");
        }
    }

    public void buidUIComponents(int finalPort) {

        // Create a label to display the countdown
        Label countdownLabel = new Label(String.valueOf(remainingSeconds));
        countdownLabel.setStyle("-fx-font-size: 24px;");
        countdownLabel.setVisible(false);
        // Create a stack pane to hold the label
        StackPane stackPane = new StackPane(countdownLabel);
        stackPane.setPadding(new Insets(20));
        // Create a dialog for the alert
        alertToShow = new Alert(AlertType.INFORMATION);
        alertToShow.setTitle("Countdown Alert");
        alertToShow.setHeaderText("Count Down");
        alertToShow.initModality(Modality.APPLICATION_MODAL);
        // Set the content of the alert
        alertToShow.getDialogPane().setContent(stackPane);
        // Create a timeline to update the countdown
        timeline = new Timeline(new KeyFrame(Duration.seconds(1), event -> {
            remainingSeconds--;
            countdownLabel.setText(String.valueOf(remainingSeconds));
            if (remainingSeconds <= 0) {
                timeline.stop(); // Stop the timeline when countdown finishes
                alertToShow.close(); // Close the alert dialog
            }
        }));

        this.refreshButton = builder.buildButton(
                "Refresh", ARConstants.SPACE_ZERO, "/refresh.png", ARConstants.SPACE_M, new Insets(5.0D));
        this.openScannerButton = builder.buildButton(
                "Scan", ARConstants.SPACE_ZERO, "/open_browser.png", ARConstants.SPACE_M, new Insets(5.0D));
        this.editBotJobButton = builder.buildButton(
                "Edit Job", ARConstants.SPACE_ZERO, "/edit.png", ARConstants.SPACE_M, new Insets(5.0D));

        this.launchBotJobButton = builder.buildButton(
                "Launch", ARConstants.SPACE_ZERO, "/play.png", ARConstants.SPACE_M, new Insets(5.0D));
        this.saveBotJobButton = builder.buildButton(
                "Save Job ", ARConstants.SPACE_ZERO, ARConstants.ICON_SAVE, ARConstants.SPACE_M, new Insets(5.0D));
        this.saveBotJobButton.setDisable(true);

        //        this.saveAsBotJobButton = builder.buildButton(
        //                "Save As", ARConstants.SPACE_ZERO, ARConstants.ICON_SAVE, ARConstants.SPACE_M, new
        // Insets(5.0D));
        this.printBotJobButton = builder.buildButton(
                "Print", ARConstants.SPACE_ZERO, ARConstants.ICON_PRINT, ARConstants.SPACE_M, new Insets(5.0D));
        this.openExcelFileButton = builder.buildButton(
                "Excel File", ARConstants.SPACE_ZERO, ARConstants.ICON_EXCEL, ARConstants.SPACE_M, new Insets(5.0D));
        this.generateExcelButton = builder.buildButton(
                "Generate", ARConstants.SPACE_ZERO, ARConstants.ICON_EXCEL, ARConstants.SPACE_M, new Insets(5.0D));
        this.openExcelFilterPanelButton = builder.buildButton(
                "Filter", ARConstants.SPACE_ZERO, ARConstants.ICON_LIST, ARConstants.SPACE_M, new Insets(5.0D));
        this.closeBotJobButton = builder.buildButton(
                "Close", ARConstants.SPACE_ZERO, ARConstants.ICON_CROSS, ARConstants.SPACE_M, new Insets(5.0D));

        // Create a GridPane for the left side buttons
        GridPane leftGridPane = new GridPane();
        leftGridPane.setVgap(10); // Vertical spacing between elements
        leftGridPane.setHgap(10); // Horizontal spacing between elements

        // Define a uniform width for the buttons
        double buttonWidth = 100;

        // Add the top row of buttons
        refreshButton.setPrefWidth(buttonWidth);
        leftGridPane.add(refreshButton, 0, 0);

        openScannerButton.setPrefWidth(buttonWidth);
        leftGridPane.add(openScannerButton, 1, 0);

        saveBotJobButton.setPrefWidth(buttonWidth);
        leftGridPane.add(saveBotJobButton, 2, 0);

        //        saveAsBotJobButton.setPrefWidth(buttonWidth);
        //        leftGridPane.add(saveAsBotJobButton, 3, 0);

        editBotJobButton.setPrefWidth(buttonWidth);
        leftGridPane.add(editBotJobButton, 3, 0);

        launchBotJobButton.setPrefWidth(buttonWidth);
        leftGridPane.add(launchBotJobButton, 4, 0);

        // Add the bottom row of buttons
        //        saveBotJobButton.setPrefWidth(buttonWidth);
        //        leftGridPane.add(saveBotJobButton, 0, 1);

        //        saveAsBotJobButton.setPrefWidth(buttonWidth);
        //        leftGridPane.add(saveAsBotJobButton, 1, 1);

        openExcelFileButton.setPrefWidth(buttonWidth);
        leftGridPane.add(openExcelFileButton, 2, 1);

        generateExcelButton.setPrefWidth(buttonWidth);
        leftGridPane.add(generateExcelButton, 3, 1);

        openExcelFilterPanelButton.setPrefWidth(buttonWidth);
        leftGridPane.add(openExcelFilterPanelButton, 4, 1);

        closeBotJobButton.setPrefWidth(buttonWidth);
        leftGridPane.add(closeBotJobButton, 5, 1);

        // Center the buttons
        for (Node node : leftGridPane.getChildren()) {
            GridPane.setHalignment(node, HPos.CENTER);
        }

        // Other UI components

        double botJobNameWidth = 200;

        this.botJobNameLabel = new Label(this.botJobLoad.getName());
        this.botJobNameLabel.setPrefWidth(botJobNameWidth);
        this.botJobName = new TextField(this.botJobLoad.getName());
        this.botJobName.setPrefWidth(botJobNameWidth);

        this.initComponentUI();

        StackPane botJobNameGroup =
                new StackPane(new Node[] {this.botJobNameLabel, this.botJobName, this.componentButton});
        StackPane.setAlignment(this.componentButton, Pos.CENTER_RIGHT);
        StackPane.setMargin(this.componentButton, new Insets(5.0D, 0.0D, 0.0D, 0.0D));

        this.botJobDescriptionLabel = new Label(this.botJobLoad.getDescription());
        this.botJobDescriptionLabel.setPrefWidth(botJobNameWidth);
        this.botJobDescription = new TextField(this.botJobLoad.getDescription());
        this.botJobDescription.setPrefWidth(botJobNameWidth);

        StackPane botJobDescriptionGroup =
                new StackPane(new Node[] {this.botJobDescriptionLabel, this.botJobDescription});

        //        this.blockDTOObservableList = FXCollections.observableArrayList(ARSharedResources.getInstance()
        //                .getEntityList(BlockDTO.class, blockDTO -> blockDTO.getBotJob().getId() ==
        // this.botJobLoad.getId()));

        // Send a message to all connected clients after 5 seconds
        //        WebSocketStompServer.sendMessageToAll(jsonData);
        List<InstructionDTO> listForDeletion =
                performDataBase.getBlockLoopInstructionIdsWithNullBlock(this.botJobLoad.getId());
        for (InstructionDTO instruction : listForDeletion) {
            performDataBase.deleteInstruction(this.botJobLoad.getId(), instruction);
        }
        performDataBase.deleteNullBlocks(this.botJobLoad.getId());
        performDataBase.updateBlockOrderNumber(performDataBase.selectAllBlocks(this.botJobLoad.getId()), true);

        this.botJobLoadList = performDataBase.loadBotJobComplete(this.botJobLoad.getId());
        Gson gson = new Gson();
        String jsonData = "";

        // Load blocks based on the BotJobLoadDTO instead of blockDTOObservableList

        if (this.botJobLoadList.size() > 0) {
            createExcelDataFile();

            List<InstructionLoadDTO> blockLoopInstructions = performDataBase.buildJsonViewData(botJobLoadList);

            performMessage.outputJson(blockLoopInstructions);

            jsonData = gson.toJson(blockLoopInstructions);

        } else {

            BotJobLoadDTO botJobDTO = new BotJobLoadDTO();
            botJobDTO.setId(this.botJobLoad.getId());
            botJobDTO.setName(this.botJobLoad.getName());
            botJobDTO.setBlockLoadDTOList(new ArrayList<>());
            this.botJobLoadList.add(botJobDTO);

            createExcelDataFile();

            PayloadJson payload = new PayloadJson(this.botJobLoad.getId(), this.botJobLoad.getName(), 0);
            // Convert the object to JSON using Gson
            jsonData = gson.toJson(payload);
        }

        webEngine = webView.getEngine();
        webEngine.javaScriptEnabledProperty().set(true);

        // (SENDER: insertTool) -> botJobTasks
        sessionId = "botJobTasks";
        buildWebView(jsonData, finalPort, sessionId);

        componentBox = new HBox(new Node[] {this.webView});

        // Prevent componentContainer from growing too much
        HBox.setHgrow(this.componentContainer, Priority.NEVER);

        // Create botJobContainer AFTER defining compBox
        this.botJobContainer =
                new VBox(new Node[] {leftGridPane, botJobNameGroup, botJobDescriptionGroup, componentBox});

        // Allow botJobContainer to grow vertically as well
        // Ensure botJobContainer and webView grow properly
        VBox.setVgrow(this.botJobContainer, Priority.ALWAYS);
        HBox.setHgrow(this.webView, Priority.ALWAYS);
        VBox.setVgrow(this.webView, Priority.ALWAYS);

        VBox.setVgrow(this.componentBox, Priority.ALWAYS);
        HBox.setHgrow(this.componentBox, Priority.ALWAYS);

        this.botJobContainer =
                new VBox(new Node[] {leftGridPane, botJobNameGroup, botJobDescriptionGroup, componentBox});
        // Main container that holds everything
        //        this.botJobContainer = new VBox(leftGridPane, botJobNameGroup, botJobDescriptionGroup, compBox);

        AnchorPane.setTopAnchor(this.botJobContainer, ARConstants.SPACE_M);
        AnchorPane.setBottomAnchor(this.botJobContainer, ARConstants.SPACE_M);
        AnchorPane.setLeftAnchor(this.botJobContainer, ARConstants.SPACE_M);
        AnchorPane.setRightAnchor(this.botJobContainer, ARConstants.SPACE_M);

        // Add the stylesheet to the scene
        //        mainGridPane.getStylesheets().add(css);

    }

    private void createExcelDataFile() {

        // Retrieve the updated BotJobDTO
        //        BotJobDTO botJobUpdated = (BotJobDTO) ARSharedResources.getInstance().getEntityById(BotJobDTO.class,
        // botJobId);

        if (this.botJobLoadList.size() > 0) {

            List<BlockLoadDTO> blocksLoaded = botJobLoadList.get(0).getBlockLoadDTOList();

            List<String> allActions = performDataBase.loadAllActionsPerBlock(blocksLoaded);

            String excelFolderPath = ARPropertyManager.getInstance().getProperty(ARPropertyEnum.FOLDER_PATH_EXCEL);
            String fileName = String.format("%s/%s%s", excelFolderPath, botJobName, ARConstants.FILE_FORMAT_EXCEL);

            // Create a File object
            File fileCheck = new File(fileName);
            if (!fileCheck.exists() && !fileCheck.isDirectory()) {

                // Check if the Excel file already exists
                ExtractedData extractedData =
                        ExcelUtils.isFileExists(botJobLoadList.get(0).getName(), allActions);

                if (extractedData == null
                        || (extractedData.getErrorTitle() != null
                                && !extractedData.getErrorTitle().contains("No Actions Provided"))) {

                    // Create a task for generating the Excel file
                    Task<Void> excelTask = new Task<>() {
                        @Override
                        protected Void call() throws Exception {
                            new ExcelUtils().generateExcelFiles(botJobLoadList, allActions, extractedData, false);
                            return null;
                        }
                    };

                    new Thread(excelTask).start();
                }
            }
        } else {

            Text variableText1Styled = new Text("Not Able to Create a Excel File");
            variableText1Styled.setStyle("-fx-font-size: 18px; -fx-fill: red;");

            VBox combinedTextContainer = new VBox();
            combinedTextContainer.setSpacing(5); // Add some sp

            combinedTextContainer.getChildren().add(variableText1Styled);

            performMessage.showAlertCombinedVBOX(
                    Alert.AlertType.WARNING, "Not Bot Job", "Bot-Job List is empty!", null, combinedTextContainer);
        }
    }

    private void buildWebView(String jsonData, int finalPort, String sessionIdFromJava) {
        webEngine.load(getClass().getResource("/build/index.html").toExternalForm());

        webEngine.getLoadWorker().stateProperty().addListener((obs, oldState, newState) -> {
            if (newState == Worker.State.SUCCEEDED) {
                // After the page has successfully loaded
                try {
                    webEngine.executeScript("setTimeout(function() { window.receiveDataFromJava(JSON.stringify("
                            + jsonData + "), " + finalPort + ", '" + sessionIdFromJava + "' ) }, 1000)");
                } catch (Exception e) {
                    ARLogger.getInstance(ARViewBotJobPane.class).severe("buildWebView  \nError: " + e.getMessage());
                }
            }
        });
    }

    public void initUIBehaviour() {
        refreshButton.setOnMouseClicked(e -> {
            stopWebSocketServer();
            Stage stage = (Stage) ((Button) e.getSource()).getScene().getWindow();
            stage.close();

            new ARViewBotJobScene(this.botJobLoad).show();
        });
        //        saveAsBotJobButton.setOnMouseClicked(e -> new ARSaveBotJobAsScene(this.botJobLoad.getId()).show());
        this.botJobNameLabel.visibleProperty().bind(this.isEditingBotJob.not());
        this.botJobDescriptionLabel.visibleProperty().bind(this.isEditingBotJob.not());
        this.botJobName.visibleProperty().bind(this.isEditingBotJob);
        this.botJobDescription.visibleProperty().bind(this.isEditingBotJob);
        this.editBotJobButton.setOnMouseClicked((e) -> {
            this.isEditingBotJob.set(this.isEditingBotJob.not().getValue());
            this.saveBotJobButton.setDisable(this.isEditingBotJob.not().getValue());
        });
        this.saveBotJobButton.setOnMouseClicked((e) -> {
            this.isEditingBotJob.set(false);
            this.isEditingBotJob.set(false);
            this.botJobNameLabel.setText(this.botJobName.getText());
            this.botJobDescriptionLabel.setText(this.botJobDescription.getText());
            this.botJobLoad.setName(this.botJobNameLabel.getText());
            this.botJobLoad.setDescription(this.botJobDescriptionLabel.getText());
            this.saveBotJobButton.setDisable(true);

            boolean botJobUpdate = performDataBase.updateBotJobNme(
                    this.botJobLoad.getId(), botJobName.getText(), botJobDescription.getText());

            //            ARSharedResources.getInstance().updateEntity(this.botJobLoad, BotJobDTO.class);

            ARSharedResources.getInstance().changeDbConnection();

            Text variableText1Styled = new Text(String.format("Bot Job \"%s\" Updated", this.botJobLoad.getName()));
            variableText1Styled.setStyle("-fx-font-size: 18px; -fx-fill: blue;");

            if (!botJobUpdate) {
                variableText1Styled = new Text(String.format("Bot Job \"%s\" NOT Updated!", this.botJobLoad.getName()));
                variableText1Styled.setStyle("-fx-font-size: 18px; -fx-fill: red;");
            }

            VBox combinedTextContainer = new VBox();
            combinedTextContainer.setSpacing(5); // Add some sp

            combinedTextContainer.getChildren().add(variableText1Styled);

            performMessage.showAlertCombinedVBOX(
                    botJobUpdate ? Alert.AlertType.INFORMATION : Alert.AlertType.WARNING,
                    "Update Bot-Job",
                    botJobUpdate ? "Bot-Job Updated successfully!" : "Bot-Job NOT Update!\"",
                    null,
                    combinedTextContainer);
        });
        this.openScannerButton.setOnMouseClicked((e) -> {
            if (!isScannerButtonClicked) { // Check if the button action was not already triggered
                isScannerButtonClicked = true; // Set the flag to prevent further clicks

                ARLogger.getInstance(ARWebDriver.class).fine("Calling openScannerButton");

                arScene.startNewThread(() -> {
                    executeScannerTask();
                    isScannerButtonClicked = false; // Reset the flag after task completes
                });
            }
        });

        this.generateExcelButton.setOnMouseClicked((e) -> {
            // Cache entities from the database
            //            ARSharedResources.getInstance().changeDbConnection();

            this.botJobLoadList = performDataBase.loadBotJobAndBlocks(this.botJobLoad.getId());

            // Retrieve the updated BotJobDTO
            //            BotJobDTO botJobUpdated = (BotJobDTO)
            //                    ARSharedResources.getInstance().getEntityById(BotJobDTO.class,
            // this.botJobLoad.getId());

            //            List<BlockLoadDTO> blockList = this.botJobLoad.getBlockLoadDTOList();

            //            boolean hasInputFields = blockList.stream()
            //                    .flatMap(
            //                            block -> block
            //                                    .getBlockLoopInstructionDTOS()
            //                                    .stream()) // Flatten all BlockLoopInstructionDTOs from each block
            //                    .anyMatch(instruction -> instruction.getActions() != null
            //                            && instruction.getActions().startsWith("I:"));

            Text variableText1Styled =
                    new Text("File name: " + this.botJobLoad.getName() + ARConstants.FILE_FORMAT_EXCEL);
            variableText1Styled.setStyle("-fx-font-size: 18px; -fx-fill: green;");

            VBox combinedTextContainer = new VBox();
            combinedTextContainer.setSpacing(5); // Add some sp

            //            if (!hasInputFields) {
            //                Text variableText2Styled = new Text("Use Web Scanner Tool First to create the:");
            //                variableText2Styled.setStyle("-fx-font-size: 18px; -fx-fill: red;");
            //
            //                variableText1Styled =
            //                        new Text("Excel Data File: " + this.botJobLoad.getName() +
            // ARConstants.FILE_FORMAT_EXCEL);
            //                variableText1Styled.setStyle("-fx-font-size: 18px; -fx-fill: blue;");
            //
            //                combinedTextContainer.getChildren().addAll(variableText2Styled, variableText1Styled);
            //
            //                performMessage.showAlertCombinedVBOX(
            //                        AlertType.ERROR,
            //                        "Error: No \"INPUT\" Web Elements",
            //                        "Error: Don't Have Any Web Element as INPUT", // No header text
            //                        null,
            //                        combinedTextContainer);
            //                return;
            //            }

            // Create an HBox to hold the individual text elements

            combinedTextContainer.getChildren().add(variableText1Styled);

            if (botJobLoadList.size() > 0) {

                List<BlockLoadDTO> blocksLoaded = botJobLoadList.get(0).getBlockLoadDTOList();

                List<String> allActions = performDataBase.loadAllActionsPerBlock(blocksLoaded);

                // Check if the Excel file already exists
                ExtractedData extractedData = ExcelUtils.isFileExists(this.botJobLoad.getName(), allActions);

                if (extractedData.getErrorMessage() != null) {

                    performMessage.errorMessage(
                            "Excel Error",
                            "Could Not Execute Excel File",
                            extractedData.getErrorMessage(),
                            null,
                            null,
                            0);

                    return;
                }

                // Create a task for generating the Excel file
                Task<Void> excelTask = new Task<>() {
                    @Override
                    protected Void call() throws Exception {
                        new ExcelUtils().generateExcelFiles(botJobLoadList, allActions, extractedData, true);
                        return null;
                    }
                };

                if (extractedData != null) {

                    // Prepare the combined text container for the dialog
                    // You can add more content to the combinedTextContainer if needed

                    // Show confirmation dialog
                    boolean confirmed = performMessage.showAlertCombinedVBOX(
                            AlertType.CONFIRMATION,
                            "Warning: Excel File Already Exists",
                            "The Excel file already exists. Would you like to overwrite it?",
                            null,
                            combinedTextContainer);

                    if (confirmed) {

                        new Thread(excelTask).start();

                        performMessage.showAlertCombinedVBOX(
                                AlertType.INFORMATION,
                                "Warning: Excel File Already Exists",
                                "Success Excel File Override.", // No header text
                                null,
                                combinedTextContainer);
                    }
                } else {
                    // If file does not exist, start the Excel generation task directly

                    new Thread(excelTask).start();

                    // Show confirmation dialog
                    performMessage.showAlertCombinedVBOX(
                            AlertType.INFORMATION,
                            "Warning: New Excel File Created!",
                            "Success Excel File Generated.", // No header text
                            null,
                            combinedTextContainer);
                }
            }
        });
        this.openExcelFilterPanelButton.setOnMouseClicked((e) -> {
            (new ARExportFilterScene(this.botJobLoad)).show();
        });
        this.launchBotJobButton.setOnMouseClicked((e) -> {
            ARPropertyManager managerProps = ARPropertyManager.getInstance();
            String enginePath = managerProps.getProperty(ARPropertyEnum.PATH_ENGINE) + "\\AR_Web_Engine.jar";
            String excelPath = managerProps.getProperty(ARPropertyEnum.FOLDER_PATH_EXCEL);
            excelPath = excelPath + "\\" + this.botJobLoad.getName() + ".xlsx";
            if (!(new File(excelPath)).exists()) {
                new ARAlertScene(
                        AlertType.WARNING,
                        "Missing file excel",
                        "Please generate and compile the data of the file excel first before launching the bot job",
                        new ButtonType[] {ButtonType.OK});
            }

            String[] command = new String[] {
                "cmd.exe",
                "/c",
                ".\\java\\bin\\java.exe",
                "-jar",
                "\"" + enginePath + "\"",
                "execute/j",
                String.valueOf(this.botJobLoad.getHomeBankingLoadDTO().getId()),
                String.valueOf(this.botJobLoad.getId()),
                "\"" + excelPath + "\"",
                "-c",
                ARPropertyManager.getConfigurationFileName()
            };
            ProcessBuilder processBuilder = new ProcessBuilder(command);
            processBuilder.directory(new File(ARConstants.CURRENT_PATH));
            String logPath = ARPropertyManager.getInstance().getProperty(ARPropertyEnum.FOLDER_PATH_LOG);
            File output = new File(logPath + "\\engine_debug_log_output.log");
            File error = new File(logPath + "\\engine_debug_log_error.log");
            File input = new File(logPath + "\\engine_debug_log_input.log");
            List<File> files = new ArrayList<File>();
            files.add(output);
            files.add(error);
            files.add(input);

            Iterator<File> var11 = files.iterator();

            while (var11.hasNext()) {
                File file = (File) var11.next();
                if (!file.exists()) {
                    try {
                        file.createNewFile();
                    } catch (IOException var15) {
                        var15.printStackTrace();
                    }
                }
            }

            processBuilder.redirectOutput(output);
            processBuilder.redirectError(error);
            processBuilder.redirectInput(input);

            try {
                processBuilder.start();
            } catch (IOException var14) {
                var14.printStackTrace();
            }
        });
        this.closeBotJobButton.setOnMouseClicked((e) -> {
            stopWebSocketServer();
            Stage stage = (Stage) ((Button) e.getSource()).getScene().getWindow();
            stage.close();
        });
        this.openExcelFileButton.setOnMouseClicked((e) -> {
            String excelFolderPath = ARPropertyManager.getInstance().getProperty(ARPropertyEnum.FOLDER_PATH_EXCEL);
            String fileName =
                    String.format("%s/%s%s", excelFolderPath, this.botJobLoad.getName(), ARConstants.FILE_FORMAT_EXCEL);

            //        List<BlockLoadDTO> blocksLoaded = botLoadJobs.get(0).getBlockLoadDTOList();

            // Create a File object
            File fileCheck = new File(fileName);
            if (!fileCheck.exists() && !fileCheck.isDirectory()) {
                Text variableText1Styled = new Text("File Excel Does not Exist");
                variableText1Styled.setStyle("-fx-font-size: 18px; -fx-fill: blue;");

                fileName = fileName.replace("/", "\\");
                Text variableText3Styled = new Text(fileName);
                variableText3Styled.setStyle("-fx-font-size: 18px; -fx-fill: red;");

                VBox combinedTextContainer = new VBox();
                combinedTextContainer.setSpacing(5); // Add some sp

                combinedTextContainer.getChildren().addAll(variableText1Styled, variableText3Styled);

                performMessage.showAlertCombinedVBOX(
                        Alert.AlertType.ERROR, "Excel File Error", "File Not Exist!", null, combinedTextContainer);
                return;
                //            Platform.exit();
            } else {

                try {
                    String excelFilePath =
                            ARPropertyManager.getInstance().getProperty(ARPropertyEnum.FOLDER_PATH_EXCEL);
                    excelFilePath = excelFilePath + "\\" + this.botJobLoad.getName() + ".xlsx";
                    File file = new File(excelFilePath);
                    Desktop.getDesktop().open(file);
                    //                    Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " +
                    // excelFilePath);
                } catch (IOException var3) {

                    Text variableText1Styled = new Text("Verify the Possible Errors:");
                    variableText1Styled.setStyle("-fx-font-size: 18px; -fx-fill: blue;");

                    Text variableText2Styled = new Text("Error load the Excel Rows");
                    variableText2Styled.setStyle("-fx-font-size: 18px; -fx-fill: red;");

                    Text variableText3Styled = new Text("Maybe is Better to Re-Generate the File");
                    variableText3Styled.setStyle("-fx-font-size: 18px; -fx-fill: red;");

                    VBox combinedTextContainer = new VBox();
                    combinedTextContainer.setSpacing(5); // Add some sp

                    combinedTextContainer
                            .getChildren()
                            .addAll(variableText1Styled, variableText2Styled, variableText3Styled);

                    performMessage.showAlertCombinedVBOX(
                            Alert.AlertType.ERROR,
                            "Excel File Error",
                            "Check All Excel Columns and Values!",
                            null,
                            combinedTextContainer);
                    return;
                }
            }
        });
        this.componentButton.setOnMouseClicked((e) -> {
            if (isComponentBoxVisible) {
                componentBox.getChildren().clear();

                componentBox.getChildren().add(this.webView);
                componentBox.requestLayout();
                componentContainer.requestLayout();
                //                this.componentContainer.setManaged(false);

            } else {

                componentBox.getChildren().clear();
                componentBox.getChildren().addAll(this.webView, this.componentContainer);

                componentBox.requestLayout();
                componentContainer.requestLayout();
                //                this.componentContainer.setVisible(true);
                //                this.componentContainer.setManaged(true);
            }
            isComponentBoxVisible = !isComponentBoxVisible;
        });
    }

    private void executeScannerTask() {

        HomeBankingLoadDTO homeBankingLoadDTO = performDataBase.loadHomeBanking(this.botJobLoad.getHomeBankingId());

        try {
            Platform.runLater(() -> {
                try {
                    // Call the ARScannedElementScene here
                    ARScannedElementScene scene = arScannedElementScene.initialize(
                            homeBankingLoadDTO.getPriority(),
                            this.botJobLoad.getId(),
                            this.botJobLoad.getBlockLoadDTOList() != null
                                            && this.botJobLoad
                                                            .getBlockLoadDTOList()
                                                            .size()
                                                    > 0
                                    ? this.botJobLoad
                                            .getBlockLoadDTOList()
                                            .get(0)
                                            .getId()
                                    : null);

                    scene.show(); // Make sure the scene is shown
                } catch (Exception ex) {
                    handleExceptionScan(ex);
                }
            });
        } catch (Exception ex) {
            handleExceptionScan(ex);
        }
    }

    private void handleExceptionScan(Exception error) {
        // Log the exception
        ARLogger.getInstance(ARWebDriver.class)
                .severe("ERROR Calling openScannerButton -> Cause: " + error.getMessage());

        // Display the error message to the user
        if (error.getMessage().contains("no such window: target window already closed")
                || error.getMessage().contains("web view not found")) {
            performMessage.errorMessage(
                    "Error Calling SCAN",
                    "Web Browser was closed before the Scanner Tool",
                    "Close and Re-Open the Scanner Tool",
                    null,
                    null,
                    0);
        } else {

            if (!error.getMessage().contains("Current browser version")) {
                String[] lines = error.getMessage().split("\n");

                String msg1 = null;
                String msg2 = null;
                String msg3 = null;
                String msg4 = null;

                for (String line : lines) {
                    // Exclude unnecessary lines
                    if (line.contains("Host info")
                            || line.contains("Build info")
                            || line.contains("System info")
                            || line.contains("Command")) {
                        continue;
                    }

                    String message = line.contains("Message: ")
                            ? line.substring(line.indexOf("Message: ") + "Message: ".length())
                                    .trim()
                            : line.trim();

                    if (!message.isEmpty()) {
                        if (msg1 == null) {
                            msg1 = message;
                        } else if (msg2 == null) {
                            msg2 = message;
                        } else if (msg3 == null) {
                            msg3 = message;
                        } else if (msg4 == null) {
                            msg4 = message;
                        }
                    }
                }

                ARLogger.getInstance(ARWebDriver.class).severe("Error Open URL: \n" + msg1 + "\n" + msg2);

                performMessage.errorMessage("Error Open URL", msg1, msg2, msg3, msg4, 0);
            }
        }

        //        Platform.runLater(() -> {
        //            JOptionPane.showMessageDialog(
        //                    null,
        //                    "An error has occurred Calling SCAN: \nCause: " + ex.getMessage(),
        //                    "Error calling in SCAN",
        //                    JOptionPane.ERROR_MESSAGE);
        //        });
    }

    private void showAlert(String title, String content) {
        executorService = Executors.newSingleThreadExecutor();
        alertToShow.setAlertType(AlertType.ERROR);
        alertToShow.setTitle("Error");
        alertToShow.setHeaderText(title);
        alertToShow.setContentText(content);

        executorService.execute(() -> {
            timeline.setCycleCount(SECONDS); // Run for seconds
            timeline.play(); // Start the timeline

            // Show the alert on the JavaFX Application Thread
            javafx.application.Platform.runLater(() -> alertToShow.showAndWait());
        });

        if (executorService != null) {
            remainingSeconds = SECONDS;
            executorService.shutdown();
        }
    }

    public Pane getPaneReference() {
        AnchorPane acAnchorPane = new AnchorPane(new Node[] {this.botJobContainer});
        acAnchorPane.setUserData(this);
        return acAnchorPane;
    }

    private void initComponentUI() {
        this.componentButton = builder.buildButton(
                "",
                ARConstants.SPACE_L,
                "/Cubes.png",
                ARConstants.SPACE_L + 10.0D,
                Insets.EMPTY,
                Background.fill(Color.TRANSPARENT));
        ObservableList<ComponentBlockDTO> componentBlockDTO =
                ARSharedResources.getInstance().getEntityList(ComponentBlockDTO.class);
        this.componentList = new ListView<ComponentBlockDTO>(componentBlockDTO);

        componentList.setCellFactory(new ARCellFactory<>(ComponentListCell.class)::call);
        this.componentList.setMaxHeight(Double.MAX_VALUE);
        this.componentList.setPrefHeight(900.0D);
        this.componentList.setUserData(this);
        this.componentList.getUserData();
        VBox.setVgrow(componentList, Priority.ALWAYS);

        Label componentTitleLabel = new Label("Components");
        componentTitleLabel.setPadding(new Insets(5.0D));
        componentTitleLabel.setFont(
                Font.font((String) null, FontWeight.BOLD, FontPosture.REGULAR, ARConstants.SPACE_SM + 4.0D));

        Label searchLabel = new Label("Find");
        searchLabel.setPadding(new Insets(5.0D));
        searchLabel.setFont(
                Font.font((String) null, FontWeight.BOLD, FontPosture.REGULAR, ARConstants.SPACE_SM + 2.0D));
        TextField searchTextField = new TextField();

        searchTextField.textProperty().addListener((observable, oldValue, newValue) -> {
            ObservableList<ComponentBlockDTO> componentBlockDTOS;
            if (!newValue.equals("")) {
                System.out.println(newValue + " Text");
                componentBlockDTOS = ARSharedResources.getInstance()
                        .getEntityList(ComponentBlockDTO.class, (savedBlock) -> {
                            return savedBlock.getName().toLowerCase().contains(newValue.toLowerCase());
                        });
            } else {
                componentBlockDTOS = ARSharedResources.getInstance().getEntityList(ComponentBlockDTO.class);
            }

            this.componentList.setItems(componentBlockDTOS);
            this.componentList.refresh();
        });

        //        createMockSavedBlocksDTOs();

        HBox searchPaneBox = new HBox(new Node[] {searchLabel, searchTextField});
        searchPaneBox.setMaxHeight(ARConstants.SPACE_XL);
        searchPaneBox.setSpacing(ARConstants.SPACE_XXS);
        HBox.setHgrow(searchTextField, Priority.ALWAYS);

        this.componentContainer = new VBox(new Node[] {searchPaneBox, componentList});
        this.componentContainer.setSpacing(ARConstants.SPACE_XS);

        //        this.componentContainer.setMaxWidth(800.0D);
        isComponentBoxVisible = false;
    }

    public BotJobLoadDTO getBotJobDTO() {
        return this.botJobLoad;
    }

    private void initializeDatabase() {

        String dbPath = ARPropertyManager.getInstance().getProperty(ARPropertyEnum.FOLDER_PATH_DB);
        String dbUrl = CONNECTION_TYPE + dbPath + ARConstants.FILE_NAME_DB + CONNECTION_PARAMETERS;

        File dbFile = new File(dbPath + ARConstants.FILE_NAME_DB);
        if (!dbFile.exists()) {
            try (Connection conn = DriverManager.getConnection(dbUrl)) {
                try (Statement stmt = conn.createStatement()) {
                    String createTableSQL = "CREATE TABLE home_banking (" + "ID AUTOINCREMENT PRIMARY KEY, "
                            + "name TEXT, password TEXT, url TEXT, username TEXT, priority TEXT)";
                    stmt.executeUpdate(createTableSQL);
                }
                System.out.println(String.format("Database %s has bee created!", dbFile.getName()));
            } catch (SQLException e) {
                ARLogger.getInstance(ARViewBotJobPane.class).severe("initializeDatabase\nError: " + e.getMessage());
            }
        } else {
            ARLogger.getInstance(ARViewBotJobPane.class)
                    .info(String.format("Database '%s' Already exist!", dbFile.getName()));
        }
    }

    public List<InstructionDTO> getInstructionsByBlockId(int botJobId, int blockId) {
        // List to store the fetched instructions
        List<InstructionDTO> instructions = new ArrayList<>();

        // Build the SQL query statement
        String querySQL =
                "SELECT * FROM instruction WHERE block_id = " + blockId + " order by instruction_order_number ASC";

        // Execute the query and process the result set
        try (Statement stmt = ARSharedResources.getInstance().getConnection().createStatement();
                ResultSet rs = stmt.executeQuery(querySQL)) {

            while (rs.next()) {
                // Assuming you have an Instruction class, populate it with data from the ResultSet
                InstructionDTO instruction = new InstructionDTO();
                instruction.setInstructionId(rs.getInt("id"));
                instruction.setInstructionName(rs.getString("name"));
                instruction.setInstructionOrderNumber(rs.getInt("instruction_order_number"));
                instruction.setBlockId(rs.getInt("block_id"));
                instruction.setBlockOrderNumber(instruction.getBlockOrderNumber());
                instruction.setBotJobId(botJobId);

                instruction.setActions(rs.getString("actions"));
                instruction.setPath(rs.getString("path"));
                instruction.setCoordinates(rs.getString("coordinates"));
                instruction.setForceCoordinates(rs.getBoolean("force_coordinates"));
                instruction.setIFrameXPath(rs.getString("iframe_xpath"));
                instruction.setDescription(rs.getString("description"));
                instruction.setOptional(rs.getBoolean("optional"));
                instruction.setActionCustomMaxWaitSec(rs.getInt("action_custom_max_wait_sec"));
                instruction.setOnHoldSeconds(rs.getInt("on_hold_seconds"));
                instruction.setCodified(rs.getBoolean("codified"));
                instruction.setExportToABR(rs.getBoolean("export_to_abr"));
                instruction.setInstructionActive(rs.getBoolean("active"));

                // Add the instruction to the list
                instructions.add(instruction);
            }

            ARLogger.getInstance(ARWebDriver.class)
                    .info(String.format("Fetched %d instructions for Block ID %d:", instructions.size(), blockId));

        } catch (SQLException e) {
            ARLogger.getInstance(ARWebDriver.class)
                    .severe(String.format(
                            "Error fetching instructions for Block ID %d. Error: %s: ", blockId, e.getMessage()));
        }

        return instructions;
    }

    public boolean reorderInstructions(List<InstructionDTO> rowList) {
        int orderNumber = 1;

        // Iterate through the list and update the instructionOrderNumber
        for (InstructionDTO instruction : rowList) {
            instruction.setInstructionOrderNumber(orderNumber);
            orderNumber++; // Increment the order number for the next instruction
        }

        // Build the SQL update statement
        try (Statement stmt = ARSharedResources.getInstance().getConnection().createStatement()) {
            // Loop through each instruction in the rowList
            for (InstructionDTO instruction : rowList) {
                // Increment the instructionOrderNumber by 1 for each instruction
                String updateSQL = "UPDATE instruction SET  "
                        + " instruction_order_number = " + instruction.getInstructionOrderNumber()
                        + " WHERE id = " + instruction.getInstructionId()
                        + " AND block_id = " + instruction.getBlockId();

                int rowsAffected = stmt.executeUpdate(updateSQL);
                if (rowsAffected > 0) {
                    //                    ARLogger.getInstance(ARWebDriver.class)
                    //                            .warning(String.format(
                    //                                    "preInsertStep - InstructionId: %s in BlockId: %s now has
                    // order number: %d",
                    //                                    instruction.getInstructionId(),
                    //                                    instruction.getBlockId(),
                    //                                    instruction.getInstructionOrderNumber() + 1));
                } else {
                    ARLogger.getInstance(ARWebDriver.class)
                            .info(String.format(
                                    "preInsertStep - No matching record found for BlockId: %d and InstructionId: %d",
                                    instruction.getBlockId(), instruction.getInstructionId()));
                }
            }

            return true;
        } catch (SQLException e) {
            ARLogger.getInstance(ARWebDriver.class)
                    .severe(String.format("Error updating instruction order numbers.\nError: %s", e.getMessage()));
        }
        return false;
    }

    private void createMockSavedBlocksDTOs() {
        // Create mock data for SavedBlocksDTO
        ObservableList<ComponentBlockDTO> componentBlockDTOS = FXCollections.observableArrayList();

        // Create mock SavedBlockLoopInstructionDTO entries
        ComponentInstructionDTO instruction1 = new ComponentInstructionDTO();
        instruction1.setInstructionOrderNumber(1);
        instruction1.setActions("Action 1");
        instruction1.setName("Instruction 1");
        instruction1.setPath("/path/to/instruction1");
        instruction1.setDescription("Description for Instruction 1");
        instruction1.setOptional(false);
        instruction1.setDefaultValue("default1");
        instruction1.setActionCustomMaxWaitSec(10);
        instruction1.setOnHoldSeconds(5);
        instruction1.setCodified(false);
        instruction1.setExportToABR(true);
        instruction1.setActive(true);

        ComponentInstructionDTO instruction2 = new ComponentInstructionDTO();
        instruction2.setInstructionOrderNumber(2);
        instruction2.setActions("Action 2");
        instruction2.setName("Instruction 2");
        instruction2.setPath("/path/to/instruction2");
        instruction2.setDescription("Description for Instruction 2");
        instruction2.setOptional(false);
        instruction2.setDefaultValue("default2");
        instruction2.setActionCustomMaxWaitSec(20);
        instruction2.setOnHoldSeconds(10);
        instruction2.setCodified(false);
        instruction2.setExportToABR(true);
        instruction1.setActive(true);

        // Assign mock instructions to mock blocks
        ComponentBlockDTO block1 = new ComponentBlockDTO();
        block1.setName("Block One");
        block1.setDescription("Description for Block One");
        block1.setTypeId(1);
        block1.setActive(true);
        block1.setWait(3);
        block1.setSavedBlockLoopInstructions(new ArrayList<>(List.of(instruction1))); // Assign instruction1 to block1

        ComponentBlockDTO block2 = new ComponentBlockDTO();
        block2.setName("Block Two");
        block2.setDescription("Description for Block Two");
        block2.setTypeId(2);
        block2.setActive(true);
        block2.setWait(3);
        block2.setSavedBlockLoopInstructions(new ArrayList<>(List.of(instruction2))); // Assign instruction2 to block2

        ComponentBlockDTO block3 = new ComponentBlockDTO();
        block3.setName("Another Block");
        block3.setDescription("Description for Another Block");
        block3.setTypeId(3);
        block3.setActive(true);
        block3.setWait(3);
        block3.setSavedBlockLoopInstructions(new ArrayList<>()); // No instructions for this block

        ComponentBlockDTO block4 = new ComponentBlockDTO();
        block4.setName("Sample Block");
        block4.setDescription("Description for Sample Block");
        block4.setTypeId(4);
        block4.setSavedBlockLoopInstructions(new ArrayList<>()); // No instructions for this block

        // Add mock blocks to the ObservableList
        componentBlockDTOS.addAll(block1, block2, block3, block4);

        this.componentList.setItems(componentBlockDTOS);
    }
}
